package com.tyshi00.trinkets

// Original, wholesome, dad-style jokes written for Trinkets. Nothing here is
// copied from an external joke database. See docs/CONTENT.md for how to
// keep growing this bucket toward the long-term 2,500 target.
object TrinketsJokes {
    val ALL: List<Joke> = listOf(
        Joke(1, "Why don't scientists trust atoms?", "Because they make up everything."),
        Joke(2, "What do you call a fish with no eyes?", "A fsh."),
        Joke(3, "Why did the scarecrow win an award?", "Because he was outstanding in his field."),
        Joke(4, "What do you call a bear with no teeth?", "A gummy bear."),
        Joke(5, "Why did the bicycle fall over?", "It was two-tired."),
        Joke(6, "What do you call a factory that makes okay products?", "A satisfactory."),
        Joke(7, "Why don't eggs tell jokes?", "They'd crack each other up."),
        Joke(8, "What did the ocean say to the shore?", "Nothing, it just waved."),
        Joke(9, "Why can't your nose be twelve inches long?", "Because then it would be a foot."),
        Joke(10, "What do you call cheese that isn't yours?", "Nacho cheese."),
        Joke(11, "Why did the coffee file a police report?", "It got mugged."),
        Joke(12, "What's orange and sounds like a parrot?", "A carrot."),
        Joke(13, "Why did the math book look sad?", "It had too many problems."),
        Joke(14, "What do you call a can opener that doesn't work?", "A can't opener."),
        Joke(15, "Why did the golfer bring two pairs of pants?", "In case he got a hole in one."),
        Joke(16, "What do you call a sleeping dinosaur?", "A dino-snore."),
        Joke(17, "Why don't skeletons fight each other?", "They don't have the guts."),
        Joke(18, "What did one wall say to the other wall?", "I'll meet you at the corner."),
        Joke(19, "Why did the tomato turn red?", "Because it saw the salad dressing."),
        Joke(20, "What do you call a boomerang that won't come back?", "A stick."),
        Joke(21, "Why did the picture go to jail?", "Because it was framed."),
        Joke(22, "What's the best time to go to the dentist?", "Tooth-hurty."),
        Joke(23, "Why did the cookie go to the doctor?", "Because it was feeling crummy."),
        Joke(24, "What do you call a dog magician?", "A labracadabrador."),
        Joke(25, "Why did the stadium get hot after the game?", "All the fans left."),
        Joke(26, "What do you call an alligator in a vest?", "An investigator."),
        Joke(27, "Why did the computer go to the doctor?", "It caught a virus."),
        Joke(28, "What do you call a pig that does karate?", "A pork chop."),
        Joke(29, "Why did the banana go to the doctor?", "It wasn't peeling well."),
        Joke(30, "What do you call a group of musical whales?", "An orca-stra."),
        Joke(31, "Why did the belt get arrested?", "It held up a pair of pants."),
        Joke(32, "What do you call a fake noodle?", "An impasta."),
        Joke(33, "Why did the astronaut break up with his girlfriend?", "He needed space."),
        Joke(34, "What do you call a snowman in July?", "A puddle."),
        Joke(35, "Why did the light bulb fail school?", "It wasn't very bright."),
        Joke(36, "What do you call a very small valentine?", "A valen-tiny."),
        Joke(37, "Why did the calendar look stressed?", "Its days were numbered."),
        Joke(38, "What do you call a fish that's terrible at giving directions?", "Lost at sea, and proud of it."),
        Joke(39, "Why did the mushroom get invited to the party?", "Because he's a fungi."),
        Joke(40, "What do you call a bee that can't make up its mind?", "A maybe."),
        Joke(41, "Why did the clock get sent to the principal's office?", "For tocking too much."),
        Joke(42, "What do you call a dinosaur that crashes his car?", "Tyrannosaurus wrecks."),
        Joke(43, "Why did the gym close down?", "It just didn't work out."),
        Joke(44, "What do you call two birds in love?", "Tweethearts."),
        Joke(45, "Why did the baker stop making donuts?", "He was tired of the hole business."),
        Joke(46, "What do you call a nervous javelin thrower?", "Shaky spear."),
        Joke(47, "Why did the string refuse to play tag?", "It was tired of being wound up."),
        Joke(48, "What do you call a sleepy cactus?", "A prick-crastinator."),
        Joke(49, "Why did the pencil go on vacation?", "It needed a break from the point."),
        Joke(50, "What do you call a lazy kangaroo?", "A pouch potato."),
        Joke(51, "Why did the melon jump into the lake?", "It wanted to be a watermelon."),
        Joke(52, "What do you call a duck that gets straight A's?", "A wise quacker."),
        Joke(53, "Why did the traffic light turn red?", "You would too if you had to change in front of everyone."),
        Joke(54, "What do you call a house that fell in love?", "A dwelling in affection."),
        Joke(55, "Why did the teapot get a promotion?", "It always had steam."),
        Joke(56, "What do you call a cow with a twitch?", "Beef jerky."),
        Joke(57, "Why did the potato win the race?", "It was a couch potato no more."),
        Joke(58, "What do you call a very polite iceberg?", "The tip of courtesy."),
        Joke(59, "Why did the shoe go to school?", "To get a little more sole."),
        Joke(60, "What do you call a sleepy pizza?", "A slice that dozed off."),
        Joke(61, "Why did the chef quit his job?", "He didn't have thyme."),
        Joke(62, "What do you call an owl who does magic tricks?", "Hoodini."),
        Joke(63, "Why did the ladder never get invited to parties?", "It always steps out."),
        Joke(64, "What do you call a nervous bug?", "A jitterbug."),
        Joke(65, "Why did the broom get a promotion?", "It was outstanding at sweeping the competition."),
        Joke(66, "What do you call a fish that needs help with vocals?", "Autotuna."),
        Joke(67, "Why did the sun go to school?", "To get a little brighter."),
        Joke(68, "What do you call a well-mannered mountain?", "Mount Curteous."),
        Joke(69, "Why did the jacket win the argument?", "It had great cover."),
        Joke(70, "What do you call a river that tells jokes?", "A stand-up current."),
        Joke(71, "Why did the paper get a raise?", "It was outstanding in its field of work."),
        Joke(72, "What do you call an elephant that never stops talking?", "A trumpeter."),
        Joke(73, "Why did the garden always know the news?", "The plants kept in touch with the grapevine."),
        Joke(74, "What do you call a bear caught in the rain?", "A drizzly bear."),
        Joke(75, "Why did the balloon skip the party?", "It didn't want to get too inflated."),
        Joke(76, "What do you call a well-organized closet?", "A hangout for hangers."),
        Joke(77, "Why did the seed refuse to grow?", "It wasn't ready to root for itself yet."),
        Joke(78, "What do you call a candle that's always on time?", "Very punc-wickual."),
        Joke(79, "Why did the kite finally feel free?", "It let go of its string of doubts."),
        Joke(80, "What do you call a quiet thunderstorm?", "A soft-spoken front."),
        Joke(81, "Why did the scientist install a knocker on his door?", "He wanted to win the No-bell prize."),
        Joke(82, "What do you call a dinosaur with a large vocabulary?", "A thesaurus."),
        Joke(83, "Why did the orange stop rolling down the hill?", "It ran out of juice."),
        Joke(84, "What do you call a fish that wears a bowtie?", "So-fish-ticated."),
        Joke(85, "Why did the birthday cake go to the doctor?", "It was feeling crumby."),
        Joke(86, "What do you call a group of disorganized cats?", "A cat-astrophe."),
        Joke(87, "Why did the frog take the bus to work?", "His car got toad away."),
        Joke(88, "What do you call a pile of kittens?", "A meowntain."),
        Joke(89, "Why did the grape stop in the middle of the road?", "It ran out of raisin."),
        Joke(90, "What do you call a well-behaved skeleton?", "A model citizen, right down to the bones."),
        Joke(91, "Why did the cheese go to the party alone?", "It didn't want to be brie-lonely."),
        Joke(92, "What do you call a snowman with a six pack?", "An abdominal snowman."),
        Joke(93, "Why did the book join the police force?", "It wanted to go undercover."),
        Joke(94, "What do you call two peanuts walking down the street?", "One was a-salted."),
        Joke(95, "Why did the shovel win an award?", "It was ground breaking."),
        Joke(96, "What do you call a nervous grape?", "One that gets a little whiny."),
        Joke(97, "Why did the mountain go to the doctor?", "It was feeling a little boulder than usual."),
        Joke(98, "What do you call a cow during an earthquake?", "A milkshake."),
        Joke(99, "Why did the tree take up banking?", "It wanted to grow its interest."),
        Joke(100, "What do you call a bear stuck in the rain with no umbrella?", "Wet."),
        Joke(101, "Why did the toaster get a promotion?", "It always popped up with good ideas."),
        Joke(102, "What do you call an ant that skips school?", "A truant."),
        Joke(103, "Why did the barber win the race?", "He knew a shortcut."),
        Joke(104, "What do you call a rich elf?", "Welfy."),
        Joke(105, "Why did the cloud stay home from the party?", "It was feeling under the weather."),
        Joke(106, "What do you call a fruit that's always jumpy?", "A nervous nectarine."),
        Joke(107, "Why did the peach get a therapist?", "It had trouble getting to the pit of its feelings."),
        Joke(108, "Why did the waterfall write a letter?", "It had a lot to get off its chest, and downhill from there."),
        Joke(109, "Why did the plant refuse to fight?", "It didn't want to leaf on bad terms."),
        Joke(110, "What do you call a chicken that counts its eggs?", "A mathema-chicken."),
        Joke(111, "Why did the flashlight win an award?", "It was outstanding in its own light."),
        Joke(112, "What do you call a well-mannered frog?", "Perfectly polite-poliwog."),
        Joke(113, "Why did the sock go to therapy?", "It kept getting lost and had abandonment issues."),
        Joke(114, "What do you call a spider that's excellent at math?", "A calcu-later."),
        Joke(115, "Why did the boat get a good grade?", "It was outstanding above sea level."),
        Joke(116, "What do you call an old snowball?", "Water under the bridge."),
        Joke(117, "Why did the map win an award?", "It always knew where it stood."),
        Joke(118, "What do you call a knight who's afraid to fight?", "Sir Render."),
        Joke(119, "Why did the drum go to the doctor?", "It felt like it was being taken for granted."),
        Joke(120, "What do you call a very organized garden?", "A plot with a plan."),
        Joke(121, "Why did the tomato blush at the party?", "It saw the salad undressing."),
        Joke(122, "What do you call a bird that's afraid of heights?", "A chicken, technically, but also just a nervous bird."),
        Joke(123, "Why did the window feel lonely?", "Because it was always looking out for others."),
        Joke(124, "Why did the alarm clock get promoted?", "It always rose to the occasion."),
        Joke(125, "Why did the doughnut visit the dentist?", "It needed a filling."),
        Joke(126, "What do you call a cat that's a great singer?", "A Meow-riah Carey."),
        Joke(127, "Why did the button get left off the shirt?", "It just wasn't fasten-ating enough that day."),
        Joke(128, "What do you call two crows sharing a phone?", "Shared-crow-plan."),
        Joke(129, "Why did the sofa refuse to move?", "It had really settled into its position."),
        Joke(130, "What do you call a lizard that sings?", "A rap-tile."),
        Joke(131, "Why did the fisherman throw his alarm clock in the lake?", "He wanted to start the day off on a good catch."),
        Joke(132, "Why did the storm apologize?", "It didn't mean to thunder in unannounced."),
        Joke(133, "Why did the vegetable garden feel proud?", "It had really turned over a new leaf."),
        Joke(134, "What do you call a train that sneezes?", "A-choo-choo train."),
        Joke(135, "Why did the mirror stay calm during the argument?", "It just reflected on things."),
        Joke(136, "What do you call a very tidy pirate?", "Captain Neat Beard."),
        Joke(137, "Why did the wheel refuse to argue?", "It didn't want to go in circles."),
        Joke(138, "What do you call an owl that's great at parties?", "A hoot."),
        Joke(139, "Why did the biscuit apply for a job?", "It wanted to earn its own dough."),
        Joke(140, "What do you call a snail on a ship?", "A snailor."),
        Joke(141, "Why did the raindrop get invited everywhere?", "It always knew how to make a splash."),
        Joke(142, "What do you call a musical vegetable?", "A turnip beat."),
        Joke(143, "Why did the pillow get promoted?", "It was always supportive."),
        Joke(144, "What do you call a smart pumpkin?", "A gourd-geous genius."),
        Joke(145, "Why did the umbrella get invited to every event?", "It always came prepared to shower people with kindness."),
        Joke(146, "What do you call a dog that does woodworking?", "A collie-carpenter."),
        Joke(147, "Why did the recipe book win an award?", "It always had the right ingredients for success."),
        Joke(148, "What do you call a well-rested mountain?", "Fully re-peaked."),
        Joke(149, "Why did the candle stay so calm?", "It never let anything get under its wick."),
        Joke(150, "What do you call a polite volcano?", "One that always erupts with good manners."),
        Joke(151, "Why did the clock in the cafeteria always seem off?", "It went back four seconds, every single second."),
        Joke(152, "What do you call a fish that plays basketball?", "A slam dunk-er with excellent form."),
        Joke(153, "Why did the beekeeper win an award?", "He was outstanding in his hive."),
        Joke(154, "What do you call a well-dressed lion?", "A dandy-lion."),
        Joke(155, "Why did the orange bring a map?", "It didn't want to get lost in the fruit bowl."),
        Joke(156, "What do you call a nervous elevator?", "One with a lot of ups and downs."),
        Joke(157, "Why did the bicycle stay home from the party?", "It just couldn't find the wheel motivation."),
        Joke(158, "What do you call a pony with a cough?", "A little hoarse."),
        Joke(159, "Why did the popcorn get a promotion?", "It always popped at the right moment."),
        Joke(160, "What do you call a snake that works for the government?", "A civil serpent."),
        Joke(161, "What do you call a calendar that tells jokes?", "A real date-based comedian."),
        Joke(162, "What do you call a magician who's also a cat?", "A magic-purr-ist."),
        Joke(163, "Why did the chef stop telling jokes?", "His timing was a little too well done."),
        Joke(164, "What do you call a very organized beach?", "A shore thing."),
        Joke(165, "Why did the light switch feel proud?", "It had really turned things around."),
        Joke(166, "Why did the surfer bring a pencil to the beach?", "In case he wanted to draw a wave."),
        Joke(167, "Why did the tree get promoted?", "It always branched out."),
        Joke(168, "What do you call a shy pebble?", "A little boulder than most, but still shy."),
        Joke(169, "Why did the ocean apply for a loan?", "It wanted to expand its shore-folio."),
        Joke(170, "What do you call a well-mannered shark?", "One that always says please before it bites into a joke."),
        Joke(171, "Why did the garden gnome get promoted?", "He was always grounded and dependable."),
        Joke(172, "What do you call a spider who just won the lottery?", "A very lucky charm, and also incredibly rich for a spider."),
        Joke(173, "Why did the kite feel so confident?", "It had really learned to rise above things."),
        Joke(174, "What do you call a peaceful pepper?", "Mild mannered, in every sense."),
        Joke(175, "Why did the river get an award?", "It always went with the flow and still got things done."),
        Joke(176, "What do you call a lazy sheep?", "A ewe-nique kind of relaxed."),
        Joke(177, "Why did the stapler get promoted?", "It always held things together under pressure."),
        Joke(178, "What do you call a bear with no socks on?", "Barefoot, obviously, but also a little chilly."),
        Joke(179, "Why did the pencil sharpener get so popular?", "It always helped others put their best point forward."),
        Joke(180, "What do you call a duck that studies rocks?", "A geo-duck-ist."),
        Joke(181, "Why did the sunflower get invited everywhere?", "It always brought a bright outlook to the room."),
        Joke(182, "What do you call a cat who loves gardening?", "A meow-tanist."),
        Joke(183, "Why did the leaf apologize?", "It didn't mean to fall for anyone that fast."),
        Joke(184, "What do you call a very calm ocean wave?", "Well adjusted, and also low tide."),
        Joke(185, "Why did the vacuum cleaner get a promotion?", "It really sucked up all the competition."),
        Joke(186, "What do you call a bee with great manners?", "A queen's favorite, honestly."),
        Joke(187, "Why did the road feel proud of itself?", "It had really gone the distance."),
        Joke(188, "What do you call a raccoon that tells jokes?", "A trash panda with great comedic timing."),
        Joke(189, "Why did the seed keep its secrets?", "It wasn't ready to spill yet."),
        Joke(190, "Why did the cloud get kicked out of school?", "It kept spacing out."),
        Joke(191, "Why did the shoelace get promoted?", "It always tied things together nicely."),
        Joke(192, "What do you call a dog who tells the best stories?", "A good boy with a great narrative arc."),
        Joke(193, "Why did the coat hanger feel appreciated?", "Someone finally gave it some support."),
        Joke(194, "What do you call a whale who loves to sing?", "An opera-whale."),
        Joke(195, "Why did the paperclip stay so calm?", "It just held everything together and didn't sweat the small stuff."),
        Joke(196, "What do you call a well-organized squirrel?", "One with a very solid nut budget."),
        Joke(197, "Why did the flashlight win the award?", "It always shed light on the situation."),
        Joke(198, "What do you call a turtle that tells the truth?", "A shell-abrating honest friend."),
        Joke(199, "Why did the fence feel confident?", "It knew exactly where it stood."),
        Joke(200, "What do you call a storm cloud with excellent posture?", "Well grounded, considering it's up so high."),
        Joke(201, "Why did the marker feel appreciated?", "People always drew attention to its good points."),
        Joke(202, "What do you call a fish that helps other fish with homework?", "A tutor-tuna."),
        Joke(203, "Why did the balloon feel confident before the party?", "It really knew how to rise to the occasion."),
        Joke(204, "What do you call a well-mannered wolf?", "A howl-ite gentleman."),
        Joke(205, "Why did the fern get such good reviews?", "It always knew how to leaf a good impression."),
        Joke(206, "What do you call a squirrel that always plans ahead?", "Nuts about being prepared, and proud of it."),
        Joke(207, "Why did the hammer feel proud of its work?", "It really nailed it every time."),
        Joke(208, "What do you call a duck who loves puzzles?", "Quack-ing the code, one piece at a time."),
        Joke(209, "Why did the garden hose stay so relaxed?", "It just went with the flow."),
        Joke(210, "Why did the ant refuse to share its snack?", "It didn't want to be picnicked on."),
        Joke(211, "Why did the broomstick feel appreciated?", "It always swept people off their feet, figuratively."),
        Joke(212, "What do you call a rabbit who tells great jokes?", "A real hare-larious character."),
        Joke(213, "Why did the toothbrush get promoted?", "It always brushed up on the details."),
        Joke(214, "What do you call an owl who loves math?", "A wise old calcu-owl-tor."),
        Joke(215, "Why did the pillowcase feel comfortable in interviews?", "It knew how to cover all the bases."),
        Joke(216, "What do you call a very supportive tree branch?", "A real limb of encouragement."),
        Joke(217, "Why did the crayon feel proud?", "It always colored inside its own confidence."),
        Joke(218, "What do you call a bird who loves to read?", "A well-read robin, with excellent taste."),
        Joke(219, "Why did the doorknob feel important?", "It was always the key to getting things open, metaphorically."),
        Joke(220, "What do you call a fish that leads the school?", "The head of the class, quite literally."),
        Joke(221, "Why did the sneaker feel accomplished?", "It really went the extra mile."),
        Joke(222, "What do you call a spider who loves to organize?", "A web designer with excellent structure."),
        Joke(223, "Why did the garden rake feel appreciated?", "It always helped people get their thoughts together."),
        Joke(224, "What do you call a very honest scarecrow?", "Straw-ight forward, through and through."),
        Joke(225, "Why did the teakettle feel proud after the party?", "It really brought the heat when it counted."),
        Joke(226, "What do you call a dolphin who tells the best jokes?", "A real fin-tastic comedian."),
        Joke(227, "Why did the pencil case feel so organized?", "It always kept its things in order, point by point."),
        Joke(228, "What do you call a caterpillar who loves fashion?", "A trendsetter in training, before its big transformation."),
        Joke(229, "Why did the mailbox feel appreciated?", "People always dropped by with something for it."),
        Joke(230, "Why did the snail refuse to race the hare?", "It knew this story before it even started."),
        Joke(231, "Why did the apple stop mid bite?", "It ran into a little core issue."),
        Joke(232, "What do you call a bear who works in real estate?", "A real es-paw-te agent."),
        Joke(233, "Why did the light bulb apply for a raise?", "It felt it deserved a brighter future."),
        Joke(234, "Why did the penguin bring a suitcase to the beach?", "It heard the ice was thin on vacation plans."),
        Joke(235, "Why did the cactus win the popularity contest?", "Everyone thought it was a real point of interest."),
        Joke(236, "What do you call a raincoat that tells jokes?", "A real riot when the weather turns."),
        Joke(237, "Why did the sandwich feel confident?", "It knew it had all the right layers."),
        Joke(238, "What do you call a mushroom that throws great parties?", "A real fungi to be around."),
        Joke(239, "Why did the traffic cone get promoted?", "It always knew how to direct attention."),
        Joke(240, "What do you call a spider with excellent taste in music?", "A web deejay."),
        Joke(241, "Why did the sock puppet get such rave reviews?", "It really had a lot of character."),
        Joke(242, "What do you call a well-organized toolbox?", "A model of good structure, screw by screw."),
        Joke(243, "Why did the strawberry take a day off?", "It was in a bit of a jam."),
        Joke(244, "What do you call a very confident scarecrow?", "One that's not afraid to stand out in a field."),
        Joke(245, "Why did the teabag feel so relaxed?", "It just let things steep for a while."),
        Joke(246, "What do you call a squirrel who tells the best stories?", "The nut with the best material in the park."),
        Joke(247, "Why did the wallet feel proud?", "It always had something to show for itself."),
        Joke(248, "Why did the snowflake break up with the icicle?", "It said the relationship was going nowhere, slowly."),
        Joke(249, "Why did the compass feel so confident?", "It always knew which way to go."),
        Joke(250, "What do you call a bird who's an excellent listener?", "A real good egg, through and through."),
        Joke(251, "Why did the pumpkin get invited to every party?", "It always brought great seasonal energy."),
        Joke(252, "What do you call a very dependable ladder?", "Someone you can really count on to help you rise up."),
        Joke(253, "Why did the fish refuse to share its snack?", "It was a little shellfish, if we're being honest."),
        Joke(254, "What do you call a well-organized spice rack?", "A model of good seasoning judgment."),
        Joke(255, "Why did the kite feel so proud of itself?", "It really knew how to keep its head up."),
        Joke(256, "What do you call a squirrel that's great at chess?", "A strategic little nut."),
        Joke(257, "Why did the umbrella win employee of the month?", "It always showed up prepared for the storm."),
        Joke(258, "What do you call a very generous tree?", "One that's always willing to branch out for others."),
        Joke(259, "Why did the potato apply for a passport?", "It wanted to see the world, one eye at a time."),
        Joke(260, "What do you call a fish that's great at giving directions?", "A very reliable navi-gator, even if it's technically a fish."),
        Joke(261, "Why did the clock feel so accomplished?", "It always made time for everyone."),
        Joke(262, "What do you call a well-organized bookshelf?", "A story well told, in every sense."),
        Joke(263, "Why did the balloon go to therapy?", "It had trouble letting things go."),
        Joke(264, "Why did the snail stay off social media?", "It didn't want to get caught up in the fast lane."),
        Joke(265, "Why did the recipe card feel appreciated?", "People always followed its lead."),
        Joke(266, "What do you call a duck who gives great advice?", "A real quack of wisdom, believe it or not."),
        Joke(267, "Why did the picture frame feel so proud?", "It always knew how to showcase the good stuff."),
        Joke(268, "Why did the raincloud bring a comedian?", "It wanted to make a real downpour of laughs."),
        Joke(269, "Why did the sunflower always stand tall?", "It just liked keeping its chin up toward the light."),
        Joke(270, "What do you call a well-mannered octopus?", "One with eight excellent handshakes."),
        Joke(271, "Why did the garden gate feel so confident?", "It always knew exactly where it stood."),
        Joke(272, "What do you call a very supportive pillow?", "The best shoulder to lean on, literally."),
        Joke(273, "Why did the candle feel proud of its work?", "It always brightened up the room."),
        Joke(274, "What do you call a well-organized picnic basket?", "A model of good planning, sandwich by sandwich."),
        Joke(275, "Why did the paintbrush feel so accomplished?", "It always added a little color to the day."),
        Joke(276, "Why did the alarm clock apologize?", "It felt bad about all the mixed wake-up calls."),
        Joke(277, "Why did the welcome mat feel so appreciated?", "It always made a great first impression."),
        Joke(278, "What do you call a garden hose with great manners?", "One that always waters things down politely."),
        Joke(279, "Why did the bookmark feel so useful?", "It always knew exactly where things left off."),
        Joke(280, "What do you call a well-organized toolbox owner?", "Someone who really has it all screwed together."),
        Joke(281, "Why did the winter coat break up with the scarf?", "It felt smothered."),
        Joke(282, "Why did the mailbox start a diary?", "It had a lot of correspondence to keep track of."),
        Joke(283, "Why did the garden path refuse to gossip?", "It didn't want to lead anyone astray."),
        Joke(284, "What do you call a raindrop that tells the truth?", "Straight down honest."),
        Joke(285, "Why did the picture book get a library card?", "It wanted to check itself out."),
        Joke(286, "Why did the flashlight break up with the candle?", "It said the spark just wasn't there anymore."),
        Joke(287, "Why did the garden bench refuse to move?", "It had really taken a seat in life."),
        Joke(288, "Why did the junk drawer file a complaint?", "It felt overqualified for the job."),
        Joke(289, "Why did the wind chime get invited to the band?", "It already had the whole ensemble down."),
        Joke(290, "Why did the street lamp fail the test?", "It kept dimming out during the hard questions."),
        Joke(291, "Why did the garden fence apply for a loan?", "It wanted to expand its property line of credit."),
        Joke(292, "Why did the breeze get a warning?", "It kept blowing past the speed limit."),
        Joke(293, "Why did the toolbox drawer go to therapy?", "It had trouble opening up."),
        Joke(294, "What do you call a very dependable morning routine?", "A creature of habit, and proud of it."),
        Joke(295, "Why did the brick wall become a comedian?", "It really knew how to build a punchline."),
        Joke(296, "Why did the spice drawer get promoted?", "It really knew how to season the deal."),
        Joke(297, "Why did the front porch refuse to gossip?", "It didn't want anyone talking behind its back."),
        Joke(298, "Why did the doorbell get stage fright?", "It wasn't used to being the center of attention, ringing true."),
        Joke(299, "Why did the garden trowel start a band?", "It really liked to dig the music."),
        Joke(300, "Why did the kite string take up boxing?", "It knew how to keep things taut."),
        Joke(301, "Why did the garden shed run for office?", "It had all the right tools for the job."),
        Joke(302, "Why did the weather vane get invited to every party?", "It always knew which way the wind was blowing."),
        Joke(303, "Why did the coat rack apply for a job?", "It really wanted to hang in there."),
        Joke(304, "Why did the recipe box get promoted?", "It always had the inside scoop."),
        Joke(305, "Why did the front step file a complaint?", "Everyone kept walking all over it."),
        Joke(306, "Why did the gate latch refuse to gossip?", "It knew how to keep things under lock and key."),
        Joke(307, "Why did the toolbox handle get a raise?", "It really carried the whole team."),
        Joke(308, "Why did the doormat apply to law school?", "It wanted to learn how to properly wipe the slate clean."),
        Joke(309, "Why did the porch light get promoted?", "It really knew how to shine at work."),
        Joke(310, "Why did the mailbox flag get stage fright?", "It wasn't used to standing up in front of everyone."),
        Joke(311, "Why did the garden hose reel win an award?", "It really had its act coiled together."),
        Joke(312, "Why did the spice jars start a band?", "They really knew how to shake things up."),
        Joke(313, "Why did the umbrella stand run for office?", "It promised to weather any storm."),
        Joke(314, "Why did the welcome sign get nervous?", "It's always the first one to greet the crowd."),
        Joke(315, "Why did the garden bell take up singing?", "It already had perfect pitch."),
        Joke(316, "Why did the wind sock refuse to argue?", "It just went whichever way the conversation blew."),
        Joke(317, "Why did the shed key go to therapy?", "It had trouble opening up about its feelings."),
        Joke(318, "Why did the garden gnome start comedy?", "He always had a stone-faced delivery."),
        Joke(319, "Why did the gate hinge get promoted?", "It really knew how to swing a deal."),
        Joke(320, "Why did the junk drawer file for a promotion?", "It had way more range than anyone gave it credit for."),
        Joke(321, "Why did the trellis get a standing ovation?", "It really knew how to support a rising star."),
        Joke(322, "Why did the porch swing never worry?", "It always had good back-and-forth support."),
        Joke(323, "Why did the mailbox post refuse to move?", "It had really put down roots."),
        Joke(324, "Why did the garden rake apply for a desk job?", "It was tired of always being tied up outside."),
        Joke(325, "Why did the hallway get a compliment?", "It always knew how to make an entrance."),
        Joke(326, "Why did the kitchen timer become a motivational speaker?", "It really knew how to count down to success."),
        Joke(327, "Why did the path light get a promotion?", "It always showed initiative after dark."),
        Joke(328, "Why did the recipe collection get promoted?", "It always knew how to whip up a good decision."),
        Joke(329, "Why did the back door apply for a night shift?", "It liked working quietly after everyone left."),
        Joke(330, "Why did the bench cushion get promoted?", "It really knew how to sit well with everyone."),
        Joke(331, "Why did the toolbox latch propose?", "It wanted something to hold onto forever."),
        Joke(332, "Why did the porch chair get promoted?", "It really knew how to sit in on the big meetings."),
        Joke(333, "Why did the mailbox lid file a complaint?", "It felt like it was always getting talked over."),
        Joke(334, "Why did the wind chime start a band?", "It already had the whole orchestra hanging around."),
        Joke(335, "Why did the hallway rug get promoted?", "It really knew how to smooth things over."),
        Joke(336, "Why did the garden shed shelf apply for a raise?", "It felt like it was carrying the whole operation."),
        Joke(337, "Why did the door knocker get stage fright?", "It's always the one who has to open the show."),
        Joke(338, "Why did the kitchen apron enroll in culinary school?", "It wanted to cover all its bases."),
        Joke(339, "Why did the watering can get promoted?", "It really knew how to pour into its work."),
        Joke(340, "Why did the clothesline refuse to gossip?", "It didn't want to air out anyone's laundry."),
        Joke(341, "Why did the porch railing propose?", "It wanted something steady to hold onto."),
        Joke(342, "Why did the front yard tree run for mayor?", "It already had deep roots in the neighborhood."),
        Joke(343, "Why did the shed window apply for a job?", "It really knew how to bring things to light."),
        Joke(344, "Why did the coat closet get organized?", "It was tired of everyone jumping to conclusions about it."),
        Joke(345, "Why did the step mat file a complaint?", "It kept getting walked all over."),
        Joke(346, "Why did the fence post win an award?", "It really knew how to hold its ground."),
        Joke(347, "Why did the mailbox key go to therapy?", "It had trouble figuring out what it was really for."),
        Joke(348, "Why did the porch plant start a podcast?", "It really liked to branch out."),
        Joke(349, "Why did the light switch get promoted?", "It always knew how to turn things around."),
        Joke(350, "Why did the bird feeder win employee of the month?", "It always went above and beyond for the little guys."),
        Joke(351, "Why did the porch step get a raise?", "It carried a lot of weight around here."),
        Joke(352, "Why did the garden toolshed win an award?", "It really had all its tools in a row."),
        Joke(353, "Why did the kitchen towel apply for detective work?", "It always showed up right when things got messy."),
        Joke(354, "Why did the garden gate stay so calm?", "It never let anything get its hinges in a twist."),
        Joke(355, "Why did the porch lantern refuse to gossip?", "It preferred to keep things in a good light."),
        Joke(356, "Why did the kitchen chair get promoted?", "It always knew how to pull up to the big decisions."),
        Joke(357, "Why did the shed door go to therapy?", "It had trouble staying open about its feelings."),
        Joke(358, "Why did the morning kettle get a standing ovation?", "It always brought the house to a boil."),
        Joke(359, "Why did the gate latch get promoted?", "It really knew how to keep things locked down."),
        Joke(360, "What do you call a well-organized garden?", "A plot that's really got it together."),
    )
}
