package com.tyshi00.trinkets

// Real historical events, described in original wording, chosen deliberately
// to span Africa, Asia, the Americas, Europe, and Oceania rather than
// skewing toward any one region. See docs/CONTENT.md for how to keep
// growing this bucket toward full year-round coverage.
object TrinketsHistoryFacts {
    val ALL: List<HistoryFact> = listOf(
        HistoryFact(1, 1, 1, 1804, "Caribbean", "Haiti declared its independence from France, becoming the world's first nation founded by a successful slave revolt."),
        HistoryFact(2, 1, 1, 1959, "Caribbean", "Fidel Castro's forces entered Havana as the Cuban government of Fulgencio Batista collapsed."),
        HistoryFact(3, 1, 26, 1950, "Asia", "India adopted its constitution and became a republic, an event now marked annually as Republic Day."),
        HistoryFact(4, 2, 4, 1948, "Asia", "Sri Lanka (then Ceylon) gained independence from British colonial rule."),
        HistoryFact(5, 2, 11, 1990, "Africa", "Nelson Mandela was released from prison in South Africa after 27 years."),
        HistoryFact(6, 2, 15, 1898, "Caribbean", "The USS Maine exploded in Havana Harbor, an event that helped trigger the Spanish-American War."),
        HistoryFact(7, 3, 1, 1932, "North America", "The Empire State Building's radio tower was completed, though the building itself had opened months earlier."),
        HistoryFact(8, 3, 3, 1990, "Europe", "Namibia became fully independent from South African administration."),
        HistoryFact(9, 3, 6, 1957, "Africa", "Ghana became the first sub-Saharan African colony to gain independence from European colonial rule."),
        HistoryFact(10, 3, 8, 1917, "Europe", "Demonstrations in Petrograd (present-day St. Petersburg) marking International Women's Day helped ignite the February Revolution in Russia."),
        HistoryFact(11, 3, 11, 2011, "Asia", "A magnitude 9.0 earthquake and tsunami struck the Tohoku region of Japan, one of the most powerful earthquakes ever recorded."),
        HistoryFact(12, 3, 17, 1992, "Africa", "A whites-only referendum in South Africa approved ending apartheid-era rule."),
        HistoryFact(13, 3, 21, 1960, "Africa", "The Sharpeville massacre in South Africa became a turning point in the international movement against apartheid."),
        HistoryFact(14, 3, 21, 1990, "Africa", "Namibia's independence was formally celebrated, ending decades of South African administration."),
        HistoryFact(15, 3, 25, 1821, "Europe", "Greece began its war of independence from the Ottoman Empire, an anniversary still celebrated as Greek Independence Day."),
        HistoryFact(16, 3, 26, 1971, "Asia", "Bangladesh declared independence from Pakistan."),
        HistoryFact(17, 4, 4, 1968, "North America", "Civil rights leader Martin Luther King Jr. was assassinated in Memphis, Tennessee."),
        HistoryFact(18, 4, 6, 1994, "Africa", "A plane crash killing the presidents of Rwanda and Burundi helped trigger the Rwandan genocide."),
        HistoryFact(19, 4, 7, 1994, "Africa", "The Rwandan genocide began, ultimately claiming an estimated 800,000 lives over roughly 100 days."),
        HistoryFact(20, 4, 18, 1980, "Africa", "Zimbabwe gained formal independence, ending white minority rule in Rhodesia."),
        HistoryFact(21, 4, 27, 1994, "Africa", "South Africa held its first fully democratic election, with citizens of all races voting for the first time."),
        HistoryFact(22, 5, 5, 1862, "North America", "Mexican forces defeated the French army at the Battle of Puebla, the origin of the Cinco de Mayo holiday."),
        HistoryFact(23, 5, 8, 1945, "Europe", "Victory in Europe (V-E) Day marked the formal end of World War II fighting in Europe."),
        HistoryFact(24, 5, 14, 1948, "Middle East", "The State of Israel was declared, hours before the expiration of the British Mandate for Palestine."),
        HistoryFact(25, 5, 25, 1963, "Africa", "The Organisation of African Unity, a precursor to the African Union, was founded in Addis Ababa, Ethiopia."),
        HistoryFact(26, 5, 25, 2020, "North America", "The killing of George Floyd in Minneapolis sparked a wave of protests against police violence across the United States and around the world."),
        HistoryFact(27, 6, 4, 1989, "Asia", "Chinese authorities forcibly cleared Tiananmen Square in Beijing, ending weeks of pro-democracy demonstrations."),
        HistoryFact(28, 6, 5, 1967, "Middle East", "The Six-Day War began between Israel and a coalition of Arab states."),
        HistoryFact(29, 6, 16, 1976, "Africa", "Students in Soweto, South Africa, marched to protest a policy requiring instruction in Afrikaans, a turning point in the anti-apartheid struggle."),
        HistoryFact(30, 6, 20, 1837, "Europe", "Victoria became Queen of the United Kingdom at the age of 18, beginning a 63-year reign."),
        HistoryFact(31, 6, 26, 1945, "North America", "Delegates from 50 countries signed the United Nations Charter in San Francisco."),
        HistoryFact(32, 7, 1, 1867, "North America", "The British North America Act took effect, creating the Dominion of Canada."),
        HistoryFact(33, 7, 4, 1776, "North America", "The United States formally adopted the Declaration of Independence."),
        HistoryFact(34, 7, 5, 1962, "Africa", "Algeria gained independence from France after an eight-year war."),
        HistoryFact(35, 7, 6, 1885, "Europe", "French chemist Louis Pasteur successfully tested his rabies vaccine on a human patient for the first time."),
        HistoryFact(36, 7, 9, 1816, "South America", "Argentina declared its independence from Spain."),
        HistoryFact(37, 7, 14, 1789, "Europe", "Parisians stormed the Bastille fortress, a flashpoint that helped ignite the French Revolution."),
        HistoryFact(38, 7, 20, 1969, "Global", "Apollo 11 astronauts Neil Armstrong and Buzz Aldrin became the first humans to walk on the Moon."),
        HistoryFact(39, 7, 26, 1953, "Caribbean", "A rebel attack on the Moncada Barracks in Cuba, led by Fidel Castro, is commemorated as the start of the Cuban Revolution."),
        HistoryFact(40, 8, 6, 1945, "Asia", "The United States dropped an atomic bomb on Hiroshima, Japan, during the closing days of World War II."),
        HistoryFact(41, 8, 9, 1965, "Asia", "Singapore became an independent nation after separating from Malaysia."),
        HistoryFact(42, 8, 14, 1947, "Asia", "Pakistan gained independence from British colonial rule."),
        HistoryFact(43, 8, 15, 1947, "Asia", "India gained independence from British colonial rule after nearly two centuries."),
        HistoryFact(44, 8, 17, 1945, "Asia", "Indonesia proclaimed its independence from Dutch colonial rule."),
        HistoryFact(45, 8, 24, 79, "Europe", "Mount Vesuvius erupted, burying the Roman city of Pompeii in volcanic ash."),
        HistoryFact(46, 9, 2, 1945, "Asia", "Japan formally surrendered aboard the USS Missouri, marking the end of World War II."),
        HistoryFact(47, 9, 7, 1822, "South America", "Brazil declared its independence from Portugal."),
        HistoryFact(48, 9, 15, 1821, "Central America", "Costa Rica, El Salvador, Guatemala, Honduras, and Nicaragua jointly declared independence from Spain."),
        HistoryFact(49, 9, 16, 1810, "North America", "Mexico's independence movement began with the Grito de Dolores, a call to arms against Spanish rule."),
        HistoryFact(50, 9, 16, 1975, "Africa", "Papua New Guinea gained independence from Australian administration."),
        HistoryFact(51, 9, 21, 1964, "Africa", "Malta gained independence from the United Kingdom."),
        HistoryFact(52, 9, 24, 1960, "Africa", "Guinea-Bissau's independence movement gained global attention as African decolonization accelerated across the continent."),
        HistoryFact(53, 10, 1, 1949, "Asia", "The People's Republic of China was formally proclaimed in Beijing."),
        HistoryFact(54, 10, 1, 1960, "Africa", "Nigeria gained independence from British colonial rule, becoming Africa's most populous nation."),
        HistoryFact(55, 10, 2, 1869, "Asia", "Mohandas Gandhi, who would go on to lead India's independence movement through nonviolent resistance, was born in Porbandar."),
        HistoryFact(56, 10, 9, 2006, "Asia", "North Korea conducted its first announced nuclear weapons test."),
        HistoryFact(57, 10, 24, 1945, "Global", "The United Nations officially came into existence after its charter was ratified by the required number of countries."),
        HistoryFact(58, 11, 9, 1989, "Europe", "The Berlin Wall fell, as East German authorities opened checkpoints after weeks of mass protests."),
        HistoryFact(59, 11, 11, 1975, "Africa", "Angola declared independence from Portugal after a long colonial war."),
        HistoryFact(60, 11, 18, 1918, "Europe", "Latvia declared its independence amid the collapse of the Russian and German empires at the end of World War I."),
        HistoryFact(61, 11, 28, 1912, "Europe", "Albania declared independence from the Ottoman Empire."),
        HistoryFact(62, 12, 1, 1955, "North America", "Rosa Parks refused to give up her bus seat in Montgomery, Alabama, helping spark the modern American civil rights movement."),
        HistoryFact(63, 12, 2, 1971, "Middle East", "The United Arab Emirates was formed through the union of several small emirates."),
        HistoryFact(64, 12, 10, 1948, "Global", "The United Nations General Assembly adopted the Universal Declaration of Human Rights."),
        HistoryFact(65, 12, 16, 1971, "Asia", "The Bangladesh Liberation War ended with the surrender of Pakistani forces, securing Bangladeshi independence."),
        HistoryFact(66, 12, 25, 1991, "Europe", "Mikhail Gorbachev resigned as president of the Soviet Union, which formally dissolved the following day."),
        HistoryFact(67, 1, 15, 1929, "North America", "Civil rights leader Martin Luther King Jr. was born in Atlanta, Georgia."),
        HistoryFact(68, 1, 20, 1961, "North America", "John F. Kennedy was inaugurated as the 35th President of the United States."),
        HistoryFact(69, 1, 28, 1986, "North America", "The Space Shuttle Challenger broke apart shortly after launch, killing all seven crew members."),
        HistoryFact(70, 2, 4, 2004, "North America", "Facebook, which would grow into one of the world's largest social media platforms, was launched from a Harvard dormitory."),
        HistoryFact(71, 2, 20, 1962, "North America", "John Glenn became the first American to orbit the Earth."),
        HistoryFact(72, 2, 24, 1582, "Europe", "Pope Gregory XIII introduced the Gregorian calendar, now the most widely used civil calendar in the world."),
        HistoryFact(73, 3, 10, 1876, "North America", "Alexander Graham Bell made the first successful telephone call, famously summoning his assistant."),
        HistoryFact(74, 3, 14, 1879, "Europe", "Physicist Albert Einstein, whose work would transform modern physics, was born in Ulm, Germany."),
        HistoryFact(75, 3, 30, 1867, "North America", "The United States agreed to purchase Alaska from Russia."),
        HistoryFact(76, 4, 12, 1961, "Asia", "Soviet cosmonaut Yuri Gagarin became the first human to travel into space."),
        HistoryFact(77, 4, 22, 1970, "Global", "The first Earth Day was observed, helping launch the modern environmental movement."),
        HistoryFact(78, 5, 1, 1931, "North America", "The Empire State Building officially opened in New York City."),
        HistoryFact(79, 5, 29, 1953, "Asia", "Tenzing Norgay of Nepal and Edmund Hillary of New Zealand became the first climbers confirmed to reach the summit of Mount Everest."),
        HistoryFact(80, 6, 12, 1964, "Africa", "Nelson Mandela was sentenced to life imprisonment in South Africa for his role opposing apartheid."),
        HistoryFact(81, 6, 15, 1215, "Europe", "England's King John sealed the Magna Carta, an early milestone in limiting royal power under law."),
        HistoryFact(82, 7, 2, 1937, "Oceania", "Aviator Amelia Earhart disappeared over the Pacific Ocean during an attempt to fly around the world."),
        HistoryFact(83, 8, 28, 1963, "North America", "Martin Luther King Jr. delivered his 'I Have a Dream' speech during the March on Washington."),
        HistoryFact(84, 9, 26, 1983, "Europe", "A Soviet early-warning system falsely signaled an incoming nuclear attack; officer Stanislav Petrov's judgment that it was a false alarm is widely credited with averting catastrophe."),
        HistoryFact(85, 10, 14, 1947, "North America", "Test pilot Chuck Yeager became the first person confirmed to fly faster than the speed of sound."),
        HistoryFact(86, 11, 20, 1945, "Europe", "The Nuremberg trials began, prosecuting senior Nazi officials for war crimes after World War II."),
        HistoryFact(87, 12, 17, 1903, "North America", "Orville and Wilbur Wright achieved the first sustained, controlled flight of a powered aircraft near Kitty Hawk, North Carolina."),
        HistoryFact(88, 1, 3, 1959, "North America", "Alaska was admitted as the 49th U.S. state."),
        HistoryFact(89, 1, 27, 1945, "Europe", "Soviet troops liberated the Auschwitz concentration camp, an event now marked internationally as Holocaust Remembrance Day."),
        HistoryFact(90, 2, 21, 1965, "North America", "Civil rights activist Malcolm X was assassinated in New York City."),
        HistoryFact(91, 3, 15, 44, "Europe", "Roman dictator Julius Caesar was assassinated by a group of senators."),
        HistoryFact(92, 4, 9, 1865, "North America", "Confederate General Robert E. Lee surrendered to Union General Ulysses S. Grant, effectively ending the American Civil War."),
        HistoryFact(93, 5, 8, 1886, "North America", "Pharmacist John Pemberton first sold his new soft drink, Coca-Cola, in Atlanta, Georgia."),
        HistoryFact(94, 6, 28, 1914, "Europe", "The assassination of Archduke Franz Ferdinand in Sarajevo set off the chain of events leading to World War I."),
        HistoryFact(95, 8, 1, 1834, "Caribbean", "Slavery was formally abolished across the British Empire, freeing enslaved people across the Caribbean and elsewhere."),
        HistoryFact(96, 9, 8, 1966, "North America", "The television series Star Trek premiered, later becoming a defining piece of science fiction culture."),
        HistoryFact(97, 10, 12, 1492, "Caribbean", "Christopher Columbus's expedition reached land in the Caribbean, a voyage that opened an era of European contact with the Americas."),
        HistoryFact(98, 11, 22, 1963, "North America", "U.S. President John F. Kennedy was assassinated in Dallas, Texas."),
        HistoryFact(99, 12, 7, 1941, "Asia", "Japanese forces attacked the U.S. naval base at Pearl Harbor, Hawaii, drawing the United States into World War II."),
        HistoryFact(100, 12, 21, 1988, "Europe", "A bomb destroyed Pan Am Flight 103 over Lockerbie, Scotland, killing everyone aboard and several people on the ground."),
        HistoryFact(101, 2, 6, 1952, "Europe", "Elizabeth II became Queen of the United Kingdom upon the death of her father, King George VI."),
        HistoryFact(102, 3, 12, 1930, "Asia", "Mohandas Gandhi began the Salt March, a 240-mile protest walk against British salt taxes in colonial India."),
        HistoryFact(103, 4, 26, 1986, "Europe", "A reactor at the Chernobyl Nuclear Power Plant in Soviet Ukraine exploded, causing the worst nuclear accident in history."),
        HistoryFact(104, 5, 18, 1980, "Asia", "China conducted its first successful test launch of an intercontinental ballistic missile into the Pacific Ocean."),
        HistoryFact(105, 6, 6, 1944, "Europe", "Allied forces landed on the beaches of Normandy, France, in the D-Day invasion of World War II."),
        HistoryFact(106, 7, 17, 1955, "North America", "Disneyland opened to the public in Anaheim, California."),
        HistoryFact(107, 8, 12, 30, "Africa", "Cleopatra, the last active ruler of the Ptolemaic Kingdom of Egypt, is traditionally said to have died around this time, ending the Hellenistic period in Egypt."),
        HistoryFact(108, 9, 11, 2001, "North America", "Coordinated terrorist attacks destroyed the World Trade Center towers in New York City and struck the Pentagon."),
        HistoryFact(109, 10, 3, 1990, "Europe", "East and West Germany formally reunified into a single nation after decades of Cold War division."),
        HistoryFact(110, 11, 4, 2008, "North America", "Barack Obama was elected as the first African American president of the United States."),
        HistoryFact(111, 12, 26, 2004, "Asia", "A massive earthquake off Sumatra, Indonesia, triggered a tsunami across the Indian Ocean that killed roughly 230,000 people in over a dozen countries."),
        HistoryFact(112, 1, 8, 1935, "North America", "Musician Elvis Presley, who would help popularize rock and roll worldwide, was born in Tupelo, Mississippi."),
        HistoryFact(113, 2, 27, 1991, "Middle East", "The Gulf War ended after coalition forces liberated Kuwait from Iraqi occupation."),
        HistoryFact(114, 3, 23, 1956, "Asia", "Pakistan became an Islamic republic, adopting its first constitution."),
        HistoryFact(115, 4, 14, 1912, "Global", "The RMS Titanic struck an iceberg in the North Atlantic and sank in the early hours of the following day."),
        HistoryFact(116, 5, 6, 1954, "Europe", "British runner Roger Bannister became the first person recorded to run a mile in under four minutes."),
        HistoryFact(117, 6, 23, 1868, "North America", "Christopher Latham Sholes patented an early practical version of the typewriter."),
        HistoryFact(118, 7, 27, 1953, "Asia", "An armistice ended active fighting in the Korean War, though a formal peace treaty was never signed."),
        HistoryFact(119, 8, 19, 1839, "Europe", "The French government publicly announced the daguerreotype photographic process, making it freely available to the world."),
        HistoryFact(120, 9, 25, 1980, "Middle East", "Iraq launched a full invasion of Iran, beginning the eight-year Iran-Iraq War."),
        HistoryFact(121, 1, 2, 1959, "Global", "The Soviet Union launched Luna 1, the first spacecraft to leave Earth's orbit."),
        HistoryFact(122, 1, 6, 1912, "Europe", "Alfred Wegener first proposed his theory of continental drift in a public lecture."),
        HistoryFact(123, 1, 9, 1972, "Asia", "The RMS Queen Elizabeth ocean liner was destroyed by fire in Hong Kong harbor."),
        HistoryFact(124, 1, 12, 1866, "Europe", "The Royal Aeronautical Society was founded in London, one of the world's first aviation organizations."),
        HistoryFact(125, 1, 16, 1920, "Global", "The League of Nations, a precursor to the United Nations, held its first council meeting in Paris."),
        HistoryFact(126, 1, 18, 1871, "Europe", "The German Empire was proclaimed at the Palace of Versailles, unifying a collection of German states."),
        HistoryFact(127, 1, 20, 1887, "North America", "The United States Senate approved an agreement to lease Pearl Harbor in Hawaii as a naval base."),
        HistoryFact(128, 1, 23, 1556, "Asia", "The Shaanxi earthquake struck China, remaining the deadliest earthquake in recorded history."),
        HistoryFact(129, 1, 25, 1959, "North America", "American Airlines Flight 1 introduced commercial jet service between New York and Los Angeles."),
        HistoryFact(130, 1, 31, 1958, "North America", "The United States launched Explorer 1, its first satellite, into orbit."),
        HistoryFact(131, 2, 1, 1979, "Middle East", "Ayatollah Ruhollah Khomeini returned to Iran after years in exile, a pivotal moment in the Iranian Revolution."),
        HistoryFact(132, 2, 3, 1959, "North America", "Musicians Buddy Holly, Ritchie Valens, and The Big Bopper died in a plane crash, later remembered as The Day the Music Died."),
        HistoryFact(133, 2, 7, 1974, "Caribbean", "Grenada gained independence from the United Kingdom."),
        HistoryFact(134, 2, 9, 1964, "North America", "The Beatles made their first live American television appearance on The Ed Sullivan Show."),
        HistoryFact(135, 2, 10, 1996, "Global", "IBM's Deep Blue computer defeated world chess champion Garry Kasparov in a single game for the first time under standard rules."),
        HistoryFact(136, 2, 12, 1809, "North America", "Abraham Lincoln, who would later serve as the 16th U.S. President, was born in Kentucky."),
        HistoryFact(137, 2, 18, 1930, "North America", "Astronomer Clyde Tombaugh discovered Pluto at the Lowell Observatory in Arizona."),
        HistoryFact(138, 2, 21, 1848, "Europe", "Karl Marx and Friedrich Engels published The Communist Manifesto."),
        HistoryFact(139, 2, 22, 1979, "Caribbean", "Saint Lucia gained independence from the United Kingdom."),
        HistoryFact(140, 2, 25, 1986, "Asia", "The People Power Revolution in the Philippines forced President Ferdinand Marcos from office."),
        HistoryFact(141, 3, 2, 1969, "Europe", "The first Concorde supersonic passenger jet completed its maiden test flight in France."),
        HistoryFact(142, 3, 4, 1789, "North America", "The United States Constitution officially took effect."),
        HistoryFact(143, 3, 9, 1959, "North America", "The Barbie doll debuted at the American International Toy Fair in New York."),
        HistoryFact(144, 3, 12, 1912, "North America", "The Girl Scouts of the USA was founded in Savannah, Georgia."),
        HistoryFact(145, 3, 13, 1930, "Global", "The discovery of Pluto was formally announced to the public."),
        HistoryFact(146, 3, 15, 1990, "Europe", "Mikhail Gorbachev was elected the first and only President of the Soviet Union by its Congress of People's Deputies."),
        HistoryFact(147, 3, 16, 1968, "Asia", "American soldiers killed hundreds of unarmed villagers in the My Lai massacre during the Vietnam War."),
        HistoryFact(148, 3, 20, 1815, "Europe", "Napoleon Bonaparte returned to Paris, beginning the period known as the Hundred Days after his escape from exile."),
        HistoryFact(149, 3, 23, 1919, "Europe", "Benito Mussolini founded the Fascist movement in Italy."),
        HistoryFact(150, 3, 29, 1973, "Asia", "The last United States combat troops departed Vietnam, formally ending direct American military involvement."),
        HistoryFact(151, 4, 1, 1976, "North America", "Apple Computer was founded by Steve Jobs, Steve Wozniak, and Ronald Wayne in California."),
        HistoryFact(152, 4, 3, 1948, "Global", "The Marshall Plan was enacted, providing U.S. economic assistance to help rebuild Western Europe after World War II."),
        HistoryFact(153, 4, 6, 1896, "Europe", "The first modern Olympic Games opened in Athens, Greece."),
        HistoryFact(154, 4, 12, 1955, "North America", "The polio vaccine developed by Jonas Salk was declared safe and effective."),
        HistoryFact(155, 4, 15, 1912, "Global", "The RMS Titanic sank in the early hours of this date after striking an iceberg the night before."),
        HistoryFact(156, 4, 19, 1775, "North America", "Fighting broke out at Lexington and Concord, marking the start of the American Revolutionary War."),
        HistoryFact(157, 4, 21, 753, "Europe", "According to tradition, the city of Rome was founded on this date."),
        HistoryFact(158, 4, 23, 1616, "Europe", "William Shakespeare, one of the most influential writers in the English language, died in Stratford-upon-Avon."),
        HistoryFact(159, 4, 26, 1964, "Africa", "Tanganyika and Zanzibar merged to form the United Republic of Tanzania."),
        HistoryFact(160, 4, 29, 1992, "North America", "Riots broke out in Los Angeles following the acquittal of police officers in the beating of Rodney King."),
        HistoryFact(161, 5, 1, 1886, "North America", "Labor demonstrations across the United States, centered in Chicago, helped establish the origins of May Day as a workers' holiday."),
        HistoryFact(162, 5, 6, 1937, "North America", "The airship Hindenburg caught fire and was destroyed while attempting to dock in New Jersey."),
        HistoryFact(163, 5, 9, 1950, "Europe", "French foreign minister Robert Schuman proposed the plan that would evolve into the European Union."),
        HistoryFact(164, 5, 12, 1949, "Europe", "The Soviet Union lifted its blockade of West Berlin, ending a crisis that had lasted nearly a year."),
        HistoryFact(165, 5, 15, 1948, "Middle East", "War broke out between Israel and neighboring Arab states the day after Israel's declaration of independence."),
        HistoryFact(166, 5, 21, 1980, "Africa", "South African anti-apartheid activists faced increasing international sanctions as global protests intensified."),
        HistoryFact(167, 5, 24, 1844, "North America", "Samuel Morse sent the first long distance telegraph message, reading What hath God wrought."),
        HistoryFact(168, 5, 30, 1431, "Europe", "Joan of Arc was executed in Rouen, France."),
        HistoryFact(169, 6, 1, 1980, "North America", "The Cable News Network, CNN, launched as the first 24 hour television news channel."),
        HistoryFact(170, 6, 3, 1965, "North America", "Astronaut Ed White performed the first American spacewalk during the Gemini 4 mission."),
        HistoryFact(171, 6, 8, 632, "Middle East", "The Prophet Muhammad died in Medina, in present day Saudi Arabia."),
        HistoryFact(172, 6, 10, 1940, "Europe", "Italy declared war on France and the United Kingdom, entering World War II."),
        HistoryFact(173, 6, 13, 1966, "North America", "The United States Supreme Court decided Miranda v. Arizona, establishing the requirement to inform suspects of their legal rights."),
        HistoryFact(174, 6, 17, 1885, "North America", "The Statue of Liberty arrived in New York Harbor aboard a French ship."),
        HistoryFact(175, 6, 19, 1865, "North America", "Enslaved people in Texas learned of their freedom, an event now commemorated as Juneteenth."),
        HistoryFact(176, 6, 21, 1989, "North America", "The United States Supreme Court ruled that burning the American flag was a form of protected free speech."),
        HistoryFact(177, 6, 23, 1912, "North America", "Delegates opened the Progressive Party convention in Chicago, backing Theodore Roosevelt for a return to the presidency."),
        HistoryFact(178, 6, 27, 1950, "Global", "The United Nations Security Council voted to send military assistance to South Korea following the outbreak of the Korean War."),
        HistoryFact(179, 6, 30, 1908, "Asia", "A massive explosion, later called the Tunguska event, flattened an enormous area of Siberian forest."),
        HistoryFact(180, 7, 1, 1997, "Asia", "The United Kingdom transferred sovereignty of Hong Kong back to China."),
        HistoryFact(181, 7, 3, 1988, "Middle East", "A United States Navy warship mistakenly shot down an Iranian passenger jet, killing everyone aboard."),
        HistoryFact(182, 7, 6, 1957, "Europe", "Althea Gibson became the first Black athlete to win the Wimbledon tennis championship."),
        HistoryFact(183, 7, 8, 1889, "North America", "The Wall Street Journal published its first issue."),
        HistoryFact(184, 7, 11, 1804, "North America", "U.S. Vice President Aaron Burr fatally wounded former Treasury Secretary Alexander Hamilton in a duel."),
        HistoryFact(185, 7, 13, 1930, "South America", "The first FIFA World Cup began in Uruguay."),
        HistoryFact(186, 7, 15, 1965, "North America", "The Mariner 4 spacecraft transmitted the first close up images of Mars back to Earth."),
        HistoryFact(187, 7, 16, 1945, "North America", "The United States conducted the first successful test of a nuclear weapon in the New Mexico desert."),
        HistoryFact(188, 7, 18, 1976, "Global", "Romanian gymnast Nadia Comaneci scored the first perfect ten in Olympic gymnastics history at the Montreal Games."),
        HistoryFact(189, 7, 19, 1900, "Europe", "The first line of the Paris Metro opened to the public."),
        HistoryFact(190, 7, 21, 1925, "North America", "The Scopes Monkey Trial concluded in Tennessee, a landmark case concerning the teaching of evolution in public schools."),
        HistoryFact(191, 7, 23, 1962, "Global", "The Telstar satellite relayed the first live transatlantic television broadcast."),
        HistoryFact(192, 7, 24, 1911, "South America", "American explorer Hiram Bingham rediscovered the Inca site of Machu Picchu in Peru."),
        HistoryFact(193, 7, 27, 1866, "Global", "The first successful permanent transatlantic telegraph cable was completed."),
        HistoryFact(194, 7, 29, 1958, "North America", "The United States created NASA, its national space agency."),
        HistoryFact(195, 7, 30, 1930, "South America", "Uruguay defeated Argentina to win the first FIFA World Cup final."),
        HistoryFact(196, 8, 3, 1492, "Europe", "Christopher Columbus departed Spain on the voyage that would lead to European contact with the Americas."),
        HistoryFact(197, 8, 4, 1944, "Europe", "Diarist Anne Frank and her family were arrested by German forces after hiding for over two years in Amsterdam."),
        HistoryFact(198, 8, 5, 1962, "North America", "Actress Marilyn Monroe was found dead at her home in Los Angeles."),
        HistoryFact(199, 8, 6, 1926, "North America", "American swimmer Gertrude Ederle became the first woman to swim across the English Channel."),
        HistoryFact(200, 8, 8, 1963, "Europe", "A gang carried out the Great Train Robbery in England, stealing a then record sum from a Royal Mail train."),
        HistoryFact(201, 8, 10, 1809, "South America", "Ecuador declared its intention to seek independence from Spanish colonial rule, an early spark in the region's independence movement."),
        HistoryFact(202, 8, 13, 1961, "Europe", "East German authorities began construction of the Berlin Wall."),
        HistoryFact(203, 8, 16, 1977, "North America", "Musician Elvis Presley died at his home in Memphis, Tennessee."),
        HistoryFact(204, 8, 18, 1920, "North America", "The 19th Amendment to the U.S. Constitution was ratified, granting many American women the right to vote."),
        HistoryFact(205, 8, 20, 1988, "Middle East", "A ceasefire took effect ending active combat in the Iran-Iraq War."),
        HistoryFact(206, 8, 21, 1959, "North America", "Hawaii was admitted as the 50th U.S. state."),
        HistoryFact(207, 8, 23, 1989, "Europe", "Roughly two million people joined hands across Estonia, Latvia, and Lithuania in a peaceful protest known as the Baltic Way."),
        HistoryFact(208, 8, 27, 1883, "Asia", "The volcano Krakatoa erupted catastrophically in present day Indonesia, producing one of the loudest sounds in recorded history."),
        HistoryFact(209, 8, 29, 2005, "North America", "Hurricane Katrina made landfall on the U.S. Gulf Coast, causing catastrophic flooding in New Orleans."),
        HistoryFact(210, 8, 31, 1957, "Asia", "Malaysia, then known as Malaya, gained independence from British colonial rule."),
        HistoryFact(211, 9, 1, 1939, "Europe", "Germany invaded Poland, an event widely regarded as the beginning of World War II in Europe."),
        HistoryFact(212, 9, 3, 1783, "North America", "The Treaty of Paris was signed, formally ending the American Revolutionary War."),
        HistoryFact(213, 9, 6, 1997, "Europe", "The funeral of Diana, Princess of Wales, was held in London, watched by an estimated worldwide audience of over two billion people."),
        HistoryFact(214, 9, 12, 1977, "Africa", "South African anti-apartheid activist Steve Biko died in police custody, drawing global condemnation."),
        HistoryFact(215, 9, 17, 1978, "Middle East", "Israel and Egypt signed the Camp David Accords, a framework for peace between the two nations."),
        HistoryFact(216, 9, 18, 1931, "Asia", "Japanese forces staged an incident in Manchuria that led to the invasion and occupation of the region."),
        HistoryFact(217, 9, 19, 1893, "Oceania", "New Zealand became the first self governing country in the world to grant women the right to vote."),
        HistoryFact(218, 9, 20, 1519, "Europe", "Portuguese explorer Ferdinand Magellan set sail on the expedition that would achieve the first circumnavigation of the globe."),
        HistoryFact(219, 9, 22, 1862, "North America", "U.S. President Abraham Lincoln issued the preliminary Emancipation Proclamation."),
        HistoryFact(220, 9, 23, 1846, "Europe", "Astronomers first observed the planet Neptune, confirming its existence based on mathematical predictions."),
        HistoryFact(221, 9, 27, 1996, "Asia", "The Taliban captured Kabul, Afghanistan, and established control over most of the country."),
        HistoryFact(222, 9, 28, 1928, "Europe", "Scottish scientist Alexander Fleming discovered penicillin, the world's first widely used antibiotic."),
        HistoryFact(223, 9, 29, 1954, "Europe", "CERN, the European Organization for Nuclear Research, was founded near Geneva, Switzerland."),
        HistoryFact(224, 9, 30, 1938, "Europe", "Britain, France, Germany, and Italy signed the Munich Agreement, allowing German annexation of part of Czechoslovakia."),
        HistoryFact(225, 10, 4, 1957, "Asia", "The Soviet Union launched Sputnik 1, the first artificial satellite, beginning the Space Age."),
        HistoryFact(226, 10, 5, 1962, "Europe", "The first James Bond film, Dr. No, premiered in London."),
        HistoryFact(227, 10, 6, 1973, "Middle East", "Egypt and Syria launched a coordinated surprise attack on Israel, beginning the Yom Kippur War."),
        HistoryFact(228, 10, 7, 2001, "Asia", "The United States and allied forces began a military campaign in Afghanistan following the September 11 attacks."),
        HistoryFact(229, 10, 9, 1967, "South America", "Revolutionary leader Che Guevara was captured and executed in Bolivia."),
        HistoryFact(230, 10, 11, 1968, "North America", "NASA launched Apollo 7, the first crewed mission in the Apollo program."),
        HistoryFact(231, 10, 15, 1783, "Europe", "The first untethered hot air balloon flight carrying a human took place in Paris."),
        HistoryFact(232, 10, 18, 1867, "North America", "The United States formally took possession of Alaska after purchasing it from Russia."),
        HistoryFact(233, 10, 21, 1805, "Europe", "The Royal Navy defeated a combined French and Spanish fleet at the Battle of Trafalgar."),
        HistoryFact(234, 10, 23, 1956, "Europe", "A popular uprising against Soviet controlled government began in Hungary."),
        HistoryFact(235, 10, 25, 1971, "Asia", "The United Nations General Assembly voted to recognize the People's Republic of China and transfer China's seat from Taiwan."),
        HistoryFact(236, 10, 29, 1929, "North America", "The New York Stock Exchange crashed on a day known as Black Tuesday, helping trigger the Great Depression."),
        HistoryFact(237, 10, 31, 1517, "Europe", "Martin Luther is traditionally said to have posted his Ninety Five Theses, a spark for the Protestant Reformation."),
        HistoryFact(238, 11, 2, 1917, "Middle East", "The British government issued the Balfour Declaration, expressing support for a Jewish homeland in Palestine."),
        HistoryFact(239, 11, 6, 1917, "Europe", "Bolshevik forces seized power in Petrograd, a key event of the Russian Revolution."),
        HistoryFact(240, 11, 8, 1519, "North America", "Spanish conquistador Hernan Cortes and Aztec ruler Moctezuma II first met near present day Mexico City."),
        HistoryFact(241, 11, 9, 1938, "Europe", "Coordinated attacks on Jewish communities across Germany and Austria, known as Kristallnacht, marked an escalation of Nazi persecution."),
        HistoryFact(242, 11, 10, 1983, "North America", "Microsoft founder Bill Gates announced the Windows operating system to the public for the first time."),
        HistoryFact(243, 11, 13, 1927, "North America", "The Holland Tunnel opened, connecting New York and New Jersey beneath the Hudson River."),
        HistoryFact(244, 11, 15, 1889, "South America", "Brazil became a republic after a military coup ended the monarchy."),
        HistoryFact(245, 11, 16, 1945, "Global", "UNESCO, the United Nations agency for education, science, and culture, was founded."),
        HistoryFact(246, 11, 19, 1863, "North America", "U.S. President Abraham Lincoln delivered the Gettysburg Address."),
        HistoryFact(247, 11, 21, 1877, "North America", "Inventor Thomas Edison announced his invention of the phonograph, an early device for recording and playing sound."),
        HistoryFact(248, 11, 25, 1963, "North America", "U.S. President John F. Kennedy was laid to rest at Arlington National Cemetery following his assassination three days earlier."),
        HistoryFact(249, 11, 29, 1947, "Middle East", "The United Nations General Assembly voted to adopt a plan to partition British controlled Palestine into separate Jewish and Arab states."),
        HistoryFact(250, 11, 30, 1782, "North America", "The United States and Great Britain signed preliminary peace terms in Paris, effectively ending the American Revolutionary War."),
        HistoryFact(251, 12, 1, 1918, "Europe", "Transylvania united with the Kingdom of Romania, an event still celebrated as Great Union Day."),
        HistoryFact(252, 12, 3, 1967, "Africa", "South African surgeon Christiaan Barnard performed the world's first human to human heart transplant."),
        HistoryFact(253, 12, 4, 1791, "Europe", "The Observer newspaper published its first edition in London, becoming the world's oldest Sunday newspaper still in publication."),
        HistoryFact(254, 12, 5, 1955, "North America", "The Montgomery Bus Boycott began in Alabama, days after Rosa Parks's arrest."),
        HistoryFact(255, 12, 6, 1917, "North America", "A massive explosion caused by a ship collision devastated the harbor city of Halifax, Canada."),
        HistoryFact(256, 12, 8, 1980, "North America", "Musician John Lennon was shot and killed outside his New York City apartment."),
        HistoryFact(257, 12, 9, 1961, "Africa", "Tanganyika, later part of Tanzania, gained independence from British colonial rule."),
        HistoryFact(258, 12, 11, 1936, "Europe", "King Edward VIII of the United Kingdom abdicated the throne to marry Wallis Simpson."),
        HistoryFact(259, 12, 13, 1937, "Asia", "Japanese forces captured Nanjing, China, beginning a period of mass violence against civilians known as the Nanjing Massacre."),
        HistoryFact(260, 12, 14, 1911, "Global", "Norwegian explorer Roald Amundsen's expedition became the first to reach the South Pole."),
        HistoryFact(261, 12, 15, 1791, "North America", "The U.S. Bill of Rights was ratified, adding the first ten amendments to the Constitution."),
        HistoryFact(262, 12, 17, 1989, "South America", "Fernando Collor de Mello won Brazil's first direct presidential election in nearly three decades."),
        HistoryFact(263, 12, 18, 1865, "North America", "The 13th Amendment to the U.S. Constitution was ratified, formally abolishing slavery."),
        HistoryFact(264, 12, 19, 1998, "North America", "The U.S. House of Representatives voted to impeach President Bill Clinton."),
        HistoryFact(265, 12, 22, 1989, "Europe", "The Brandenburg Gate reopened in Berlin, symbolizing the end of the city's Cold War division."),
        HistoryFact(266, 12, 23, 1888, "Europe", "Artist Vincent van Gogh injured his own ear during a period of personal crisis in Arles, France."),
        HistoryFact(267, 12, 24, 1968, "Global", "The crew of Apollo 8 became the first humans to orbit the Moon, and took the famous Earthrise photograph."),
        HistoryFact(268, 12, 27, 1949, "Asia", "The Netherlands formally transferred sovereignty of Indonesia, ending centuries of Dutch colonial rule."),
        HistoryFact(269, 12, 29, 1170, "Europe", "Archbishop Thomas Becket was murdered inside Canterbury Cathedral in England."),
        HistoryFact(270, 12, 30, 1922, "Europe", "The Union of Soviet Socialist Republics was formally established."),
        HistoryFact(271, 1, 5, 1919, "Europe", "The German Workers' Party, which would later become the Nazi Party, was founded in Munich."),
        HistoryFact(272, 1, 7, 1610, "Europe", "Galileo Galilei observed the four largest moons of Jupiter for the first time through his telescope."),
        HistoryFact(273, 1, 11, 1922, "North America", "Insulin was successfully used to treat a human diabetes patient for the first time, in Toronto, Canada."),
        HistoryFact(274, 1, 13, 1990, "North America", "Douglas Wilder was inaugurated as Virginia's governor, becoming the first elected African American governor in U.S. history."),
        HistoryFact(275, 1, 14, 1943, "Africa", "Allied leaders met in Casablanca, Morocco, to plan strategy for the remainder of World War II."),
        HistoryFact(276, 1, 17, 1991, "Middle East", "A U.S. led coalition began a military campaign to expel Iraqi forces from Kuwait, opening the Gulf War."),
        HistoryFact(277, 1, 19, 1983, "Europe", "The Apple Lisa, one of the first personal computers with a graphical user interface, was announced."),
        HistoryFact(278, 1, 21, 1976, "Europe", "The Concorde began the world's first commercial supersonic passenger flights."),
        HistoryFact(279, 1, 22, 1901, "Europe", "Queen Victoria of the United Kingdom died after a reign of 63 years, one of the longest in British history."),
        HistoryFact(280, 1, 24, 41, "Europe", "Roman Emperor Caligula was assassinated by members of his own guard."),
        HistoryFact(281, 1, 27, 1888, "North America", "The National Geographic Society was founded in Washington, D.C."),
        HistoryFact(282, 1, 29, 1845, "North America", "Edgar Allan Poe's poem The Raven was first published in a New York newspaper."),
        HistoryFact(283, 1, 30, 1948, "Asia", "Indian independence leader Mohandas Gandhi was assassinated in New Delhi."),
        HistoryFact(284, 2, 3, 1966, "Global", "The Soviet spacecraft Luna 9 achieved the first successful soft landing on the Moon."),
        HistoryFact(285, 2, 5, 1970, "Africa", "The first modern census in independent Nigeria helped shape the country's early political structure."),
        HistoryFact(286, 2, 9, 1895, "North America", "William Morgan invented the game of volleyball in Massachusetts."),
        HistoryFact(287, 2, 12, 1912, "Asia", "The last Qing emperor of China abdicated, ending over two thousand years of imperial rule."),
        HistoryFact(288, 2, 14, 1929, "North America", "Seven men were killed in Chicago in the gang related killings known as the Saint Valentine's Day Massacre."),
        HistoryFact(289, 2, 15, 1965, "North America", "Canada officially adopted its current national flag, featuring the red maple leaf."),
        HistoryFact(290, 2, 16, 1959, "Caribbean", "Fidel Castro was sworn in as Prime Minister of Cuba."),
        HistoryFact(291, 2, 18, 1965, "Africa", "The Gambia gained independence from British colonial rule."),
        HistoryFact(292, 2, 19, 1878, "North America", "Thomas Edison patented the phonograph, an early sound recording device."),
        HistoryFact(293, 2, 22, 1980, "North America", "The United States ice hockey team defeated the Soviet Union at the Winter Olympics in a game later called the Miracle on Ice."),
        HistoryFact(294, 2, 23, 1945, "Asia", "U.S. Marines raised the flag atop Mount Suribachi during the Battle of Iwo Jima."),
        HistoryFact(295, 2, 24, 1976, "Caribbean", "Cuba adopted a new socialist constitution."),
        HistoryFact(296, 2, 26, 1993, "North America", "A truck bomb exploded in the parking garage of the World Trade Center in New York City."),
        HistoryFact(297, 2, 27, 1933, "Europe", "A fire severely damaged the German Reichstag building, an event the Nazi government used to justify expanded emergency powers."),
        HistoryFact(298, 2, 28, 1953, "Europe", "Scientists James Watson and Francis Crick announced they had determined the structure of DNA."),
        HistoryFact(299, 3, 1, 1872, "North America", "Yellowstone became the world's first officially designated national park."),
        HistoryFact(300, 3, 4, 1681, "North America", "King Charles II of England granted William Penn a charter for the territory that would become Pennsylvania."),
        HistoryFact(301, 3, 5, 1946, "Europe", "Winston Churchill delivered his Iron Curtain speech in Missouri, describing the division of Europe in the early Cold War."),
        HistoryFact(302, 3, 7, 1876, "North America", "Alexander Graham Bell was granted a patent for the telephone."),
        HistoryFact(303, 3, 9, 1796, "Europe", "Napoleon Bonaparte married Josephine de Beauharnais in Paris, shortly before taking command of French forces in Italy."),
        HistoryFact(304, 3, 10, 1959, "Asia", "A major uprising against Chinese rule broke out in Tibet, prompting the Dalai Lama to flee into exile in India."),
        HistoryFact(305, 3, 13, 1997, "North America", "Astronomer discoveries surrounding the Hale-Bopp comet drew record public attention as it reached peak visibility."),
        HistoryFact(306, 3, 14, 1794, "North America", "Inventor Eli Whitney received a patent for the cotton gin."),
        HistoryFact(307, 3, 16, 1521, "Asia", "Portuguese explorer Ferdinand Magellan's expedition reached the Philippine islands, one of the first European contacts with the archipelago."),
        HistoryFact(308, 3, 18, 1965, "Global", "Soviet cosmonaut Alexei Leonov performed the first spacewalk in human history."),
        HistoryFact(309, 3, 20, 1602, "Europe", "The Dutch East India Company was founded, often considered the world's first major multinational corporation."),
        HistoryFact(310, 3, 22, 1980, "Africa", "Southern Rhodesia was internationally recognized as the newly independent nation of Zimbabwe."),
        HistoryFact(311, 3, 24, 1989, "North America", "The oil tanker Exxon Valdez struck a reef off Alaska, causing a massive oil spill."),
        HistoryFact(312, 3, 27, 1964, "North America", "The Good Friday earthquake, the most powerful ever recorded in North America, struck Alaska."),
        HistoryFact(313, 3, 28, 1979, "North America", "A partial nuclear meltdown occurred at the Three Mile Island power plant in Pennsylvania."),
        HistoryFact(314, 3, 29, 1974, "Asia", "Archaeologists excavating near Xi'an, China, discovered the buried Terracotta Army."),
        HistoryFact(315, 3, 31, 1889, "Europe", "The Eiffel Tower officially opened in Paris."),
        HistoryFact(316, 4, 2, 1792, "North America", "The United States Congress established the U.S. Mint."),
        HistoryFact(317, 4, 3, 1973, "North America", "Motorola researcher Martin Cooper made the first handheld mobile phone call."),
        HistoryFact(318, 4, 5, 1976, "Asia", "The death of Chinese leader Zhou Enlai's memorial sparked mass public mourning that became a significant political moment."),
        HistoryFact(319, 4, 6, 1909, "North America", "Explorer Robert Peary's expedition claimed to have reached the North Pole."),
        HistoryFact(320, 4, 9, 1940, "Europe", "Germany invaded Denmark and Norway."),
        HistoryFact(321, 4, 10, 1912, "Europe", "The RMS Titanic departed Southampton, England, on its only voyage."),
        HistoryFact(322, 4, 11, 1970, "North America", "NASA launched Apollo 13, which suffered an onboard explosion en route to the Moon."),
        HistoryFact(323, 4, 13, 1943, "Europe", "The Jefferson Memorial was dedicated in Washington, D.C., on the 200th anniversary of Thomas Jefferson's birth."),
        HistoryFact(324, 4, 17, 1961, "Caribbean", "A CIA backed group of exiles launched the failed Bay of Pigs invasion of Cuba."),
        HistoryFact(325, 4, 18, 1906, "North America", "A major earthquake and resulting fires devastated San Francisco, California."),
        HistoryFact(326, 4, 21, 1926, "Europe", "Queen Elizabeth II of the United Kingdom was born in London."),
        HistoryFact(327, 4, 23, 1985, "North America", "The Coca-Cola Company announced a reformulated recipe, later reversing course after public backlash."),
        HistoryFact(328, 4, 24, 1990, "North America", "NASA launched the Hubble Space Telescope aboard the Space Shuttle Discovery."),
        HistoryFact(329, 4, 25, 1953, "Europe", "James Watson and Francis Crick published their landmark paper describing the double helix structure of DNA."),
        HistoryFact(330, 4, 28, 1789, "Global", "A mutiny occurred aboard the British ship HMS Bounty in the Pacific Ocean."),
        HistoryFact(331, 4, 29, 1913, "North America", "Inventor Gideon Sundback patented a practical version of the modern zipper."),
        HistoryFact(332, 5, 2, 1519, "Europe", "Renaissance artist and inventor Leonardo da Vinci died in Amboise, France."),
        HistoryFact(333, 5, 4, 1979, "Europe", "Margaret Thatcher became the first female Prime Minister of the United Kingdom."),
        HistoryFact(334, 5, 6, 1994, "Europe", "The Channel Tunnel officially opened, connecting England and France beneath the sea."),
        HistoryFact(335, 5, 7, 1915, "Europe", "A German submarine sank the passenger liner RMS Lusitania, killing nearly 1,200 people."),
        HistoryFact(336, 5, 9, 1960, "North America", "The U.S. Food and Drug Administration approved the first birth control pill."),
        HistoryFact(337, 5, 10, 1869, "North America", "The First Transcontinental Railroad was completed in the United States with the driving of a ceremonial golden spike."),
        HistoryFact(338, 5, 11, 1997, "Global", "IBM's Deep Blue computer defeated world chess champion Garry Kasparov in a full match for the first time."),
        HistoryFact(339, 5, 13, 1954, "Europe", "Sports Illustrated magazine published its very first issue in the United States."),
        HistoryFact(340, 5, 15, 1928, "North America", "The animated character Mickey Mouse debuted publicly in a short test screening."),
        HistoryFact(341, 5, 16, 1929, "North America", "The first Academy Awards ceremony was held in Hollywood, California."),
        HistoryFact(342, 5, 17, 1954, "North America", "The U.S. Supreme Court decided Brown v. Board of Education, ruling public school segregation unconstitutional."),
        HistoryFact(343, 5, 19, 1780, "North America", "An unusual atmospheric phenomenon caused a mysterious darkness to fall over parts of New England during the day."),
        HistoryFact(344, 5, 20, 1932, "North America", "Aviator Amelia Earhart began her solo flight across the Atlantic Ocean."),
        HistoryFact(345, 5, 21, 1927, "Europe", "Aviator Charles Lindbergh landed in Paris, completing the first solo nonstop transatlantic flight."),
        HistoryFact(346, 5, 26, 1940, "Europe", "The evacuation of Allied soldiers from Dunkirk, France, began during World War II."),
        HistoryFact(347, 5, 28, 1937, "North America", "The Golden Gate Bridge opened to vehicle traffic in San Francisco."),
        HistoryFact(348, 5, 30, 1911, "North America", "The first Indianapolis 500 automobile race was held."),
        HistoryFact(349, 5, 31, 1889, "North America", "The Johnstown Flood killed over 2,000 people in Pennsylvania after a dam failure."),
        HistoryFact(350, 6, 4, 1919, "North America", "The U.S. Congress passed the 19th Amendment, sending it to the states for ratification on women's suffrage."),
        HistoryFact(351, 6, 5, 1968, "North America", "U.S. presidential candidate Robert F. Kennedy was shot in Los Angeles, dying the following day."),
        HistoryFact(352, 6, 8, 1949, "Europe", "George Orwell's novel Nineteen Eighty Four was published in London."),
        HistoryFact(353, 6, 11, 1963, "Asia", "Buddhist monk Thich Quang Duc's self immolation in Saigon drew worldwide attention to the Vietnamese political crisis."),
        HistoryFact(354, 6, 14, 1919, "Europe", "British aviators John Alcock and Arthur Brown began the first nonstop transatlantic flight."),
        HistoryFact(355, 6, 16, 1963, "Global", "Soviet cosmonaut Valentina Tereshkova became the first woman to travel into space."),
        HistoryFact(356, 6, 18, 1815, "Europe", "The Battle of Waterloo ended Napoleon Bonaparte's rule as Emperor of the French."),
        HistoryFact(357, 6, 21, 1948, "Europe", "The first practical transistor was publicly demonstrated by researchers at Bell Labs in the United States."),
        HistoryFact(358, 6, 25, 1876, "North America", "The Battle of the Little Bighorn took place between the U.S. Army and a coalition of Native nations."),
        HistoryFact(359, 6, 29, 1613, "Europe", "London's Globe Theatre, closely associated with William Shakespeare, burned down during a performance."),
        HistoryFact(360, 6, 30, 1859, "Europe", "French acrobat Charles Blondin crossed Niagara Falls on a tightrope for the first time."),
    )
}
