package com.tyshi00.trinkets

// Original daily philosophy prompts and thought experiments written for
// Trinkets, not excerpted from any particular philosopher or text.
object TrinketsPhilosophyPrompts {
    val ALL: List<PhilosophyPrompt> = listOf(
        PhilosophyPrompt(1, "Imagine you could relive today exactly as it happened, forever, on a loop.", "Would today, as you lived it, be one you'd be willing to repeat?"),
        PhilosophyPrompt(2, "A ship has every plank replaced over the years until none of the original wood remains.", "Is it still the same ship? What does that suggest about whether you are the same person you were ten years ago?"),
        PhilosophyPrompt(3, "Consider the idea that you only ever truly own your attention, never your time.", "If that's true, what have you been spending your attention on lately, and is it where you'd choose to spend it?"),
        PhilosophyPrompt(4, "Suppose a machine could give you any experience you wanted, indistinguishable from reality, for the rest of your life.", "Would you plug in? What does your answer say about what you actually value?"),
        PhilosophyPrompt(5, "Think of a rule you follow even when you're certain no one is watching.", "Where did that rule come from, and would you still follow it if you knew, with total certainty, there were no consequences?"),
        PhilosophyPrompt(6, "Picture explaining today's biggest worry to someone one hundred years in the future.", "Does it still sound as urgent once you imagine it from that distance?"),
        PhilosophyPrompt(7, "Consider that every person you pass today is the main character of their own life, just as convinced of their own reality as you are of yours.", "How might that change the way you treat a stranger this week?"),
        PhilosophyPrompt(8, "A river is never the same river twice, since the water is always moving.", "In what ways are you not the same person you were this morning?"),
        PhilosophyPrompt(9, "Suppose you had to justify, out loud, why you deserve the good things that have happened to you.", "How much of it would you honestly attribute to your own effort, and how much to circumstance?"),
        PhilosophyPrompt(10, "Imagine two people experience the exact same event. One calls it the worst day of their life, the other calls it a turning point.", "What determines which one you become?"),
        PhilosophyPrompt(11, "Consider the idea that courage isn't the absence of fear, but acting anyway.", "What is something you're avoiding right now purely out of fear, not because it's actually a bad idea?"),
        PhilosophyPrompt(12, "Picture a stranger reading a complete, honest transcript of your inner thoughts from the last 24 hours.", "What would surprise them most?"),
        PhilosophyPrompt(13, "Suppose happiness and meaning were sometimes in tension, so that the most meaningful choice isn't always the happiest one in the moment.", "Which do you tend to chase more often?"),
        PhilosophyPrompt(14, "Think about a belief you hold strongly today that you didn't hold ten years ago.", "What changed your mind, and could the same kind of evidence change it again?"),
        PhilosophyPrompt(15, "Imagine you could know, with certainty, exactly how you'll be remembered by the people closest to you.", "Would you want to know? Would knowing change how you act today?"),
        PhilosophyPrompt(16, "Consider that most of what you call 'yourself,' your language, your habits, your tastes, was absorbed from other people.", "What's something about you that feels truly, originally yours?"),
        PhilosophyPrompt(17, "Picture a version of you who made the opposite choice at the last major fork in your life.", "What do you think that version of you is doing right now, and are you envious, relieved, or indifferent?"),
        PhilosophyPrompt(18, "Suppose every complaint you make today had to come with one concrete action you'd take to address it.", "How many of today's complaints would survive that rule?"),
        PhilosophyPrompt(19, "Think about the last time you changed your opinion because someone made a genuinely good argument.", "How open are you, honestly, to that happening again this week?"),
        PhilosophyPrompt(20, "Consider that the opposite of a great truth may also be a great truth.", "Is there a belief you hold that has a valid opposite you've never seriously considered?"),
        PhilosophyPrompt(21, "Imagine explaining your daily routine to someone from three hundred years ago.", "Which parts would they find wise, and which would they find strange?"),
        PhilosophyPrompt(22, "Picture the version of yourself who has already overcome the challenge you're currently facing.", "What would that version of you tell you to do right now?"),
        PhilosophyPrompt(23, "Suppose you could give your younger self exactly one sentence of advice, no more.", "What would it be, and are you actually living by it now?"),
        PhilosophyPrompt(24, "Consider the idea that we rarely regret the risks we took, but often regret the ones we didn't.", "Is there a small risk in front of you right now that you're talking yourself out of?"),
        PhilosophyPrompt(25, "Think about the difference between being busy and being productive.", "Which one described most of your day yesterday?"),
        PhilosophyPrompt(26, "Imagine a world where everyone could hear exactly what you say about them behind their back.", "Would you need to change how you speak about people?"),
        PhilosophyPrompt(27, "Picture the last thing that genuinely made you laugh out loud.", "How long has it been since that happened, and what does that tell you about your recent days?"),
        PhilosophyPrompt(28, "Suppose comfort and growth were mutually exclusive, so that you truly couldn't have both at once.", "Which one has your life leaned toward lately?"),
        PhilosophyPrompt(29, "Consider that other people's opinions of you are, in a sense, none of your business, since you can't fully know or control them.", "How much weight are you currently giving to an opinion you can't actually verify?"),
        PhilosophyPrompt(30, "Think about a time you were completely certain you were right, and later found out you weren't.", "What did that do to your confidence in your current certainties?"),
        PhilosophyPrompt(31, "Imagine your life divided into seasons rather than years: winters, springs, summers, autumns of experience.", "What season do you feel you're in right now?"),
        PhilosophyPrompt(32, "Picture two people: one who has everything they want but nothing left to want, and one who has little but is still striving.", "Which one do you suspect is happier, and why?"),
        PhilosophyPrompt(33, "Suppose gratitude were a skill you could train, like a muscle, rather than a feeling that just happens to you.", "What's one small rep you could do today?"),
        PhilosophyPrompt(34, "Consider that most fears are about an imagined future, not the present moment you're actually in.", "Is today's biggest worry about something happening right now, or something you're picturing?"),
        PhilosophyPrompt(35, "Think about the last decision you made purely to avoid discomfort, rather than because it was the better choice.", "What did it cost you?"),
        PhilosophyPrompt(36, "Imagine you had to describe your character using only your actions from the past week, not your intentions.", "Would the description match how you see yourself?"),
        PhilosophyPrompt(37, "Picture a wise elder from your own community, watching how you've handled today so far.", "What would they nod at approvingly, and what would they gently question?"),
        PhilosophyPrompt(38, "Suppose every person you resent is, in some way, dealing with a struggle you know nothing about.", "Does that change how you feel about the resentment?"),
        PhilosophyPrompt(39, "Consider that the things you own eventually end up owning a piece of your attention and effort.", "Is there something you own that costs you more than it gives you?"),
        PhilosophyPrompt(40, "Think about a goal you're chasing because you truly want it, versus one you're chasing because you think you should.", "Can you tell the difference in your own life right now?"),
        PhilosophyPrompt(41, "Imagine silence as a language of its own, something you could choose to speak more fluently.", "What would change if you said fewer things today, but meant every one of them more fully?"),
        PhilosophyPrompt(42, "Picture the busiest, most successful version of you and the calmest, most content version of you as two different people.", "Which one would you rather have dinner with?"),
        PhilosophyPrompt(43, "Suppose forgiveness is less about the other person and more about setting down something heavy you've been carrying.", "Is there something you're still carrying that you could choose to set down?"),
        PhilosophyPrompt(44, "Consider the idea that boredom is often just unmet curiosity waiting to be pointed somewhere.", "What would you explore right now if boredom struck and you leaned into it instead of reaching for a distraction?"),
        PhilosophyPrompt(45, "Think about the last apology you gave.", "Was it really an apology, or was it an explanation dressed up as one?"),
        PhilosophyPrompt(46, "Imagine measuring a day's success not by what you finished, but by how present you were while doing it.", "By that measure, how did yesterday go?"),
        PhilosophyPrompt(47, "Picture the version of 'enough' you had five years ago: enough money, enough achievement, enough approval.", "Have you actually reached it, or has the target quietly moved?"),
        PhilosophyPrompt(48, "Suppose every skill you now consider effortless was once something you were genuinely bad at.", "What are you currently bad at that you're avoiding simply because it's uncomfortable to be a beginner?"),
        PhilosophyPrompt(49, "Consider that patience is often just trust that things are unfolding, even when you can't see the process.", "Where in your life is your patience actually being tested right now?"),
        PhilosophyPrompt(50, "Think about the story you tell yourself about why you haven't yet done the thing you say you want to do.", "Is that story protecting you, or is it just familiar?"),
        PhilosophyPrompt(51, "Imagine two clocks: one measuring the hours of your life, one measuring how fully you lived them.", "Which one has been running faster lately?"),
        PhilosophyPrompt(52, "Picture the parts of your identity that are truly chosen versus the parts that were simply inherited or assigned.", "Which part do you find yourself defending the hardest?"),
        PhilosophyPrompt(53, "Suppose kindness, given consistently, changes the giver as much as the receiver.", "When was the last time you noticed that happening to you?"),
        PhilosophyPrompt(54, "Consider that most arguments aren't really about the topic at hand, but about each person wanting to feel heard.", "In your last disagreement, were you arguing to be right, or to be understood?"),
        PhilosophyPrompt(55, "Think about the difference between wanting to be respected and wanting to be liked.", "Which one drives more of your daily decisions?"),
        PhilosophyPrompt(56, "Imagine that every skill of self-discipline you build today is a gift to the person you'll be next year.", "What's one small discipline you could offer that future self right now?"),
        PhilosophyPrompt(57, "Picture your life as a book someone else will read after you're gone.", "What would you want the current chapter to say about how you spent your ordinary days, not just your big moments?"),
        PhilosophyPrompt(58, "Suppose the amount of energy you spend worrying about a problem has no bearing on how well you actually solve it.", "Where could you redirect worry-energy today into something more useful?"),
        PhilosophyPrompt(59, "Consider that humility isn't thinking less of yourself, but thinking of yourself less.", "Where in your day could a little less self-focus create more room for someone else?"),
        PhilosophyPrompt(60, "Think about the last time you did something difficult purely because it was the right thing to do, with no audience and no reward.", "How did it feel afterward, compared to how you expected it to feel beforehand?"),
        PhilosophyPrompt(61, "Consider that the version of you five years ago would be surprised by parts of your life today, both good and hard.", "Which part would surprise them most?"),
        PhilosophyPrompt(62, "Imagine you had to teach today's most important lesson to a child.", "How would you explain it in words simple enough for them to actually understand?"),
        PhilosophyPrompt(63, "Picture the difference between a life optimized for comfort and a life optimized for meaning.", "Which one have your recent choices actually been optimizing for?"),
        PhilosophyPrompt(64, "Suppose every person you've ever disappointed eventually forgave you completely.", "Would that change how harshly you judge yourself for it now?"),
        PhilosophyPrompt(65, "Consider that most people are simply doing their best with the tools they were given.", "Does that change how you see someone who frustrated you recently?"),
        PhilosophyPrompt(66, "Think about a habit you've kept for years without ever questioning why you started it.", "Would you choose to start it again today, knowing what you know now?"),
        PhilosophyPrompt(67, "Imagine describing your ideal ordinary Tuesday, nothing special, just a day you'd want repeated often.", "How close does your actual routine come to that description?"),
        PhilosophyPrompt(68, "Picture the last time you assumed the worst about someone's intentions and later found out you were wrong.", "How often does that pattern repeat, if you're honest?"),
        PhilosophyPrompt(69, "Suppose effort and outcome were never guaranteed to match.", "Does that change how you'd choose to spend today, if outcome was never promised anyway?"),
        PhilosophyPrompt(70, "Consider that silence, in a conversation, is often mistaken for agreement.", "Is there something you've stayed silent about that you actually disagree with?"),
        PhilosophyPrompt(71, "Think about the last time you said yes to something you actually wanted to say no to.", "What would it take for you to say no the next time it comes up?"),
        PhilosophyPrompt(72, "Imagine measuring wealth not in money, but in the number of people who could call you at 2am for help.", "How wealthy are you by that measure?"),
        PhilosophyPrompt(73, "Picture the parts of your day that feel automatic, barely noticed at all.", "What would happen if you tried to be fully present for just one of them today?"),
        PhilosophyPrompt(74, "Suppose you had to defend, out loud, why the way you spend your evenings actually matters to you.", "Could you make that case honestly?"),
        PhilosophyPrompt(75, "Consider that curiosity and judgment rarely occupy the same moment.", "Which one showed up first the last time someone surprised you?"),
        PhilosophyPrompt(76, "Think about a fear you inherited from someone else, rather than one you built from your own experience.", "Is it still serving you, or is it simply familiar?"),
        PhilosophyPrompt(77, "Imagine your reputation as something built entirely by your smallest, most repeated actions.", "What does the pattern actually say, apart from what you intend it to say?"),
        PhilosophyPrompt(78, "Picture the version of confidence that comes from competence, not performance.", "Where in your life have you actually earned that kind of quiet confidence?"),
        PhilosophyPrompt(79, "Suppose every excuse you've used this month had to be said honestly, out loud, to the person it affected.", "Which excuse would be hardest to say plainly?"),
        PhilosophyPrompt(80, "Consider that most growth happens in private, long before anyone notices it from the outside.", "What private growth are you in the middle of right now?"),
        PhilosophyPrompt(81, "Think about the difference between being right and being kind, in a moment when you can't have both.", "Which do you tend to choose?"),
        PhilosophyPrompt(82, "Imagine your attention as a limited resource you spend, not something that simply happens to you.", "Where did most of it go yesterday, and was that a choice or a default?"),
        PhilosophyPrompt(83, "Picture a decision you keep delaying because neither option feels fully safe.", "What is the delay itself actually costing you?"),
        PhilosophyPrompt(84, "Suppose you had to identify the one belief holding your current routine together.", "Is that belief still true, or just familiar?"),
        PhilosophyPrompt(85, "Consider that admiration for someone else's life often says more about what you want than about them.", "What do you find yourself admiring in others lately, and what does it reveal?"),
        PhilosophyPrompt(86, "Think about the last time you were proud of yourself for something no one else even noticed.", "How often do you let that be enough?"),
        PhilosophyPrompt(87, "Imagine explaining, honestly, why you haven't rested properly in a while.", "Would the explanation hold up, or is it mostly habit?"),
        PhilosophyPrompt(88, "Picture two versions of ambition, one that competes with others and one that only competes with yesterday's version of you.", "Which one actually drives you?"),
        PhilosophyPrompt(89, "Suppose you had to name the exact moment you stopped believing something you once believed strongly.", "Was it a single moment, or a slow accumulation?"),
        PhilosophyPrompt(90, "Consider that most conflict comes from two people wanting the same thing, safety, respect, or certainty, but pursuing it differently.", "What's the real thing underneath your last disagreement?"),
        PhilosophyPrompt(91, "Think about a compliment you've never fully believed, even when you knew it was sincere.", "What would it take to actually accept it?"),
        PhilosophyPrompt(92, "Imagine your future self visiting today just to observe, without being able to intervene.", "What would they be quietly hoping you'd choose?"),
        PhilosophyPrompt(93, "Picture the last time you changed your plans because of someone else's opinion, not your own judgment.", "Do you agree with that decision now?"),
        PhilosophyPrompt(94, "Suppose every skill you avoid practicing is a door you're quietly choosing to keep closed.", "Which door have you been walking past for a while now?"),
        PhilosophyPrompt(95, "Consider that most people remember how you made them feel far longer than what you actually said.", "How did you make the last three people you spoke with feel?"),
        PhilosophyPrompt(96, "Think about the story you'd tell if today were the only day anyone ever knew about your life.", "Would it be a story you're proud to tell?"),
        PhilosophyPrompt(97, "Imagine that discomfort is simply information, not a signal to retreat.", "What is today's discomfort actually trying to tell you?"),
        PhilosophyPrompt(98, "Picture the last promise you made only to yourself, with no witness at all.", "Have you kept it so far?"),
        PhilosophyPrompt(99, "Suppose your work today left no trace anyone could see, ever.", "Would you still choose to do it well?"),
        PhilosophyPrompt(100, "Consider that most regret is really just unfinished learning, waiting to be applied.", "What is your oldest regret still trying to teach you?"),
        PhilosophyPrompt(101, "Think about the version of rest that actually restores you, versus the version that just distracts you.", "Which one did you get yesterday?"),
        PhilosophyPrompt(102, "Imagine a stranger observing only your body language for the past hour.", "What would they assume about your mood, and would they be right?"),
        PhilosophyPrompt(103, "Picture the last time you underestimated how capable you actually were.", "What changed your mind afterward?"),
        PhilosophyPrompt(104, "Suppose every worry you're carrying today had an honest deadline for when you'd finally address it.", "What would that deadline be?"),
        PhilosophyPrompt(105, "Consider that most people are more forgiving of others than they are of themselves.", "Would you extend to yourself the same grace you gave a friend last week?"),
        PhilosophyPrompt(106, "Think about the difference between wanting to change and actually being willing to be inconvenienced by change.", "Which one describes where you are right now?"),
        PhilosophyPrompt(107, "Imagine your life as a series of small votes for the kind of person you're becoming.", "What did today's votes say so far?"),
        PhilosophyPrompt(108, "Picture the last time you felt truly at ease, with nothing to prove and nowhere to rush.", "What made that moment possible?"),
        PhilosophyPrompt(109, "Suppose the opinions you fear most are held by people whose lives you wouldn't actually want to live.", "Does that change how much weight those opinions deserve?"),
        PhilosophyPrompt(110, "Consider that most fear of failure is really fear of being seen failing.", "Would the task feel different if no one else would ever know the outcome?"),
        PhilosophyPrompt(111, "Think about a time your plans fell apart and something better happened instead.", "How often does that pattern actually repeat, if you track it honestly?"),
        PhilosophyPrompt(112, "Imagine treating your own time with the same respect you'd expect someone to treat your money.", "Where did you overspend it yesterday?"),
        PhilosophyPrompt(113, "Picture the last thing you finished simply because you said you would, not because you still wanted to.", "What did that follow through actually cost or earn you?"),
        PhilosophyPrompt(114, "Suppose comparison is only useful when it's comparing you to your own past, never to someone else's present.", "What comparison have you been making lately that isn't actually useful?"),
        PhilosophyPrompt(115, "Consider that most people wish they had asked for help sooner, not less often.", "Is there something right now you're quietly trying to handle alone?"),
        PhilosophyPrompt(116, "Think about the last time you assumed a closed door meant the end, rather than a redirection.", "Looking back, was it actually the end?"),
        PhilosophyPrompt(117, "Imagine your inner critic as a separate person sitting across from you.", "Would you let them speak to a friend the way they speak to you?"),
        PhilosophyPrompt(118, "Picture the smallest act of integrity you performed today, one no one else witnessed.", "Did you notice it, or did it pass without acknowledgment?"),
        PhilosophyPrompt(119, "Suppose every person who ever inspired you also had days exactly like today, uncertain and unremarkable.", "Does that change how you view your own uncertain, unremarkable days?"),
        PhilosophyPrompt(120, "Consider that hope and denial can look identical from the outside, but feel very different from the inside.", "Which one is actually present in how you're viewing your current situation?"),
        PhilosophyPrompt(121, "Think about the difference between being needed and being valued.", "Which one do you currently feel more of?"),
        PhilosophyPrompt(122, "Imagine explaining to a curious child why adults so often say they're too busy to rest.", "Would your explanation make sense to them, or even to you?"),
        PhilosophyPrompt(123, "Picture the version of yourself who handled a hard year with grace you didn't know you had.", "What did that version of you actually rely on to get through it?"),
        PhilosophyPrompt(124, "Suppose every small kindness you've ever received quietly shaped who you became.", "Whose kindness are you still carrying forward today, even without realizing it?"),
        PhilosophyPrompt(125, "Consider that most people don't remember your mistakes nearly as vividly as you do.", "Is there a mistake you're still replaying that everyone else has already forgotten?"),
        PhilosophyPrompt(126, "Think about the last time you chose the difficult conversation over the comfortable silence.", "How did it change things, for better or worse?"),
        PhilosophyPrompt(127, "Imagine your values as a compass rather than a scoreboard, something to orient by, not something to measure against others.", "Which value is guiding today's decisions?"),
        PhilosophyPrompt(128, "Picture the last time you trusted your gut over your careful analysis.", "Which one turned out to be right?"),
        PhilosophyPrompt(129, "Suppose everyone you meet today is carrying something invisible and heavy.", "How might that change the tone you use with the next stranger you encounter?"),
        PhilosophyPrompt(130, "Consider that most people overestimate how much others are paying attention to their mistakes.", "Would you take more risks today if you truly believed that?"),
        PhilosophyPrompt(131, "Think about the last time doing nothing was actually the wisest choice available.", "How hard was it to accept that stillness was the right move?"),
        PhilosophyPrompt(132, "Imagine measuring your week not by hours worked, but by moments you were fully present.", "How many moments would that week actually contain?"),
        PhilosophyPrompt(133, "Picture the last apology you received that genuinely changed how you felt about the person.", "What made it land differently than others?"),
        PhilosophyPrompt(134, "Suppose your habits today are simply votes for who you'll be in five years.", "Which habit deserves reconsideration, based on that standard?"),
        PhilosophyPrompt(135, "Consider that most burnout comes not from working hard, but from working without any sense of choice.", "Where in your life do you feel the most choice right now, and where the least?"),
        PhilosophyPrompt(136, "Think about the last time someone's belief in you outpaced your belief in yourself.", "Did their belief eventually catch up to reality?"),
        PhilosophyPrompt(137, "Imagine the version of today where you assumed things would work out reasonably well.", "How would you move differently, starting right now, if you believed that?"),
        PhilosophyPrompt(138, "Picture the last boundary you set that felt uncomfortable in the moment but right in hindsight.", "What made it worth the discomfort?"),
        PhilosophyPrompt(139, "Suppose every person who ever doubted you eventually turned out to be simply wrong.", "Would that change how much space you give to today's doubts?"),
        PhilosophyPrompt(140, "Consider that most wisdom is just hindsight, applied a little earlier than usual.", "What hindsight from last year could you apply to a decision you're facing right now?"),
        PhilosophyPrompt(141, "Think about the last time you felt genuinely useful to someone, not just busy.", "What made that moment feel different from an ordinary productive day?"),
        PhilosophyPrompt(142, "Imagine your patience as a resource that regenerates only through rest, not willpower.", "How well have you been resting it lately?"),
        PhilosophyPrompt(143, "Picture a rule you enforce on yourself that you'd never enforce on someone you loved.", "Why does the rule apply differently to you?"),
        PhilosophyPrompt(144, "Suppose every skill you now take for granted once felt impossible to someone watching you learn it.", "What impossible-feeling skill are you in the middle of learning right now?"),
        PhilosophyPrompt(145, "Consider that most people don't fear failure itself, they fear what failure might say about them.", "What would today's task say about you if it went badly, and is that actually true?"),
        PhilosophyPrompt(146, "Think about the last decision you made that your future self will likely thank you for.", "What made it possible to choose that path in the moment?"),
        PhilosophyPrompt(147, "Imagine treating every small annoyance today as data instead of an emergency.", "What would that shift actually change about your afternoon?"),
        PhilosophyPrompt(148, "Picture the last time you gave someone the benefit of the doubt and it turned out to matter.", "Who could use that same benefit from you today?"),
        PhilosophyPrompt(149, "Suppose your reputation with yourself matters more than your reputation with anyone else.", "How is that particular reputation holding up lately?"),
        PhilosophyPrompt(150, "Consider that most anxious thoughts are rehearsals for events that never happen exactly as imagined.", "How many of today's worries have historically come true as pictured?"),
        PhilosophyPrompt(151, "Think about the difference between humility and self-doubt.", "Which one is actually present in how you're talking to yourself today?"),
        PhilosophyPrompt(152, "Imagine explaining your current stress level to someone who has faced genuine hardship.", "Would the explanation still feel proportionate?"),
        PhilosophyPrompt(153, "Picture the last time you let go of a grudge and immediately felt lighter.", "Is there a lighter version of today waiting behind a grudge you're still holding?"),
        PhilosophyPrompt(154, "Suppose every act of generosity you've ever received quietly built the person you are now.", "Whose generosity are you passing forward today, even indirectly?"),
        PhilosophyPrompt(155, "Consider that most people judge themselves by their intentions but judge others by their actions.", "Is there someone you could extend the intention-based grace to today?"),
        PhilosophyPrompt(156, "Think about the last time silence taught you more than a conversation would have.", "What did you notice by simply not speaking?"),
        PhilosophyPrompt(157, "Imagine your body as a lifelong companion rather than a project to constantly improve.", "How would that shift change how you treat it today?"),
        PhilosophyPrompt(158, "Picture the last time you were wrong in an argument and admitted it out loud.", "How did that admission change the outcome?"),
        PhilosophyPrompt(159, "Suppose the version of success you're chasing was actually defined by someone else, long before you had a say.", "Would you choose the same definition if you were starting fresh today?"),
        PhilosophyPrompt(160, "Consider that most people crave being understood more than they crave being agreed with.", "Did your last conversation aim for understanding or agreement?"),
        PhilosophyPrompt(161, "Think about a fear that shrank the moment you finally faced it directly.", "Is there a fear right now you've only been facing indirectly?"),
        PhilosophyPrompt(162, "Imagine measuring today's success by how honest you were, rather than how impressive you appeared.", "By that measure, how is today going?"),
        PhilosophyPrompt(163, "Picture the last habit you built that felt impossible for the first week and automatic by the third.", "What made the difference between those two weeks?"),
        PhilosophyPrompt(164, "Suppose every person's worst day is invisible to everyone but them.", "Could the person who frustrated you today be having one right now?"),
        PhilosophyPrompt(165, "Consider that most creativity is simply permission you gave yourself to make something imperfect.", "What imperfect thing have you been holding back from starting?"),
        PhilosophyPrompt(166, "Think about the last time you noticed your own growth only by comparing two distant points in time.", "What would that comparison reveal if you did it again today?"),
        PhilosophyPrompt(167, "Imagine your recurring complaints as requests you haven't actually made out loud yet.", "What request is hiding underneath today's biggest complaint?"),
        PhilosophyPrompt(168, "Picture the last time doing the smaller, easier task first actually built momentum for the bigger one.", "Could that same trick help you today?"),
        PhilosophyPrompt(169, "Suppose confidence is built through evidence, not affirmations alone.", "What small piece of evidence could you gather today to support it?"),
        PhilosophyPrompt(170, "Consider that most anger is a secondary emotion, covering something more vulnerable underneath.", "What's underneath the last flash of anger you felt?"),
        PhilosophyPrompt(171, "Think about the last time you trusted a process even though you couldn't see the end result yet.", "What allowed you to trust it?"),
        PhilosophyPrompt(172, "Imagine your daily choices as letters written to the person you'll be in ten years.", "What would today's letter say?"),
        PhilosophyPrompt(173, "Picture the last time you let curiosity replace defensiveness in a hard conversation.", "How did the conversation change because of it?"),
        PhilosophyPrompt(174, "Suppose most of what you're chasing right now would still matter to you in five years, but not all of it.", "Which parts would still matter, and which wouldn't?"),
        PhilosophyPrompt(175, "Consider that most people remember the way you listened far longer than the advice you gave.", "How present were you the last time someone needed to talk?"),
        PhilosophyPrompt(176, "Think about a limiting belief you inherited so early you never questioned where it came from.", "Where do you think it actually originated?"),
        PhilosophyPrompt(177, "Imagine treating uncertainty as a normal condition of being alive, rather than a problem to solve immediately.", "Would that change how you're approaching today's biggest unknown?"),
        PhilosophyPrompt(178, "Picture the last time you finished something you almost quit halfway through.", "What kept you going in that moment?"),
        PhilosophyPrompt(179, "Suppose every person who ever mentored you did so imperfectly, but still meaningfully.", "Who are you imperfectly mentoring right now, even without the title?"),
        PhilosophyPrompt(180, "Consider that most people are more resilient than their worst day suggests.", "What evidence from your own past supports that about you?"),
        PhilosophyPrompt(181, "Think about the last time you chose depth over breadth, one thing done well instead of many things done quickly.", "How did the outcome compare to your usual approach?"),
        PhilosophyPrompt(182, "Imagine your morning mood as a weather system, temporary and passing, not a permanent forecast for the day.", "Has today's mood actually shifted at all since it started?"),
        PhilosophyPrompt(183, "Picture the last time you let someone help you finish something you were struggling with alone.", "What made it hard to ask in the first place?"),
        PhilosophyPrompt(184, "Suppose the story you tell about your own past is only one version among several equally true ones.", "What would a kinder version of that story sound like?"),
        PhilosophyPrompt(185, "Consider that most regret about time comes from spending it on things that never mattered to begin with.", "What's something you spent time on this week that genuinely mattered?"),
        PhilosophyPrompt(186, "Think about the last time you were honest about needing rest instead of pushing through out of habit.", "What happened as a result?"),
        PhilosophyPrompt(187, "Imagine describing your current chapter of life to someone who only knew you five years ago.", "What would surprise them most about how you've changed?"),
        PhilosophyPrompt(188, "Picture the last time a small act of discipline paid off far more than you expected.", "What discipline, however small, could pay off the same way today?"),
        PhilosophyPrompt(189, "Suppose every person you envy has a private struggle you know nothing about.", "Does that change the shape of the envy at all?"),
        PhilosophyPrompt(190, "Consider that most people wish they'd spoken up sooner, not stayed quiet longer.", "Is there something you're waiting too long to say?"),
        PhilosophyPrompt(191, "Think about the last time being wrong actually made you more credible, not less, because of how you handled it.", "What did that handling look like?"),
        PhilosophyPrompt(192, "Imagine your energy today as a budget you get to allocate deliberately, not a fixed amount that simply happens to you.", "Where is most of today's budget currently going?"),
        PhilosophyPrompt(193, "Picture the last time you gave yourself credit for something you usually dismiss as ordinary.", "What ordinary thing deserves credit today?"),
        PhilosophyPrompt(194, "Suppose the anxious voice in your head and the wise voice in your head are not the same speaker.", "Which one has been louder today?"),
        PhilosophyPrompt(195, "Consider that most people underestimate how much a short, sincere thank you actually means to the receiver.", "Who could use one from you today?"),
        PhilosophyPrompt(196, "Think about the last time a plan changing turned out to be a hidden favor.", "Could today's disruption be the same kind of favor, just not recognized yet?"),
        PhilosophyPrompt(197, "Imagine treating your attention span like a muscle that strengthens with practice, not a fixed trait.", "What would ten focused minutes actually build, if repeated daily?"),
        PhilosophyPrompt(198, "Picture the last time you chose long-term peace over short-term winning an argument.", "How did that choice feel afterward, compared to the alternative?"),
        PhilosophyPrompt(199, "Suppose most comparisons to other people are actually comparisons to a version of them you've never fully seen.", "Is there a comparison today that's based more on assumption than fact?"),
        PhilosophyPrompt(200, "Consider that most people who seem naturally confident simply practiced looking confident before they felt it.", "Where could you practice that today, even before the feeling arrives?"),
        PhilosophyPrompt(201, "Think about the last time saying no to something small protected your ability to say yes to something bigger.", "Is there a small no today that would protect a bigger yes?"),
        PhilosophyPrompt(202, "Imagine measuring a friendship not by how often you talk, but by how safe it feels to be honest.", "Which friendship in your life currently measures highest?"),
        PhilosophyPrompt(203, "Picture the last time you learned something valuable specifically because you were willing to look foolish first.", "What are you avoiding right now because it might make you look foolish?"),
        PhilosophyPrompt(204, "Suppose gratitude and ambition can coexist without canceling each other out.", "Can you hold both about your current situation at the same time?"),
        PhilosophyPrompt(205, "Consider that most people are kinder in their private thoughts about others than in their public words.", "Is there a kind private thought about someone you could actually say out loud today?"),
        PhilosophyPrompt(206, "Think about the last time you noticed a pattern in your own behavior you'd never named before.", "What did naming it change?"),
        PhilosophyPrompt(207, "Imagine treating your to-do list as a menu of options rather than a set of obligations.", "Which item would you actually choose first, if it were truly optional?"),
        PhilosophyPrompt(208, "Picture the last time being direct, instead of hinting, actually solved a problem faster.", "Is there a hint today that should become a direct request instead?"),
        PhilosophyPrompt(209, "Suppose most burnout builds slowly enough that it's easy to miss until it's loud.", "What quiet signal have you been ignoring lately?"),
        PhilosophyPrompt(210, "Consider that most people remember being believed in more than being praised.", "Who in your life could use to hear that you believe in them, specifically, today?"),
        PhilosophyPrompt(211, "Think about the last time slowing down actually got you to the right answer faster than rushing would have.", "Is there a decision today that deserves that same patience?"),
        PhilosophyPrompt(212, "Imagine your habits as a room you're slowly furnishing, one choice at a time, rather than something fixed and finished.", "What piece of furniture would you add to that room today?"),
        PhilosophyPrompt(213, "Picture the last time forgiving someone had more to do with your own peace than with excusing what they did.", "Is there a grudge today that's costing you more than it's costing them?"),
        PhilosophyPrompt(214, "Suppose most people are more interested in your questions about them than your opinions about yourself.", "What question could you ask someone today instead of leading with your own update?"),
        PhilosophyPrompt(215, "Consider that most self-improvement fails not from lack of motivation, but from expecting motivation to last without structure.", "What structure, not motivation, could support today's goal?"),
        PhilosophyPrompt(216, "Think about the last time being uncomfortable in a conversation actually deepened the relationship afterward.", "Is there a conversation you're avoiding for that same reason?"),
        PhilosophyPrompt(217, "Imagine your version of rest looking completely different from someone else's, and both being equally valid.", "What does true rest actually look like for you, specifically, today?"),
        PhilosophyPrompt(218, "Picture the last time doing less, on purpose, actually improved the quality of what you did do.", "Could that same trade apply to today?"),
        PhilosophyPrompt(219, "Suppose the people who know you best would describe your character using your habits, not your goals.", "What would that description actually say right now?"),
        PhilosophyPrompt(220, "Consider that most days that feel wasted in the moment still contributed something you couldn't see yet.", "What might today quietly be contributing to, even if it's not obvious?"),
        PhilosophyPrompt(221, "Think about the last time you chose to trust someone before they'd fully earned it, and it worked out.", "Is there someone today who deserves that same early trust?"),
        PhilosophyPrompt(222, "Imagine your best ideas as things that arrive quietly, not through force but through space you made for them.", "Have you made any space today, or has it all been filled?"),
        PhilosophyPrompt(223, "Picture the last time a mistake taught you something no success ever could have.", "What is today's small mistake trying to teach you?"),
        PhilosophyPrompt(224, "Suppose the way you treat people who can't do anything for you is the truest measure of your character.", "How did you treat that kind of person most recently?"),
        PhilosophyPrompt(225, "Consider that most people who seem to have it all together are simply better at hiding the parts that don't.", "Does that change how you compare yourself to them?"),
        PhilosophyPrompt(226, "Think about the last time you chose progress over perfection and actually finished something because of it.", "Is there a perfectionist stall happening right now that could use that same permission?"),
        PhilosophyPrompt(227, "Imagine describing today's stress to your future self, ten years from now, looking back with real perspective.", "Would future you still call it a big deal?"),
        PhilosophyPrompt(228, "Picture the last time you noticed someone quietly doing more than their share, without asking for recognition.", "Did you thank them, or did it pass unnoticed?"),
        PhilosophyPrompt(229, "Suppose most anxiety about the future disappears the moment you're fully engaged in the present.", "What's the most present you've felt today so far?"),
        PhilosophyPrompt(230, "Consider that most people never regret the kindness they showed, only the kindness they held back.", "Is there a kindness you're holding back right now?"),
        PhilosophyPrompt(231, "Think about the last time you let a small win count as a real win, instead of dismissing it.", "What small win from today deserves to actually count?"),
        PhilosophyPrompt(232, "Imagine your recurring excuses as a map showing exactly where your fears are hiding.", "What does today's excuse actually reveal, if you follow it honestly?"),
        PhilosophyPrompt(233, "Picture the last time being patient with someone else's pace actually taught you something about your own.", "Whose pace are you currently impatient with?"),
        PhilosophyPrompt(234, "Suppose most people are far more forgiving of your mistakes than you assume they'll be.", "Is there a mistake you're still hiding out of fear of a reaction that might not even happen?"),
        PhilosophyPrompt(235, "Consider that most clarity comes after action, not before it.", "What action, taken today, might create the clarity you're currently waiting for?"),
        PhilosophyPrompt(236, "Think about the last time a boundary you set actually improved a relationship instead of damaging it.", "Is there a boundary right now that's overdue?"),
        PhilosophyPrompt(237, "Imagine your inner voice speaking to a child version of yourself instead of the adult you are now.", "Would you speak more gently to that child than you speak to yourself today?"),
        PhilosophyPrompt(238, "Picture the last time doing the right thing cost you something, and you did it anyway.", "What did that cost actually teach you about your own values?"),
        PhilosophyPrompt(239, "Suppose most people remember specific moments of being helped far more vividly than general acts of generosity.", "What specific moment of help are you still grateful for?"),
        PhilosophyPrompt(240, "Consider that most of what feels urgent today will be forgotten within a year.", "What would you focus on instead, if urgency wasn't the deciding factor?"),
        PhilosophyPrompt(241, "Think about the last time you admitted you didn't know something, and it actually built trust rather than losing it.", "Is there something today you're pretending to know that you could admit you don't?"),
        PhilosophyPrompt(242, "Imagine treating rejection as redirection, information about fit rather than a verdict on your worth.", "How would that reframe change how you're carrying a recent no?"),
        PhilosophyPrompt(243, "Picture the last time you noticed real change in yourself only because someone else pointed it out first.", "What might someone notice about you right now that you haven't noticed yourself?"),
        PhilosophyPrompt(244, "Suppose most people wish they had celebrated their wins more, not less.", "What win from this month deserves a little more celebration than you gave it?"),
        PhilosophyPrompt(245, "Consider that most habits form invisibly, one unremarkable repetition at a time.", "What invisible habit are you quietly building today, for better or worse?"),
        PhilosophyPrompt(246, "Think about the last time listening without trying to fix anything was actually the most helpful thing you could do.", "Is there someone today who needs that instead of advice?"),
        PhilosophyPrompt(247, "Imagine your energy for other people as a cup that needs refilling, not an endless well.", "How full is your cup right now, honestly?"),
        PhilosophyPrompt(248, "Picture the last time you trusted your own judgment over a louder, more confident opinion in the room.", "Was your judgment right?"),
        PhilosophyPrompt(249, "Suppose most people who criticize loudly are working through something that has little to do with you.", "Does that change how you're holding onto the last piece of criticism you received?"),
        PhilosophyPrompt(250, "Consider that most peace comes from acceptance of what already happened, not from changing it.", "What could you accept today instead of continuing to fight it?"),
        PhilosophyPrompt(251, "Think about the last time you noticed joy in something ordinary, a smell, a sound, a small routine.", "What ordinary thing today deserves that same noticing?"),
        PhilosophyPrompt(252, "Imagine treating every interruption today as a chance to practice patience rather than an obstacle to your plan.", "Would that reframe change your mood about the next interruption?"),
        PhilosophyPrompt(253, "Picture the last time you realized a worry you carried for weeks resolved itself without your intervention.", "Is there a current worry that might resolve the same way, given time?"),
        PhilosophyPrompt(254, "Suppose most people undervalue consistency because it doesn't look impressive day to day.", "What consistent, unimpressive thing have you kept doing anyway?"),
        PhilosophyPrompt(255, "Consider that most people feel closer to those who ask real questions, not those who share the most facts.", "What real question could you ask someone today?"),
        PhilosophyPrompt(256, "Think about the last time choosing rest actually made you more productive the next day.", "Is today a day that calls for that same trade?"),
        PhilosophyPrompt(257, "Imagine your discomfort with silence as something you could practice sitting with, rather than immediately filling.", "How long could you sit with silence today before needing to fill it?"),
        PhilosophyPrompt(258, "Picture the last time you were more critical of your own work than anyone else who actually saw it.", "Is that happening again with something you finished recently?"),
        PhilosophyPrompt(259, "Suppose most anger fades faster when it's expressed honestly instead of held quietly.", "Is there something you're holding quietly that deserves honest expression?"),
        PhilosophyPrompt(260, "Consider that most people learn more from watching how you handle failure than from watching your successes.", "What is your handling of a recent setback actually teaching the people around you?"),
        PhilosophyPrompt(261, "Think about the last time you chose to be curious about a disagreement instead of trying to win it.", "What would curiosity look like in your next disagreement?"),
        PhilosophyPrompt(262, "Imagine treating your own limits as information, not failure.", "What limit are you currently ignoring that deserves to be respected instead?"),
        PhilosophyPrompt(263, "Picture the last time you noticed the difference between being alone and being lonely.", "Which one describes today, if either?"),
        PhilosophyPrompt(264, "Suppose most people remember the effort you made more than the outcome you achieved.", "What effort from this week deserves recognition, regardless of outcome?"),
        PhilosophyPrompt(265, "Consider that most habits of self-criticism were learned somewhere, from someone, and can be unlearned the same way.", "Where do you think your harshest self-criticism was first learned?"),
        PhilosophyPrompt(266, "Think about the last time doing something imperfectly was still far better than not doing it at all.", "Is there something today that deserves an imperfect attempt over no attempt?"),
        PhilosophyPrompt(267, "Imagine your recurring thoughts as visitors, some worth inviting in and some worth simply letting pass by.", "Which visitor showed up again today that you could simply let pass?"),
        PhilosophyPrompt(268, "Picture the last time you were proud of how you handled a disappointment, not just how you handled a win.", "What did that handling look like?"),
        PhilosophyPrompt(269, "Suppose most people crave being asked how they're really doing, not just how they're doing.", "Who could you ask that real question to today?"),
        PhilosophyPrompt(270, "Consider that most clarity about what you want comes only after trying the wrong thing first.", "What wrong thing taught you something useful about what you actually want?"),
        PhilosophyPrompt(271, "Think about the last time you chose to finish something small rather than start something new.", "Is there something small left unfinished that deserves today's attention instead of a new project?"),
        PhilosophyPrompt(272, "Imagine your patience with strangers as a mirror of your patience with yourself.", "What does today's patience level with strangers reveal?"),
        PhilosophyPrompt(273, "Picture the last time slowing your speech, on purpose, made a hard conversation go better.", "Could that same pace help a conversation you're dreading today?"),
        PhilosophyPrompt(274, "Suppose most confidence is simply the memory of having survived difficulty before.", "What past difficulty could you draw confidence from today?"),
        PhilosophyPrompt(275, "Consider that most people who seem unbothered by setbacks have simply had more practice recovering from them.", "What practice at recovering are you quietly gaining right now?"),
        PhilosophyPrompt(276, "Think about the last time choosing not to respond immediately actually improved the outcome.", "Is there a message today that deserves a pause before replying?"),
        PhilosophyPrompt(277, "Imagine treating your own opinions as drafts, open to revision, rather than final conclusions.", "What opinion are you holding today that might deserve a second look?"),
        PhilosophyPrompt(278, "Picture the last time you noticed that comparison stole more joy than it ever gave motivation.", "Is there a comparison today doing more harm than good?"),
        PhilosophyPrompt(279, "Suppose most people who inspire you started from a place remarkably similar to where you are right now.", "What similar starting point do you share with someone who inspires you?"),
        PhilosophyPrompt(280, "Consider that most burnout heals not through a single vacation, but through smaller, repeated permissions to rest.", "What small permission to rest could you give yourself today?"),
        PhilosophyPrompt(281, "Think about the last time you noticed a friend needed you more than they were willing to admit out loud.", "Is there a friend right now in that same position?"),
        PhilosophyPrompt(282, "Imagine your recurring self-doubt as an old, outdated map that no longer matches the actual territory of who you've become.", "Where is that map most clearly out of date?"),
        PhilosophyPrompt(283, "Picture the last time being generous with your time actually gave you more energy, not less.", "Could that same generosity apply to someone today?"),
        PhilosophyPrompt(284, "Suppose most people remember your presence at hard moments more than your advice at easy ones.", "Where could your simple presence matter most today?"),
        PhilosophyPrompt(285, "Consider that most goals feel more achievable once they're broken into a single next physical action.", "What's the single next physical action for today's biggest goal?"),
        PhilosophyPrompt(286, "Think about the last time you chose honesty over harmony, and the relationship survived it just fine.", "Is there honesty owed somewhere today that you've been trading for harmony?"),
        PhilosophyPrompt(287, "Imagine treating your own curiosity as a compass toward what actually matters to you, not just what's expected of you.", "What is your curiosity quietly pointing toward lately?"),
        PhilosophyPrompt(288, "Picture the last time forgiving yourself for something small actually made room for real change.", "What small thing could you forgive yourself for today?"),
        PhilosophyPrompt(289, "Suppose most people who seem endlessly patient are simply better at recognizing when patience is actually needed and when it isn't.", "Where does today actually call for patience, and where does it call for action instead?"),
        PhilosophyPrompt(290, "Consider that most meaningful conversations happen only after the easy small talk runs out.", "Is there a conversation today that could go past the small talk if you let it?"),
        PhilosophyPrompt(291, "Think about the last time you noticed that rest, done well, made you kinder the next day.", "Could rest today make tomorrow's version of you kinder?"),
        PhilosophyPrompt(292, "Imagine your recurring frustrations as requests for a boundary you haven't set yet.", "What boundary is today's frustration actually pointing toward?"),
        PhilosophyPrompt(293, "Picture the last time you noticed that being understood mattered more to you than being right.", "Which one matters more in a disagreement you're currently having?"),
        PhilosophyPrompt(294, "Suppose most growth is uncomfortable specifically because it requires giving up a version of yourself that used to work.", "What old version of yourself is today's growth asking you to release?"),
        PhilosophyPrompt(295, "Consider that most people wish they had asked more questions and offered less advice.", "Could you ask one more question today before offering the next piece of advice?"),
        PhilosophyPrompt(296, "Think about the last time doing something purely for enjoyment, with no productive purpose, actually refilled you.", "When did you last do something for enjoyment alone?"),
        PhilosophyPrompt(297, "Imagine treating your own body's signals, tiredness, hunger, tension, as information rather than inconveniences to override.", "What signal are you currently overriding?"),
        PhilosophyPrompt(298, "Picture the last time choosing to trust the process, without needing to control every step, actually worked out.", "Is there a process today that needs that same trust?"),
        PhilosophyPrompt(299, "Suppose most people remember how safe you made them feel to be honest with you, more than how impressive you seemed.", "How safe do people feel being honest with you lately?"),
        PhilosophyPrompt(300, "Consider that most days, taken alone, feel small, but a life is only ever the sum of days exactly like this one.", "What would you want this particular day to add to that sum?"),
        PhilosophyPrompt(301, "Think about the last time you noticed that being busy and being fulfilled are not the same thing.", "Which one describes most of this week so far?"),
        PhilosophyPrompt(302, "Imagine your recurring procrastination as fear wearing a disguise of laziness.", "What fear might be hiding underneath today's procrastination?"),
        PhilosophyPrompt(303, "Picture the last time you noticed real strength in someone who never called attention to it.", "Who in your life shows that quiet kind of strength?"),
        PhilosophyPrompt(304, "Suppose most people remember your consistency far more than your occasional brilliance.", "What consistent, unremarkable thing could you offer today?"),
        PhilosophyPrompt(305, "Consider that most people are harder on themselves in private than anyone would ever dare be on them in public.", "What would you say to yourself if you had to say it to your own face?"),
        PhilosophyPrompt(306, "Think about the last time embracing uncertainty, instead of resisting it, actually reduced your stress.", "Is there uncertainty today you could simply accept instead of resist?"),
        PhilosophyPrompt(307, "Imagine treating your schedule as a reflection of your actual priorities, not just your obligations.", "Does today's schedule match what you'd claim your priorities are?"),
        PhilosophyPrompt(308, "Picture the last time being wrong in public actually made people trust you more, not less.", "What did handling that moment well look like?"),
        PhilosophyPrompt(309, "Suppose most regret about relationships comes from things left unsaid, not things said too honestly.", "Is there something unsaid that deserves saying today?"),
        PhilosophyPrompt(310, "Consider that most people who seem effortlessly skilled simply put in effort where no one was watching.", "What effort are you putting in today that no one will see?"),
        PhilosophyPrompt(311, "Think about the last time a small act of courage opened a door that had seemed permanently shut.", "What small act of courage is available to you today?"),
        PhilosophyPrompt(312, "Imagine your recurring worry as a smoke alarm that's occasionally right, but often just overly sensitive.", "Is today's worry a real fire, or just sensitive wiring?"),
        PhilosophyPrompt(313, "Picture the last time you noticed that resentment mostly hurt the person carrying it, not the person it was aimed at.", "Is there a resentment today that's mostly hurting you?"),
        PhilosophyPrompt(314, "Suppose most people's definition of a good life quietly changes every few years without them noticing.", "How has your own definition changed in the last few years?"),
        PhilosophyPrompt(315, "Consider that most people appreciate directness far more than the anxious version of you assumes they will.", "Is there something today you could say directly instead of hinting at?"),
        PhilosophyPrompt(316, "Think about the last time slowing down your reaction, even by a few seconds, changed the whole outcome.", "Where could that same pause help you today?"),
        PhilosophyPrompt(317, "Imagine treating your own recovery time after a hard day as seriously as you'd treat an athlete's recovery time.", "What would real recovery look like for you tonight?"),
        PhilosophyPrompt(318, "Picture the last time you noticed that your own presence, simply showing up, mattered more than anything you said.", "Where could your presence alone matter most today?"),
        PhilosophyPrompt(319, "Suppose most people who criticize you the loudest have never actually attempted what you're attempting.", "Does that change the weight you're giving to a recent critic?"),
        PhilosophyPrompt(320, "Consider that most clarity about a hard decision comes from imagining explaining it honestly to someone you respect.", "How would you explain today's hardest decision to someone whose judgment you trust?"),
        PhilosophyPrompt(321, "Think about the last time choosing to be curious, instead of certain, actually led to a better answer.", "Where could curiosity replace certainty today?"),
        PhilosophyPrompt(322, "Imagine your recurring comparisons to others as a signal pointing toward something you actually want, not evidence that you're behind.", "What does today's comparison actually reveal you want?"),
        PhilosophyPrompt(323, "Picture the last time you noticed that being kind to a stranger changed your own mood more than theirs.", "Is there a small kindness today that could shift your own mood?"),
        PhilosophyPrompt(324, "Suppose most people remember the specific way you made time for them more than the gifts you gave them.", "Who could use some specific, undivided time from you today?"),
        PhilosophyPrompt(325, "Consider that most habits of overthinking are attempts to control outcomes that were never actually within your control.", "What outcome today are you trying to control that isn't actually yours to control?"),
        PhilosophyPrompt(326, "Think about the last time you noticed that admitting uncertainty out loud actually relieved pressure, rather than adding to it.", "Is there an uncertainty today worth admitting out loud?"),
        PhilosophyPrompt(327, "Imagine treating your own recovery from a setback as a skill you're actively building, not a personality trait you either have or don't.", "What skill of recovery are you practicing right now?"),
        PhilosophyPrompt(328, "Picture the last time you realized a habit you'd judged in someone else was one you also quietly practiced yourself.", "Is there a habit you're judging in someone else that deserves a second look at home?"),
        PhilosophyPrompt(329, "Suppose most people who seem naturally calm have simply practiced calm responses more often than dramatic ones.", "What calm response could you practice today, even if it doesn't feel natural yet?"),
        PhilosophyPrompt(330, "Consider that most meaningful change starts with a decision that looks unremarkable from the outside.", "What unremarkable decision today might actually matter more than it looks?"),
        PhilosophyPrompt(331, "Think about the last time you noticed real generosity doesn't require having extra to give.", "What could you give today, even without having extra?"),
        PhilosophyPrompt(332, "Imagine your recurring self-comparisons to your younger self as measuring the wrong things entirely.", "What would a fairer comparison to your younger self actually look like?"),
        PhilosophyPrompt(333, "Picture the last time you noticed that being told the truth, even an unflattering one, ultimately helped you more than being protected from it.", "Is there a truth you're avoiding telling someone, out of a mistaken kindness?"),
        PhilosophyPrompt(334, "Suppose most people who seem to have their lives figured out are simply better at hiding the parts still under construction.", "What part of your own life is still, honestly, under construction?"),
        PhilosophyPrompt(335, "Consider that most anxiety about the future quiets down the moment you focus on the very next small step.", "What is the very next small step available to you right now?"),
        PhilosophyPrompt(336, "Think about the last time you noticed that being patient with a slow process taught you something a quick result never could have.", "What is today's slow process quietly teaching you?"),
        PhilosophyPrompt(337, "Imagine treating your recurring doubts as questions worth actually answering, rather than noise to be silenced.", "What is today's loudest doubt actually asking you?"),
        PhilosophyPrompt(338, "Picture the last time choosing to rest, without guilt, actually made the work that followed better.", "Could resting without guilt today improve what comes next?"),
        PhilosophyPrompt(339, "Suppose most people who inspire real trust are simply the ones who follow through on small promises consistently.", "What small promise could you follow through on today?"),
        PhilosophyPrompt(340, "Consider that most people remember the tone you used far longer than the specific words you chose.", "What tone have you been using most today?"),
        PhilosophyPrompt(341, "Think about the last time you noticed that letting someone else be right didn't actually cost you anything.", "Is there a small disagreement today not worth winning?"),
        PhilosophyPrompt(342, "Imagine your recurring impatience as a signal that something in your pace, not the world's pace, needs adjusting.", "Where is today's impatience actually pointing?"),
        PhilosophyPrompt(343, "Picture the last time you noticed that a moment of real vulnerability actually deepened a relationship rather than weakening it.", "Is there a moment today that could use a little more honesty about how you actually feel?"),
        PhilosophyPrompt(344, "Suppose most people who seem endlessly capable simply ask for help earlier and more often than it appears.", "What could you ask for help with today, sooner rather than later?"),
        PhilosophyPrompt(345, "Consider that most people's biggest fears about the future never actually happen in the specific way they imagined.", "How many of your past biggest fears actually happened as imagined?"),
        PhilosophyPrompt(346, "Think about the last time you noticed that doing a hard thing early in the day made the rest of it feel lighter.", "Is there a hard thing today worth doing first?"),
        PhilosophyPrompt(347, "Imagine treating your own mistakes the way a good teacher treats a student's mistakes, as data, not verdicts.", "What mistake today could use that same framing?"),
        PhilosophyPrompt(348, "Picture the last time you noticed that real connection often happens in unplanned, unscheduled moments.", "Is there room for an unplanned moment today?"),
        PhilosophyPrompt(349, "Suppose most people who seem confident under pressure simply practiced staying calm in smaller pressures first.", "What smaller pressure today could be practice for a bigger one later?"),
        PhilosophyPrompt(350, "Consider that most people carry more courage than they give themselves credit for, simply because they've never needed to prove it yet.", "What untested courage might you actually be carrying right now?"),
        PhilosophyPrompt(351, "Think about the last time choosing gratitude over frustration, even briefly, actually shifted how the rest of the day unfolded.", "Is there something today worth choosing gratitude over frustration for?"),
        PhilosophyPrompt(352, "Imagine your recurring need for control as an attempt to feel safe, rather than a character flaw.", "What would feeling safe today look like without needing full control?"),
        PhilosophyPrompt(353, "Picture the last time you noticed that being fully present with one person mattered more than being available to everyone.", "Who deserves your full presence today, even briefly?"),
        PhilosophyPrompt(354, "Suppose most people who seem to handle change well simply practiced letting go of smaller things first.", "What smaller thing could you practice letting go of today?"),
        PhilosophyPrompt(355, "Consider that most people who seem endlessly optimistic have simply trained themselves to notice the good details more than the bad ones.", "What good detail have you noticed today that almost slipped past unnoticed?"),
        PhilosophyPrompt(356, "Think about the last time slowing your breathing, on purpose, actually changed how a hard moment felt.", "Could that same small tool help with something today?"),
        PhilosophyPrompt(357, "Imagine treating today as a rough draft rather than a final version, allowed to be revised as you go.", "What part of today could use a small revision, starting right now?"),
        PhilosophyPrompt(358, "Picture the last time you noticed that being understood by even one person was enough to get you through a hard week.", "Who has been that one person for you lately, and have you thanked them?"),
        PhilosophyPrompt(359, "Suppose most growth is quiet and slow enough that it only becomes visible when you stop and actually look back.", "What would you see if you looked back at just the last month?"),
        PhilosophyPrompt(360, "Consider that most good days start with one small, deliberate choice, not with everything falling perfectly into place.", "What is today's one small, deliberate choice going to be?"),
    )
}
