package com.tyshi00.trinkets

/**
 * Reflection prompts: open questions meant to be sat with rather than answered
 * quickly. Adapted from the Light Phone "Reflect" tool.
 *
 * The source tool grouped these into nine categories with a filter screen.
 * Trinkets draws from the whole pool instead, so the category field is dropped.
 */
data class ReflectionPrompt(
    val id: Int,
    val text: String,
)

object TrinketsReflectionPrompts {
    val ALL: List<ReflectionPrompt> = listOf(
        ReflectionPrompt(1, "What made you smile today?"),
        ReflectionPrompt(2, "What's one thing you're grateful for right now?"),
        ReflectionPrompt(3, "What's a small comfort you're grateful for today?"),
        ReflectionPrompt(4, "Who is someone you haven't thanked in a while?"),
        ReflectionPrompt(5, "What part of your routine are you quietly grateful for?"),
        ReflectionPrompt(6, "What's something your body did for you today that you're thankful for?"),
        ReflectionPrompt(7, "What's a place that you're grateful exists?"),
        ReflectionPrompt(8, "What's a small win you had today?"),
        ReflectionPrompt(9, "What are you proud of this week?"),
        ReflectionPrompt(10, "What's something you did today that you'd overlook if no one asked?"),
        ReflectionPrompt(11, "What's a version of \"success\" that has nothing to do with achievement?"),
        ReflectionPrompt(12, "What's something you got a little better at this year?"),
        ReflectionPrompt(13, "What's a risk you're glad you took?"),
        ReflectionPrompt(14, "What's something you finished, even if it was small?"),
        ReflectionPrompt(15, "Describe a moment today when you felt at ease."),
        ReflectionPrompt(16, "What's something you're looking forward to?"),
        ReflectionPrompt(17, "What's bringing you peace lately?"),
        ReflectionPrompt(18, "What are you doing right now without really noticing it?"),
        ReflectionPrompt(19, "What's one thing you can do today, slowly, on purpose?"),
        ReflectionPrompt(20, "Where is your attention right now, and where do you want it to be?"),
        ReflectionPrompt(21, "What would it look like to do the next hour intentionally?"),
        ReflectionPrompt(22, "What's a habit you do on autopilot that you'd like to notice more?"),
        ReflectionPrompt(23, "What does \"being present\" feel like in your body right now?"),
        ReflectionPrompt(24, "What's one small thing you could do today just for the sake of doing it well?"),
        ReflectionPrompt(25, "What are three things you can notice right now: see, hear, feel?"),
        ReflectionPrompt(26, "Who made a difference in your day, and how?"),
        ReflectionPrompt(27, "Who do you want to check in with this week?"),
        ReflectionPrompt(28, "What's a quality in someone else that you admire?"),
        ReflectionPrompt(29, "What's something you appreciate about the people closest to you?"),
        ReflectionPrompt(30, "Who has believed in you when it mattered?"),
        ReflectionPrompt(31, "What's a relationship in your life that's changed for the better?"),
        ReflectionPrompt(32, "Who would you like to know better?"),
        ReflectionPrompt(33, "What's weighing on your mind right now?"),
        ReflectionPrompt(34, "What would make tomorrow a good day?"),
        ReflectionPrompt(35, "What did you learn about yourself today?"),
        ReflectionPrompt(36, "Where did you notice beauty today?"),
        ReflectionPrompt(37, "What's a small detail in your surroundings you've never noticed before?"),
        ReflectionPrompt(38, "What color showed up the most in your day today?"),
        ReflectionPrompt(39, "What's something ordinary that felt beautiful today?"),
        ReflectionPrompt(40, "What sound do you want to remember from today?"),
        ReflectionPrompt(41, "What's something in nature you noticed recently?"),
        ReflectionPrompt(42, "What do you need more of in your life right now?"),
        ReflectionPrompt(43, "What's something you'd like to let go of?"),
        ReflectionPrompt(44, "What's a story about yourself that you're ready to update?"),
        ReflectionPrompt(45, "What's something you're holding onto out of habit, not need?"),
        ReflectionPrompt(46, "What would it feel like to forgive yourself for something small?"),
        ReflectionPrompt(47, "What's a comparison you could let go of?"),
        ReflectionPrompt(48, "What's an expectation, yours or someone else's, that you could release?"),
        ReflectionPrompt(49, "What's something from today you can leave in today?"),
        ReflectionPrompt(50, "What conversation stuck with you today?"),
        ReflectionPrompt(51, "What's one thing you want to remember about today?"),
        ReflectionPrompt(52, "What would you tell a friend who had your day?"),
        ReflectionPrompt(53, "What's a memory that's been on your mind lately?"),
        ReflectionPrompt(54, "What's a challenge you handled well recently?"),
        ReflectionPrompt(55, "What's something difficult that taught you something useful?"),
        ReflectionPrompt(56, "What's a fear you're slowly becoming less afraid of?"),
        ReflectionPrompt(57, "What's a mistake that turned out to matter less than you thought?"),
        ReflectionPrompt(58, "What's something you're better at than you give yourself credit for?"),
        ReflectionPrompt(59, "What's a hard conversation you're glad you had?"),
        ReflectionPrompt(60, "What feels stuck right now, and what's one small step forward?"),
        ReflectionPrompt(61, "When you feel stuck, what usually helps you move again?"),
        ReflectionPrompt(62, "What's something you've been putting off, and why?"),
        ReflectionPrompt(63, "What would you do today if you weren't afraid of getting it wrong?"),
        ReflectionPrompt(64, "What's one thing outside your control that you're trying to control?"),
        ReflectionPrompt(65, "What's a decision you've been avoiding?"),
        ReflectionPrompt(66, "If you gave yourself permission to start messy, what would you begin?"),
        ReflectionPrompt(67, "What's the smallest possible next step you could take today?"),
        ReflectionPrompt(68, "How did you take care of yourself today?"),
        ReflectionPrompt(69, "What does your body need from you today?"),
        ReflectionPrompt(70, "What's one boundary you could set today?"),
        ReflectionPrompt(71, "What's something kind you could say to yourself right now?"),
        ReflectionPrompt(72, "When did you last rest without feeling guilty about it?"),
        ReflectionPrompt(73, "What's a form of care that doesn't cost anything?"),
        ReflectionPrompt(74, "What would \"enough\" look like for you today?"),
        ReflectionPrompt(75, "What's a childhood memory that still makes you smile?"),
        ReflectionPrompt(76, "What's a memory you wish you could relive for a day?"),
        ReflectionPrompt(77, "Who from your past do you think about most often?"),
        ReflectionPrompt(78, "What's a smell or song that instantly takes you back to a memory?"),
        ReflectionPrompt(79, "What's the earliest memory you can recall?"),
        ReflectionPrompt(80, "What's a memory that shaped who you are today?"),
        ReflectionPrompt(81, "What's a trip or place you'll never forget?"),
        ReflectionPrompt(82, "What's a memory with someone you've lost touch with?"),
        ReflectionPrompt(83, "What's on your mind that you haven't said out loud?"),
        ReflectionPrompt(84, "What's something you're worried about that might not even happen?"),
        ReflectionPrompt(85, "What helps your body feel calmer when you're anxious?"),
        ReflectionPrompt(86, "What's one thing within your control today?"),
        ReflectionPrompt(87, "What's a worry you can set down, at least for tonight?"),
        ReflectionPrompt(88, "What does calm feel like in your body?"),
        ReflectionPrompt(89, "What's something true you can remind yourself when you're anxious?"),
        ReflectionPrompt(90, "Who or what makes you feel safe?"),
        ReflectionPrompt(91, "Look at the last picture you took. What memory does it bring back?"),
        ReflectionPrompt(92, "What's the story behind the last photo you took?"),
        ReflectionPrompt(93, "If you took a photo of today, what would it be of?"),
        ReflectionPrompt(94, "Find an old photo on your phone. What do you remember about that day?"),
    )
}
