package com.tyshi00.trinkets

// Real historical events, described in original wording, chosen deliberately
// to span Africa, Asia, the Americas, Europe, and Oceania rather than
// skewing toward any one region. See docs/CONTENT.md for how to keep
// growing this bucket toward full year-round coverage.
object TrinketsHistoryFacts {
    val ALL: List<HistoryFact> = listOf(
        HistoryFact(1, 1, 1, 1804, "Caribbean", "Haiti declared its independence from France, becoming the world's first nation founded by a successful slave revolt."),
        HistoryFact(2, 1, 1, 1959, "Caribbean", "Fidel Castro's forces entered Havana as the Cuban government of Fulgencio Batista collapsed."),
        HistoryFact(3, 1, 26, 1950, "Asia", "India adopted its constitution and became a republic, an event now marked annually as Republic Day."),
        HistoryFact(4, 2, 4, 1948, "Asia", "Sri Lanka (then Ceylon) gained independence from British colonial rule."),
        HistoryFact(5, 2, 11, 1990, "Africa", "Nelson Mandela was released from prison in South Africa after 27 years."),
        HistoryFact(6, 2, 15, 1898, "Caribbean", "The USS Maine exploded in Havana Harbor, an event that helped trigger the Spanish-American War."),
        HistoryFact(7, 3, 1, 1932, "North America", "The Empire State Building's radio tower was completed, though the building itself had opened months earlier."),
        HistoryFact(8, 3, 3, 1990, "Europe", "Namibia became fully independent from South African administration."),
        HistoryFact(9, 3, 6, 1957, "Africa", "Ghana became the first sub-Saharan African colony to gain independence from European colonial rule."),
        HistoryFact(10, 3, 8, 1917, "Europe", "Demonstrations in Petrograd (present-day St. Petersburg) marking International Women's Day helped ignite the February Revolution in Russia."),
        HistoryFact(11, 3, 11, 2011, "Asia", "A magnitude 9.0 earthquake and tsunami struck the Tohoku region of Japan, one of the most powerful earthquakes ever recorded."),
        HistoryFact(12, 3, 17, 1992, "Africa", "A whites-only referendum in South Africa approved ending apartheid-era rule."),
        HistoryFact(13, 3, 21, 1960, "Africa", "The Sharpeville massacre in South Africa became a turning point in the international movement against apartheid."),
        HistoryFact(14, 3, 21, 1990, "Africa", "Namibia's independence was formally celebrated, ending decades of South African administration."),
        HistoryFact(15, 3, 25, 1821, "Europe", "Greece began its war of independence from the Ottoman Empire, an anniversary still celebrated as Greek Independence Day."),
        HistoryFact(16, 3, 26, 1971, "Asia", "Bangladesh declared independence from Pakistan."),
        HistoryFact(17, 4, 4, 1968, "North America", "Civil rights leader Martin Luther King Jr. was assassinated in Memphis, Tennessee."),
        HistoryFact(18, 4, 6, 1994, "Africa", "A plane crash killing the presidents of Rwanda and Burundi helped trigger the Rwandan genocide."),
        HistoryFact(19, 4, 7, 1994, "Africa", "The Rwandan genocide began, ultimately claiming an estimated 800,000 lives over roughly 100 days."),
        HistoryFact(20, 4, 18, 1980, "Africa", "Zimbabwe gained formal independence, ending white minority rule in Rhodesia."),
        HistoryFact(21, 4, 27, 1994, "Africa", "South Africa held its first fully democratic election, with citizens of all races voting for the first time."),
        HistoryFact(22, 5, 5, 1862, "North America", "Mexican forces defeated the French army at the Battle of Puebla, the origin of the Cinco de Mayo holiday."),
        HistoryFact(23, 5, 8, 1945, "Europe", "Victory in Europe (V-E) Day marked the formal end of World War II fighting in Europe."),
        HistoryFact(24, 5, 14, 1948, "Middle East", "The State of Israel was declared, hours before the expiration of the British Mandate for Palestine."),
        HistoryFact(25, 5, 25, 1963, "Africa", "The Organisation of African Unity, a precursor to the African Union, was founded in Addis Ababa, Ethiopia."),
        HistoryFact(26, 5, 25, 2020, "North America", "The killing of George Floyd in Minneapolis sparked a wave of protests against police violence across the United States and around the world."),
        HistoryFact(27, 6, 4, 1989, "Asia", "Chinese authorities forcibly cleared Tiananmen Square in Beijing, ending weeks of pro-democracy demonstrations."),
        HistoryFact(28, 6, 5, 1967, "Middle East", "The Six-Day War began between Israel and a coalition of Arab states."),
        HistoryFact(29, 6, 16, 1976, "Africa", "Students in Soweto, South Africa, marched to protest a policy requiring instruction in Afrikaans, a turning point in the anti-apartheid struggle."),
        HistoryFact(30, 6, 20, 1837, "Europe", "Victoria became Queen of the United Kingdom at the age of 18, beginning a 63-year reign."),
        HistoryFact(31, 6, 26, 1945, "North America", "Delegates from 50 countries signed the United Nations Charter in San Francisco."),
        HistoryFact(32, 7, 1, 1867, "North America", "The British North America Act took effect, creating the Dominion of Canada."),
        HistoryFact(33, 7, 4, 1776, "North America", "The United States formally adopted the Declaration of Independence."),
        HistoryFact(34, 7, 5, 1962, "Africa", "Algeria gained independence from France after an eight-year war."),
        HistoryFact(35, 7, 6, 1885, "Europe", "French chemist Louis Pasteur successfully tested his rabies vaccine on a human patient for the first time."),
        HistoryFact(36, 7, 9, 1816, "South America", "Argentina declared its independence from Spain."),
        HistoryFact(37, 7, 14, 1789, "Europe", "Parisians stormed the Bastille fortress, a flashpoint that helped ignite the French Revolution."),
        HistoryFact(38, 7, 20, 1969, "Global", "Apollo 11 astronauts Neil Armstrong and Buzz Aldrin became the first humans to walk on the Moon."),
        HistoryFact(39, 7, 26, 1953, "Caribbean", "A rebel attack on the Moncada Barracks in Cuba, led by Fidel Castro, is commemorated as the start of the Cuban Revolution."),
        HistoryFact(40, 8, 6, 1945, "Asia", "The United States dropped an atomic bomb on Hiroshima, Japan, during the closing days of World War II."),
        HistoryFact(41, 8, 9, 1965, "Asia", "Singapore became an independent nation after separating from Malaysia."),
        HistoryFact(42, 8, 14, 1947, "Asia", "Pakistan gained independence from British colonial rule."),
        HistoryFact(43, 8, 15, 1947, "Asia", "India gained independence from British colonial rule after nearly two centuries."),
        HistoryFact(44, 8, 17, 1945, "Asia", "Indonesia proclaimed its independence from Dutch colonial rule."),
        HistoryFact(45, 8, 24, 79, "Europe", "Mount Vesuvius erupted, burying the Roman city of Pompeii in volcanic ash."),
        HistoryFact(46, 9, 2, 1945, "Asia", "Japan formally surrendered aboard the USS Missouri, marking the end of World War II."),
        HistoryFact(47, 9, 7, 1822, "South America", "Brazil declared its independence from Portugal."),
        HistoryFact(48, 9, 15, 1821, "Central America", "Costa Rica, El Salvador, Guatemala, Honduras, and Nicaragua jointly declared independence from Spain."),
        HistoryFact(49, 9, 16, 1810, "North America", "Mexico's independence movement began with the Grito de Dolores, a call to arms against Spanish rule."),
        HistoryFact(50, 9, 16, 1975, "Africa", "Papua New Guinea gained independence from Australian administration."),
        HistoryFact(51, 9, 21, 1964, "Africa", "Malta gained independence from the United Kingdom."),
        HistoryFact(52, 9, 24, 1960, "Africa", "Guinea-Bissau's independence movement gained global attention as African decolonization accelerated across the continent."),
        HistoryFact(53, 10, 1, 1949, "Asia", "The People's Republic of China was formally proclaimed in Beijing."),
        HistoryFact(54, 10, 1, 1960, "Africa", "Nigeria gained independence from British colonial rule, becoming Africa's most populous nation."),
        HistoryFact(55, 10, 2, 1869, "Asia", "Mohandas Gandhi, who would go on to lead India's independence movement through nonviolent resistance, was born in Porbandar."),
        HistoryFact(56, 10, 9, 2006, "Asia", "North Korea conducted its first announced nuclear weapons test."),
        HistoryFact(57, 10, 24, 1945, "Global", "The United Nations officially came into existence after its charter was ratified by the required number of countries."),
        HistoryFact(58, 11, 9, 1989, "Europe", "The Berlin Wall fell, as East German authorities opened checkpoints after weeks of mass protests."),
        HistoryFact(59, 11, 11, 1975, "Africa", "Angola declared independence from Portugal after a long colonial war."),
        HistoryFact(60, 11, 18, 1918, "Europe", "Latvia declared its independence amid the collapse of the Russian and German empires at the end of World War I."),
        HistoryFact(61, 11, 28, 1912, "Europe", "Albania declared independence from the Ottoman Empire."),
        HistoryFact(62, 12, 1, 1955, "North America", "Rosa Parks refused to give up her bus seat in Montgomery, Alabama, helping spark the modern American civil rights movement."),
        HistoryFact(63, 12, 2, 1971, "Middle East", "The United Arab Emirates was formed through the union of several small emirates."),
        HistoryFact(64, 12, 10, 1948, "Global", "The United Nations General Assembly adopted the Universal Declaration of Human Rights."),
        HistoryFact(65, 12, 16, 1971, "Asia", "The Bangladesh Liberation War ended with the surrender of Pakistani forces, securing Bangladeshi independence."),
        HistoryFact(66, 12, 25, 1991, "Europe", "Mikhail Gorbachev resigned as president of the Soviet Union, which formally dissolved the following day."),
        HistoryFact(67, 1, 15, 1929, "North America", "Civil rights leader Martin Luther King Jr. was born in Atlanta, Georgia."),
        HistoryFact(68, 1, 20, 1961, "North America", "John F. Kennedy was inaugurated as the 35th President of the United States."),
        HistoryFact(69, 1, 28, 1986, "North America", "The Space Shuttle Challenger broke apart shortly after launch, killing all seven crew members."),
        HistoryFact(70, 2, 4, 2004, "North America", "Facebook, which would grow into one of the world's largest social media platforms, was launched from a Harvard dormitory."),
        HistoryFact(71, 2, 20, 1962, "North America", "John Glenn became the first American to orbit the Earth."),
        HistoryFact(72, 2, 24, 1582, "Europe", "Pope Gregory XIII introduced the Gregorian calendar, now the most widely used civil calendar in the world."),
        HistoryFact(73, 3, 10, 1876, "North America", "Alexander Graham Bell made the first successful telephone call, famously summoning his assistant."),
        HistoryFact(74, 3, 14, 1879, "Europe", "Physicist Albert Einstein, whose work would transform modern physics, was born in Ulm, Germany."),
        HistoryFact(75, 3, 30, 1867, "North America", "The United States agreed to purchase Alaska from Russia."),
        HistoryFact(76, 4, 12, 1961, "Asia", "Soviet cosmonaut Yuri Gagarin became the first human to travel into space."),
        HistoryFact(77, 4, 22, 1970, "Global", "The first Earth Day was observed, helping launch the modern environmental movement."),
        HistoryFact(78, 5, 1, 1931, "North America", "The Empire State Building officially opened in New York City."),
        HistoryFact(79, 5, 29, 1953, "Asia", "Tenzing Norgay of Nepal and Edmund Hillary of New Zealand became the first climbers confirmed to reach the summit of Mount Everest."),
        HistoryFact(80, 6, 12, 1964, "Africa", "Nelson Mandela was sentenced to life imprisonment in South Africa for his role opposing apartheid."),
        HistoryFact(81, 6, 15, 1215, "Europe", "England's King John sealed the Magna Carta, an early milestone in limiting royal power under law."),
        HistoryFact(82, 7, 2, 1937, "Oceania", "Aviator Amelia Earhart disappeared over the Pacific Ocean during an attempt to fly around the world."),
        HistoryFact(83, 8, 28, 1963, "North America", "Martin Luther King Jr. delivered his 'I Have a Dream' speech during the March on Washington."),
        HistoryFact(84, 9, 26, 1983, "Europe", "A Soviet early-warning system falsely signaled an incoming nuclear attack; officer Stanislav Petrov's judgment that it was a false alarm is widely credited with averting catastrophe."),
        HistoryFact(85, 10, 14, 1947, "North America", "Test pilot Chuck Yeager became the first person confirmed to fly faster than the speed of sound."),
        HistoryFact(86, 11, 20, 1945, "Europe", "The Nuremberg trials began, prosecuting senior Nazi officials for war crimes after World War II."),
        HistoryFact(87, 12, 17, 1903, "North America", "Orville and Wilbur Wright achieved the first sustained, controlled flight of a powered aircraft near Kitty Hawk, North Carolina."),
        HistoryFact(88, 1, 3, 1959, "North America", "Alaska was admitted as the 49th U.S. state."),
        HistoryFact(89, 1, 27, 1945, "Europe", "Soviet troops liberated the Auschwitz concentration camp, an event now marked internationally as Holocaust Remembrance Day."),
        HistoryFact(90, 2, 21, 1965, "North America", "Civil rights activist Malcolm X was assassinated in New York City."),
        HistoryFact(91, 3, 15, 44, "Europe", "Roman dictator Julius Caesar was assassinated by a group of senators."),
        HistoryFact(92, 4, 9, 1865, "North America", "Confederate General Robert E. Lee surrendered to Union General Ulysses S. Grant, effectively ending the American Civil War."),
        HistoryFact(93, 5, 8, 1886, "North America", "Pharmacist John Pemberton first sold his new soft drink, Coca-Cola, in Atlanta, Georgia."),
        HistoryFact(94, 6, 28, 1914, "Europe", "The assassination of Archduke Franz Ferdinand in Sarajevo set off the chain of events leading to World War I."),
        HistoryFact(95, 8, 1, 1834, "Caribbean", "Slavery was formally abolished across the British Empire, freeing enslaved people across the Caribbean and elsewhere."),
        HistoryFact(96, 9, 8, 1966, "North America", "The television series Star Trek premiered, later becoming a defining piece of science fiction culture."),
        HistoryFact(97, 11, 22, 1963, "North America", "U.S. President John F. Kennedy was assassinated in Dallas, Texas."),
        HistoryFact(98, 12, 7, 1941, "Asia", "Japanese forces attacked the U.S. naval base at Pearl Harbor, Hawaii, drawing the United States into World War II."),
        HistoryFact(99, 12, 21, 1988, "Europe", "A bomb destroyed Pan Am Flight 103 over Lockerbie, Scotland, killing everyone aboard and several people on the ground."),
        HistoryFact(100, 2, 6, 1952, "Europe", "Elizabeth II became Queen of the United Kingdom upon the death of her father, King George VI."),
        HistoryFact(101, 3, 12, 1930, "Asia", "Mohandas Gandhi began the Salt March, a 240-mile protest walk against British salt taxes in colonial India."),
        HistoryFact(102, 4, 26, 1986, "Europe", "A reactor at the Chernobyl Nuclear Power Plant in Soviet Ukraine exploded, causing the worst nuclear accident in history."),
        HistoryFact(103, 5, 18, 1980, "Asia", "China conducted its first successful test launch of an intercontinental ballistic missile into the Pacific Ocean."),
        HistoryFact(104, 6, 6, 1944, "Europe", "Allied forces landed on the beaches of Normandy, France, in the D-Day invasion of World War II."),
        HistoryFact(105, 7, 17, 1955, "North America", "Disneyland opened to the public in Anaheim, California."),
        HistoryFact(106, 8, 12, 30, "Africa", "Cleopatra, the last active ruler of the Ptolemaic Kingdom of Egypt, is traditionally said to have died around this time, ending the Hellenistic period in Egypt."),
        HistoryFact(107, 9, 11, 2001, "North America", "Coordinated terrorist attacks destroyed the World Trade Center towers in New York City and struck the Pentagon."),
        HistoryFact(108, 10, 3, 1990, "Europe", "East and West Germany formally reunified into a single nation after decades of Cold War division."),
        HistoryFact(109, 11, 4, 2008, "North America", "Barack Obama was elected as the first African American president of the United States."),
        HistoryFact(110, 12, 26, 2004, "Asia", "A massive earthquake off Sumatra, Indonesia, triggered a tsunami across the Indian Ocean that killed roughly 230,000 people in over a dozen countries."),
        HistoryFact(111, 1, 8, 1935, "North America", "Musician Elvis Presley, who would help popularize rock and roll worldwide, was born in Tupelo, Mississippi."),
        HistoryFact(112, 2, 27, 1991, "Middle East", "The Gulf War ended after coalition forces liberated Kuwait from Iraqi occupation."),
        HistoryFact(113, 3, 23, 1956, "Asia", "Pakistan became an Islamic republic, adopting its first constitution."),
        HistoryFact(114, 4, 14, 1912, "Global", "The RMS Titanic struck an iceberg in the North Atlantic and sank in the early hours of the following day."),
        HistoryFact(115, 5, 6, 1954, "Europe", "British runner Roger Bannister became the first person recorded to run a mile in under four minutes."),
        HistoryFact(116, 6, 23, 1868, "North America", "Christopher Latham Sholes patented an early practical version of the typewriter."),
        HistoryFact(117, 7, 27, 1953, "Asia", "An armistice ended active fighting in the Korean War, though a formal peace treaty was never signed."),
        HistoryFact(118, 8, 19, 1839, "Europe", "The French government publicly announced the daguerreotype photographic process, making it freely available to the world."),
        HistoryFact(119, 9, 25, 1980, "Middle East", "Iraq launched a full invasion of Iran, beginning the eight-year Iran-Iraq War."),
        HistoryFact(120, 1, 2, 1959, "Global", "The Soviet Union launched Luna 1, the first spacecraft to leave Earth's orbit."),
        HistoryFact(121, 1, 6, 1912, "Europe", "Alfred Wegener first proposed his theory of continental drift in a public lecture."),
        HistoryFact(122, 1, 9, 1972, "Asia", "The RMS Queen Elizabeth ocean liner was destroyed by fire in Hong Kong harbor."),
        HistoryFact(123, 1, 12, 1866, "Europe", "The Royal Aeronautical Society was founded in London, one of the world's first aviation organizations."),
        HistoryFact(124, 1, 16, 1920, "Global", "The League of Nations, a precursor to the United Nations, held its first council meeting in Paris."),
        HistoryFact(125, 1, 18, 1871, "Europe", "The German Empire was proclaimed at the Palace of Versailles, unifying a collection of German states."),
        HistoryFact(126, 1, 20, 1887, "North America", "The United States Senate approved an agreement to lease Pearl Harbor in Hawaii as a naval base."),
        HistoryFact(127, 1, 23, 1556, "Asia", "The Shaanxi earthquake struck China, remaining the deadliest earthquake in recorded history."),
        HistoryFact(128, 1, 25, 1959, "North America", "American Airlines Flight 1 introduced commercial jet service between New York and Los Angeles."),
        HistoryFact(129, 1, 31, 1958, "North America", "The United States launched Explorer 1, its first satellite, into orbit."),
        HistoryFact(130, 2, 1, 1979, "Middle East", "Ayatollah Ruhollah Khomeini returned to Iran after years in exile, a pivotal moment in the Iranian Revolution."),
        HistoryFact(131, 2, 3, 1959, "North America", "Musicians Buddy Holly, Ritchie Valens, and The Big Bopper died in a plane crash, later remembered as The Day the Music Died."),
        HistoryFact(132, 2, 7, 1974, "Caribbean", "Grenada gained independence from the United Kingdom."),
        HistoryFact(133, 2, 9, 1964, "North America", "The Beatles made their first live American television appearance on The Ed Sullivan Show."),
        HistoryFact(134, 2, 10, 1996, "Global", "IBM's Deep Blue computer defeated world chess champion Garry Kasparov in a single game for the first time under standard rules."),
        HistoryFact(135, 2, 12, 1809, "North America", "Abraham Lincoln, who would later serve as the 16th U.S. President, was born in Kentucky."),
        HistoryFact(136, 2, 18, 1930, "North America", "Astronomer Clyde Tombaugh discovered Pluto at the Lowell Observatory in Arizona."),
        HistoryFact(137, 2, 21, 1848, "Europe", "Karl Marx and Friedrich Engels published The Communist Manifesto."),
        HistoryFact(138, 2, 22, 1979, "Caribbean", "Saint Lucia gained independence from the United Kingdom."),
        HistoryFact(139, 2, 25, 1986, "Asia", "The People Power Revolution in the Philippines forced President Ferdinand Marcos from office."),
        HistoryFact(140, 3, 2, 1969, "Europe", "The first Concorde supersonic passenger jet completed its maiden test flight in France."),
        HistoryFact(141, 3, 4, 1789, "North America", "The United States Constitution officially took effect."),
        HistoryFact(142, 3, 9, 1959, "North America", "The Barbie doll debuted at the American International Toy Fair in New York."),
        HistoryFact(143, 3, 12, 1912, "North America", "The Girl Scouts of the USA was founded in Savannah, Georgia."),
        HistoryFact(144, 3, 13, 1930, "Global", "The discovery of Pluto was formally announced to the public."),
        HistoryFact(145, 3, 15, 1990, "Europe", "Mikhail Gorbachev was elected the first and only President of the Soviet Union by its Congress of People's Deputies."),
        HistoryFact(146, 3, 16, 1968, "Asia", "American soldiers killed hundreds of unarmed villagers in the My Lai massacre during the Vietnam War."),
        HistoryFact(147, 3, 20, 1815, "Europe", "Napoleon Bonaparte returned to Paris, beginning the period known as the Hundred Days after his escape from exile."),
        HistoryFact(148, 3, 23, 1919, "Europe", "Benito Mussolini founded the Fascist movement in Italy."),
        HistoryFact(149, 3, 29, 1973, "Asia", "The last United States combat troops departed Vietnam, formally ending direct American military involvement."),
        HistoryFact(150, 4, 1, 1976, "North America", "Apple Computer was founded by Steve Jobs, Steve Wozniak, and Ronald Wayne in California."),
        HistoryFact(151, 4, 3, 1948, "Global", "The Marshall Plan was enacted, providing U.S. economic assistance to help rebuild Western Europe after World War II."),
        HistoryFact(152, 4, 6, 1896, "Europe", "The first modern Olympic Games opened in Athens, Greece."),
        HistoryFact(153, 4, 12, 1955, "North America", "The polio vaccine developed by Jonas Salk was declared safe and effective."),
        HistoryFact(154, 4, 15, 1912, "Global", "The RMS Titanic sank in the early hours of this date after striking an iceberg the night before."),
        HistoryFact(155, 4, 19, 1775, "North America", "Fighting broke out at Lexington and Concord, marking the start of the American Revolutionary War."),
        HistoryFact(156, 4, 21, 753, "Europe", "According to tradition, the city of Rome was founded on this date."),
        HistoryFact(157, 4, 23, 1616, "Europe", "William Shakespeare, one of the most influential writers in the English language, died in Stratford-upon-Avon."),
        HistoryFact(158, 4, 26, 1964, "Africa", "Tanganyika and Zanzibar merged to form the United Republic of Tanzania."),
        HistoryFact(159, 4, 29, 1992, "North America", "Riots broke out in Los Angeles following the acquittal of police officers in the beating of Rodney King."),
        HistoryFact(160, 5, 1, 1886, "North America", "Labor demonstrations across the United States, centered in Chicago, helped establish the origins of May Day as a workers' holiday."),
        HistoryFact(161, 5, 6, 1937, "North America", "The airship Hindenburg caught fire and was destroyed while attempting to dock in New Jersey."),
        HistoryFact(162, 5, 9, 1950, "Europe", "French foreign minister Robert Schuman proposed the plan that would evolve into the European Union."),
        HistoryFact(163, 5, 12, 1949, "Europe", "The Soviet Union lifted its blockade of West Berlin, ending a crisis that had lasted nearly a year."),
        HistoryFact(164, 5, 15, 1948, "Middle East", "War broke out between Israel and neighboring Arab states the day after Israel's declaration of independence."),
        HistoryFact(165, 5, 21, 1980, "Africa", "South African anti-apartheid activists faced increasing international sanctions as global protests intensified."),
        HistoryFact(166, 5, 24, 1844, "North America", "Samuel Morse sent the first long distance telegraph message, reading What hath God wrought."),
        HistoryFact(167, 5, 30, 1431, "Europe", "Joan of Arc was executed in Rouen, France."),
        HistoryFact(168, 6, 1, 1980, "North America", "The Cable News Network, CNN, launched as the first 24 hour television news channel."),
        HistoryFact(169, 6, 3, 1965, "North America", "Astronaut Ed White performed the first American spacewalk during the Gemini 4 mission."),
        HistoryFact(170, 6, 8, 632, "Middle East", "The Prophet Muhammad died in Medina, in present day Saudi Arabia."),
        HistoryFact(171, 6, 10, 1940, "Europe", "Italy declared war on France and the United Kingdom, entering World War II."),
        HistoryFact(172, 6, 13, 1966, "North America", "The United States Supreme Court decided Miranda v. Arizona, establishing the requirement to inform suspects of their legal rights."),
        HistoryFact(173, 6, 17, 1885, "North America", "The Statue of Liberty arrived in New York Harbor aboard a French ship."),
        HistoryFact(174, 6, 19, 1865, "North America", "Enslaved people in Texas learned of their freedom, an event now commemorated as Juneteenth."),
        HistoryFact(175, 6, 21, 1989, "North America", "The United States Supreme Court ruled that burning the American flag was a form of protected free speech."),
        HistoryFact(176, 6, 23, 1912, "North America", "Delegates opened the Progressive Party convention in Chicago, backing Theodore Roosevelt for a return to the presidency."),
        HistoryFact(177, 6, 27, 1950, "Global", "The United Nations Security Council voted to send military assistance to South Korea following the outbreak of the Korean War."),
        HistoryFact(178, 6, 30, 1908, "Asia", "A massive explosion, later called the Tunguska event, flattened an enormous area of Siberian forest."),
        HistoryFact(179, 7, 1, 1997, "Asia", "The United Kingdom transferred sovereignty of Hong Kong back to China."),
        HistoryFact(180, 7, 3, 1988, "Middle East", "A United States Navy warship mistakenly shot down an Iranian passenger jet, killing everyone aboard."),
        HistoryFact(181, 7, 6, 1957, "Europe", "Althea Gibson became the first Black athlete to win the Wimbledon tennis championship."),
        HistoryFact(182, 7, 8, 1889, "North America", "The Wall Street Journal published its first issue."),
        HistoryFact(183, 7, 11, 1804, "North America", "U.S. Vice President Aaron Burr fatally wounded former Treasury Secretary Alexander Hamilton in a duel."),
        HistoryFact(184, 7, 13, 1930, "South America", "The first FIFA World Cup began in Uruguay."),
        HistoryFact(185, 7, 15, 1965, "North America", "The Mariner 4 spacecraft transmitted the first close up images of Mars back to Earth."),
        HistoryFact(186, 7, 16, 1945, "North America", "The United States conducted the first successful test of a nuclear weapon in the New Mexico desert."),
        HistoryFact(187, 7, 18, 1976, "Global", "Romanian gymnast Nadia Comaneci scored the first perfect ten in Olympic gymnastics history at the Montreal Games."),
        HistoryFact(188, 7, 19, 1900, "Europe", "The first line of the Paris Metro opened to the public."),
        HistoryFact(189, 7, 21, 1925, "North America", "The Scopes Monkey Trial concluded in Tennessee, a landmark case concerning the teaching of evolution in public schools."),
        HistoryFact(190, 7, 23, 1962, "Global", "The Telstar satellite relayed the first live transatlantic television broadcast."),
        HistoryFact(191, 7, 27, 1866, "Global", "The first successful permanent transatlantic telegraph cable was completed."),
        HistoryFact(192, 7, 29, 1958, "North America", "The United States created NASA, its national space agency."),
        HistoryFact(193, 7, 30, 1930, "South America", "Uruguay defeated Argentina to win the first FIFA World Cup final."),
        HistoryFact(194, 8, 3, 1492, "Europe", "Christopher Columbus departed Spain on the voyage that would lead to European contact with the Americas."),
        HistoryFact(195, 8, 4, 1944, "Europe", "Diarist Anne Frank and her family were arrested by German forces after hiding for over two years in Amsterdam."),
        HistoryFact(196, 8, 5, 1962, "North America", "Actress Marilyn Monroe was found dead at her home in Los Angeles."),
        HistoryFact(197, 8, 6, 1926, "North America", "American swimmer Gertrude Ederle became the first woman to swim across the English Channel."),
        HistoryFact(198, 8, 8, 1963, "Europe", "A gang carried out the Great Train Robbery in England, stealing a then record sum from a Royal Mail train."),
        HistoryFact(199, 8, 10, 1809, "South America", "Ecuador declared its intention to seek independence from Spanish colonial rule, an early spark in the region's independence movement."),
        HistoryFact(200, 8, 13, 1961, "Europe", "East German authorities began construction of the Berlin Wall."),
        HistoryFact(201, 8, 16, 1977, "North America", "Musician Elvis Presley died at his home in Memphis, Tennessee."),
        HistoryFact(202, 8, 18, 1920, "North America", "The 19th Amendment to the U.S. Constitution was ratified, granting many American women the right to vote."),
        HistoryFact(203, 8, 20, 1988, "Middle East", "A ceasefire took effect ending active combat in the Iran-Iraq War."),
        HistoryFact(204, 8, 21, 1959, "North America", "Hawaii was admitted as the 50th U.S. state."),
        HistoryFact(205, 8, 23, 1989, "Europe", "Roughly two million people joined hands across Estonia, Latvia, and Lithuania in a peaceful protest known as the Baltic Way."),
        HistoryFact(206, 8, 27, 1883, "Asia", "The volcano Krakatoa erupted catastrophically in present day Indonesia, producing one of the loudest sounds in recorded history."),
        HistoryFact(207, 8, 29, 2005, "North America", "Hurricane Katrina made landfall on the U.S. Gulf Coast, causing catastrophic flooding in New Orleans."),
        HistoryFact(208, 8, 31, 1957, "Asia", "Malaysia, then known as Malaya, gained independence from British colonial rule."),
        HistoryFact(209, 9, 1, 1939, "Europe", "Germany invaded Poland, an event widely regarded as the beginning of World War II in Europe."),
        HistoryFact(210, 9, 3, 1783, "North America", "The Treaty of Paris was signed, formally ending the American Revolutionary War."),
        HistoryFact(211, 9, 6, 1997, "Europe", "The funeral of Diana, Princess of Wales, was held in London, watched by an estimated worldwide audience of over two billion people."),
        HistoryFact(212, 9, 12, 1977, "Africa", "South African anti-apartheid activist Steve Biko died in police custody, drawing global condemnation."),
        HistoryFact(213, 9, 17, 1978, "Middle East", "Israel and Egypt signed the Camp David Accords, a framework for peace between the two nations."),
        HistoryFact(214, 9, 18, 1931, "Asia", "Japanese forces staged an incident in Manchuria that led to the invasion and occupation of the region."),
        HistoryFact(215, 9, 19, 1893, "Oceania", "New Zealand became the first self governing country in the world to grant women the right to vote."),
        HistoryFact(216, 9, 20, 1519, "Europe", "Portuguese explorer Ferdinand Magellan set sail on the expedition that would achieve the first circumnavigation of the globe."),
        HistoryFact(217, 9, 22, 1862, "North America", "U.S. President Abraham Lincoln issued the preliminary Emancipation Proclamation."),
        HistoryFact(218, 9, 23, 1846, "Europe", "Astronomers first observed the planet Neptune, confirming its existence based on mathematical predictions."),
        HistoryFact(219, 9, 27, 1996, "Asia", "The Taliban captured Kabul, Afghanistan, and established control over most of the country."),
        HistoryFact(220, 9, 28, 1928, "Europe", "Scottish scientist Alexander Fleming discovered penicillin, the world's first widely used antibiotic."),
        HistoryFact(221, 9, 29, 1954, "Europe", "CERN, the European Organization for Nuclear Research, was founded near Geneva, Switzerland."),
        HistoryFact(222, 9, 30, 1938, "Europe", "Britain, France, Germany, and Italy signed the Munich Agreement, allowing German annexation of part of Czechoslovakia."),
        HistoryFact(223, 10, 4, 1957, "Asia", "The Soviet Union launched Sputnik 1, the first artificial satellite, beginning the Space Age."),
        HistoryFact(224, 10, 5, 1962, "Europe", "The first James Bond film, Dr. No, premiered in London."),
        HistoryFact(225, 10, 6, 1973, "Middle East", "Egypt and Syria launched a coordinated surprise attack on Israel, beginning the Yom Kippur War."),
        HistoryFact(226, 10, 7, 2001, "Asia", "The United States and allied forces began a military campaign in Afghanistan following the September 11 attacks."),
        HistoryFact(227, 10, 9, 1967, "South America", "Revolutionary leader Che Guevara was captured and executed in Bolivia."),
        HistoryFact(228, 10, 11, 1968, "North America", "NASA launched Apollo 7, the first crewed mission in the Apollo program."),
        HistoryFact(229, 10, 15, 1783, "Europe", "The first untethered hot air balloon flight carrying a human took place in Paris."),
        HistoryFact(230, 10, 18, 1867, "North America", "The United States formally took possession of Alaska after purchasing it from Russia."),
        HistoryFact(231, 10, 21, 1805, "Europe", "The Royal Navy defeated a combined French and Spanish fleet at the Battle of Trafalgar."),
        HistoryFact(232, 10, 23, 1956, "Europe", "A popular uprising against Soviet controlled government began in Hungary."),
        HistoryFact(233, 10, 25, 1971, "Asia", "The United Nations General Assembly voted to recognize the People's Republic of China and transfer China's seat from Taiwan."),
        HistoryFact(234, 10, 29, 1929, "North America", "The New York Stock Exchange crashed on a day known as Black Tuesday, helping trigger the Great Depression."),
        HistoryFact(235, 10, 31, 1517, "Europe", "Martin Luther is traditionally said to have posted his Ninety Five Theses, a spark for the Protestant Reformation."),
        HistoryFact(236, 11, 2, 1917, "Middle East", "The British government issued the Balfour Declaration, expressing support for a Jewish homeland in Palestine."),
        HistoryFact(237, 11, 6, 1917, "Europe", "Bolshevik forces seized power in Petrograd, a key event of the Russian Revolution."),
        HistoryFact(238, 11, 8, 1519, "North America", "Spanish conquistador Hernan Cortes and Aztec ruler Moctezuma II first met near present day Mexico City."),
        HistoryFact(239, 11, 9, 1938, "Europe", "Coordinated attacks on Jewish communities across Germany and Austria, known as Kristallnacht, marked an escalation of Nazi persecution."),
        HistoryFact(240, 11, 10, 1983, "North America", "Microsoft founder Bill Gates announced the Windows operating system to the public for the first time."),
        HistoryFact(241, 11, 13, 1927, "North America", "The Holland Tunnel opened, connecting New York and New Jersey beneath the Hudson River."),
        HistoryFact(242, 11, 15, 1889, "South America", "Brazil became a republic after a military coup ended the monarchy."),
        HistoryFact(243, 11, 16, 1945, "Global", "UNESCO, the United Nations agency for education, science, and culture, was founded."),
        HistoryFact(244, 11, 19, 1863, "North America", "U.S. President Abraham Lincoln delivered the Gettysburg Address."),
        HistoryFact(245, 11, 21, 1877, "North America", "Inventor Thomas Edison announced his invention of the phonograph, an early device for recording and playing sound."),
        HistoryFact(246, 11, 25, 1963, "North America", "U.S. President John F. Kennedy was laid to rest at Arlington National Cemetery following his assassination three days earlier."),
        HistoryFact(247, 11, 29, 1947, "Middle East", "The United Nations General Assembly voted to adopt a plan to partition British controlled Palestine into separate Jewish and Arab states."),
        HistoryFact(248, 11, 30, 1782, "North America", "The United States and Great Britain signed preliminary peace terms in Paris, effectively ending the American Revolutionary War."),
        HistoryFact(249, 12, 1, 1918, "Europe", "Transylvania united with the Kingdom of Romania, an event still celebrated as Great Union Day."),
        HistoryFact(250, 12, 3, 1967, "Africa", "South African surgeon Christiaan Barnard performed the world's first human to human heart transplant."),
        HistoryFact(251, 12, 4, 1791, "Europe", "The Observer newspaper published its first edition in London, becoming the world's oldest Sunday newspaper still in publication."),
        HistoryFact(252, 12, 5, 1955, "North America", "The Montgomery Bus Boycott began in Alabama, days after Rosa Parks's arrest."),
        HistoryFact(253, 12, 6, 1917, "North America", "A massive explosion caused by a ship collision devastated the harbor city of Halifax, Canada."),
        HistoryFact(254, 12, 8, 1980, "North America", "Musician John Lennon was shot and killed outside his New York City apartment."),
        HistoryFact(255, 12, 9, 1961, "Africa", "Tanganyika, later part of Tanzania, gained independence from British colonial rule."),
        HistoryFact(256, 12, 11, 1936, "Europe", "King Edward VIII of the United Kingdom abdicated the throne to marry Wallis Simpson."),
        HistoryFact(257, 12, 13, 1937, "Asia", "Japanese forces captured Nanjing, China, beginning a period of mass violence against civilians known as the Nanjing Massacre."),
        HistoryFact(258, 12, 14, 1911, "Global", "Norwegian explorer Roald Amundsen's expedition became the first to reach the South Pole."),
        HistoryFact(259, 12, 15, 1791, "North America", "The U.S. Bill of Rights was ratified, adding the first ten amendments to the Constitution."),
        HistoryFact(260, 12, 17, 1989, "South America", "Fernando Collor de Mello won Brazil's first direct presidential election in nearly three decades."),
        HistoryFact(261, 12, 18, 1865, "North America", "The 13th Amendment to the U.S. Constitution was ratified, formally abolishing slavery."),
        HistoryFact(262, 12, 19, 1998, "North America", "The U.S. House of Representatives voted to impeach President Bill Clinton."),
        HistoryFact(263, 12, 22, 1989, "Europe", "The Brandenburg Gate reopened in Berlin, symbolizing the end of the city's Cold War division."),
        HistoryFact(264, 12, 23, 1888, "Europe", "Artist Vincent van Gogh injured his own ear during a period of personal crisis in Arles, France."),
        HistoryFact(265, 12, 24, 1968, "Global", "The crew of Apollo 8 became the first humans to orbit the Moon, and took the famous Earthrise photograph."),
        HistoryFact(266, 12, 27, 1949, "Asia", "The Netherlands formally transferred sovereignty of Indonesia, ending centuries of Dutch colonial rule."),
        HistoryFact(267, 12, 29, 1170, "Europe", "Archbishop Thomas Becket was murdered inside Canterbury Cathedral in England."),
        HistoryFact(268, 12, 30, 1922, "Europe", "The Union of Soviet Socialist Republics was formally established."),
        HistoryFact(269, 1, 5, 1919, "Europe", "The German Workers' Party, which would later become the Nazi Party, was founded in Munich."),
        HistoryFact(270, 1, 7, 1610, "Europe", "Galileo Galilei observed the four largest moons of Jupiter for the first time through his telescope."),
        HistoryFact(271, 1, 11, 1922, "North America", "Insulin was successfully used to treat a human diabetes patient for the first time, in Toronto, Canada."),
        HistoryFact(272, 1, 13, 1990, "North America", "Douglas Wilder was inaugurated as Virginia's governor, becoming the first elected African American governor in U.S. history."),
        HistoryFact(273, 1, 14, 1943, "Africa", "Allied leaders met in Casablanca, Morocco, to plan strategy for the remainder of World War II."),
        HistoryFact(274, 1, 17, 1991, "Middle East", "A U.S. led coalition began a military campaign to expel Iraqi forces from Kuwait, opening the Gulf War."),
        HistoryFact(275, 1, 19, 1983, "Europe", "The Apple Lisa, one of the first personal computers with a graphical user interface, was announced."),
        HistoryFact(276, 1, 21, 1976, "Europe", "The Concorde began the world's first commercial supersonic passenger flights."),
        HistoryFact(277, 1, 22, 1901, "Europe", "Queen Victoria of the United Kingdom died after a reign of 63 years, one of the longest in British history."),
        HistoryFact(278, 1, 24, 41, "Europe", "Roman Emperor Caligula was assassinated by members of his own guard."),
        HistoryFact(279, 1, 27, 1888, "North America", "The National Geographic Society was founded in Washington, D.C."),
        HistoryFact(280, 1, 29, 1845, "North America", "Edgar Allan Poe's poem The Raven was first published in a New York newspaper."),
        HistoryFact(281, 1, 30, 1948, "Asia", "Indian independence leader Mohandas Gandhi was assassinated in New Delhi."),
        HistoryFact(282, 2, 3, 1966, "Global", "The Soviet spacecraft Luna 9 achieved the first successful soft landing on the Moon."),
        HistoryFact(283, 2, 5, 1970, "Africa", "The first modern census in independent Nigeria helped shape the country's early political structure."),
        HistoryFact(284, 2, 9, 1895, "North America", "William Morgan invented the game of volleyball in Massachusetts."),
        HistoryFact(285, 2, 12, 1912, "Asia", "The last Qing emperor of China abdicated, ending over two thousand years of imperial rule."),
        HistoryFact(286, 2, 14, 1929, "North America", "Seven men were killed in Chicago in the gang related killings known as the Saint Valentine's Day Massacre."),
        HistoryFact(287, 2, 15, 1965, "North America", "Canada officially adopted its current national flag, featuring the red maple leaf."),
        HistoryFact(288, 2, 16, 1959, "Caribbean", "Fidel Castro was sworn in as Prime Minister of Cuba."),
        HistoryFact(289, 2, 18, 1965, "Africa", "The Gambia gained independence from British colonial rule."),
        HistoryFact(290, 2, 19, 1878, "North America", "Thomas Edison patented the phonograph, an early sound recording device."),
        HistoryFact(291, 2, 22, 1980, "North America", "The United States ice hockey team defeated the Soviet Union at the Winter Olympics in a game later called the Miracle on Ice."),
        HistoryFact(292, 2, 23, 1945, "Asia", "U.S. Marines raised the flag atop Mount Suribachi during the Battle of Iwo Jima."),
        HistoryFact(293, 2, 24, 1976, "Caribbean", "Cuba adopted a new socialist constitution."),
        HistoryFact(294, 2, 26, 1993, "North America", "A truck bomb exploded in the parking garage of the World Trade Center in New York City."),
        HistoryFact(295, 2, 27, 1933, "Europe", "A fire severely damaged the German Reichstag building, an event the Nazi government used to justify expanded emergency powers."),
        HistoryFact(296, 2, 28, 1953, "Europe", "Scientists James Watson and Francis Crick announced they had determined the structure of DNA."),
        HistoryFact(297, 3, 1, 1872, "North America", "Yellowstone became the world's first officially designated national park."),
        HistoryFact(298, 3, 4, 1681, "North America", "King Charles II of England granted William Penn a charter for the territory that would become Pennsylvania."),
        HistoryFact(299, 3, 5, 1946, "Europe", "Winston Churchill delivered his Iron Curtain speech in Missouri, describing the division of Europe in the early Cold War."),
        HistoryFact(300, 3, 7, 1876, "North America", "Alexander Graham Bell was granted a patent for the telephone."),
        HistoryFact(301, 3, 9, 1796, "Europe", "Napoleon Bonaparte married Josephine de Beauharnais in Paris, shortly before taking command of French forces in Italy."),
        HistoryFact(302, 3, 10, 1959, "Asia", "A major uprising against Chinese rule broke out in Tibet, prompting the Dalai Lama to flee into exile in India."),
        HistoryFact(303, 3, 13, 1997, "North America", "Astronomer discoveries surrounding the Hale-Bopp comet drew record public attention as it reached peak visibility."),
        HistoryFact(304, 3, 14, 1794, "North America", "Inventor Eli Whitney received a patent for the cotton gin."),
        HistoryFact(305, 3, 18, 1965, "Global", "Soviet cosmonaut Alexei Leonov performed the first spacewalk in human history."),
        HistoryFact(306, 3, 20, 1602, "Europe", "The Dutch East India Company was founded, often considered the world's first major multinational corporation."),
        HistoryFact(307, 3, 22, 1980, "Africa", "Southern Rhodesia was internationally recognized as the newly independent nation of Zimbabwe."),
        HistoryFact(308, 3, 24, 1989, "North America", "The oil tanker Exxon Valdez struck a reef off Alaska, causing a massive oil spill."),
        HistoryFact(309, 3, 27, 1964, "North America", "The Good Friday earthquake, the most powerful ever recorded in North America, struck Alaska."),
        HistoryFact(310, 3, 28, 1979, "North America", "A partial nuclear meltdown occurred at the Three Mile Island power plant in Pennsylvania."),
        HistoryFact(311, 3, 29, 1974, "Asia", "Archaeologists excavating near Xi'an, China, discovered the buried Terracotta Army."),
        HistoryFact(312, 3, 31, 1889, "Europe", "The Eiffel Tower officially opened in Paris."),
        HistoryFact(313, 4, 2, 1792, "North America", "The United States Congress established the U.S. Mint."),
        HistoryFact(314, 4, 3, 1973, "North America", "Motorola researcher Martin Cooper made the first handheld mobile phone call."),
        HistoryFact(315, 4, 5, 1976, "Asia", "The death of Chinese leader Zhou Enlai's memorial sparked mass public mourning that became a significant political moment."),
        HistoryFact(316, 4, 6, 1909, "North America", "Explorer Robert Peary's expedition claimed to have reached the North Pole."),
        HistoryFact(317, 4, 9, 1940, "Europe", "Germany invaded Denmark and Norway."),
        HistoryFact(318, 4, 10, 1912, "Europe", "The RMS Titanic departed Southampton, England, on its only voyage."),
        HistoryFact(319, 4, 11, 1970, "North America", "NASA launched Apollo 13, which suffered an onboard explosion en route to the Moon."),
        HistoryFact(320, 4, 13, 1943, "Europe", "The Jefferson Memorial was dedicated in Washington, D.C., on the 200th anniversary of Thomas Jefferson's birth."),
        HistoryFact(321, 4, 17, 1961, "Caribbean", "A CIA backed group of exiles launched the failed Bay of Pigs invasion of Cuba."),
        HistoryFact(322, 4, 18, 1906, "North America", "A major earthquake and resulting fires devastated San Francisco, California."),
        HistoryFact(323, 4, 21, 1926, "Europe", "Queen Elizabeth II of the United Kingdom was born in London."),
        HistoryFact(324, 4, 23, 1985, "North America", "The Coca-Cola Company announced a reformulated recipe, later reversing course after public backlash."),
        HistoryFact(325, 4, 24, 1990, "North America", "NASA launched the Hubble Space Telescope aboard the Space Shuttle Discovery."),
        HistoryFact(326, 4, 25, 1953, "Europe", "James Watson and Francis Crick published their landmark paper describing the double helix structure of DNA."),
        HistoryFact(327, 4, 28, 1789, "Global", "A mutiny occurred aboard the British ship HMS Bounty in the Pacific Ocean."),
        HistoryFact(328, 4, 29, 1913, "North America", "Inventor Gideon Sundback patented a practical version of the modern zipper."),
        HistoryFact(329, 5, 2, 1519, "Europe", "Renaissance artist and inventor Leonardo da Vinci died in Amboise, France."),
        HistoryFact(330, 5, 4, 1979, "Europe", "Margaret Thatcher became the first female Prime Minister of the United Kingdom."),
        HistoryFact(331, 5, 6, 1994, "Europe", "The Channel Tunnel officially opened, connecting England and France beneath the sea."),
        HistoryFact(332, 5, 7, 1915, "Europe", "A German submarine sank the passenger liner RMS Lusitania, killing nearly 1,200 people."),
        HistoryFact(333, 5, 9, 1960, "North America", "The U.S. Food and Drug Administration approved the first birth control pill."),
        HistoryFact(334, 5, 10, 1869, "North America", "The First Transcontinental Railroad was completed in the United States with the driving of a ceremonial golden spike."),
        HistoryFact(335, 5, 11, 1997, "Global", "IBM's Deep Blue computer defeated world chess champion Garry Kasparov in a full match for the first time."),
        HistoryFact(336, 5, 13, 1954, "Europe", "Sports Illustrated magazine published its very first issue in the United States."),
        HistoryFact(337, 5, 15, 1928, "North America", "The animated character Mickey Mouse debuted publicly in a short test screening."),
        HistoryFact(338, 5, 16, 1929, "North America", "The first Academy Awards ceremony was held in Hollywood, California."),
        HistoryFact(339, 5, 17, 1954, "North America", "The U.S. Supreme Court decided Brown v. Board of Education, ruling public school segregation unconstitutional."),
        HistoryFact(340, 5, 19, 1780, "North America", "An unusual atmospheric phenomenon caused a mysterious darkness to fall over parts of New England during the day."),
        HistoryFact(341, 5, 20, 1932, "North America", "Aviator Amelia Earhart began her solo flight across the Atlantic Ocean."),
        HistoryFact(342, 5, 21, 1927, "Europe", "Aviator Charles Lindbergh landed in Paris, completing the first solo nonstop transatlantic flight."),
        HistoryFact(343, 5, 26, 1940, "Europe", "The evacuation of Allied soldiers from Dunkirk, France, began during World War II."),
        HistoryFact(344, 5, 28, 1937, "North America", "The Golden Gate Bridge opened to vehicle traffic in San Francisco."),
        HistoryFact(345, 5, 30, 1911, "North America", "The first Indianapolis 500 automobile race was held."),
        HistoryFact(346, 5, 31, 1889, "North America", "The Johnstown Flood killed over 2,000 people in Pennsylvania after a dam failure."),
        HistoryFact(347, 6, 4, 1919, "North America", "The U.S. Congress passed the 19th Amendment, sending it to the states for ratification on women's suffrage."),
        HistoryFact(348, 6, 5, 1968, "North America", "U.S. presidential candidate Robert F. Kennedy was shot in Los Angeles, dying the following day."),
        HistoryFact(349, 6, 8, 1949, "Europe", "George Orwell's novel Nineteen Eighty Four was published in London."),
        HistoryFact(350, 6, 11, 1963, "Asia", "Buddhist monk Thich Quang Duc's self immolation in Saigon drew worldwide attention to the Vietnamese political crisis."),
        HistoryFact(351, 6, 14, 1919, "Europe", "British aviators John Alcock and Arthur Brown began the first nonstop transatlantic flight."),
        HistoryFact(352, 6, 16, 1963, "Global", "Soviet cosmonaut Valentina Tereshkova became the first woman to travel into space."),
        HistoryFact(353, 6, 18, 1815, "Europe", "The Battle of Waterloo ended Napoleon Bonaparte's rule as Emperor of the French."),
        HistoryFact(354, 6, 21, 1948, "Europe", "The first practical transistor was publicly demonstrated by researchers at Bell Labs in the United States."),
        HistoryFact(355, 6, 25, 1876, "North America", "The Battle of the Little Bighorn took place between the U.S. Army and a coalition of Native nations."),
        HistoryFact(356, 6, 29, 1613, "Europe", "London's Globe Theatre, closely associated with William Shakespeare, burned down during a performance."),
        HistoryFact(357, 6, 30, 1859, "Europe", "French acrobat Charles Blondin crossed Niagara Falls on a tightrope for the first time."),
        HistoryFact(358, 7, 22, 1946, "Middle East", "Militants bombed the King David Hotel in Jerusalem, then housing British Mandate government offices, killing 91 people."),
        HistoryFact(359, 7, 22, 2009, "Asia", "The longest total solar eclipse of the twenty first century swept across Asia and the Pacific, lasting over six minutes at its peak."),
        HistoryFact(360, 1, 1, 1962, "Oceania", "Western Samoa gained independence from New Zealand, becoming the first Pacific Island nation to do so in the twentieth century."),
        HistoryFact(361, 1, 31, 1968, "Oceania", "Nauru became independent after decades of joint Australian, New Zealand, and British administration."),
        HistoryFact(362, 10, 10, 1970, "Oceania", "Fiji gained independence from the United Kingdom."),
        HistoryFact(363, 8, 4, 1965, "Oceania", "The Cook Islands became self governing in free association with New Zealand."),
        HistoryFact(364, 10, 19, 1974, "Oceania", "Niue became self governing in free association with New Zealand."),
        HistoryFact(365, 1, 1, 1901, "Oceania", "Six British colonies federated to form the Commonwealth of Australia."),
        HistoryFact(366, 12, 12, 1963, "Africa", "Kenya gained independence from British colonial rule."),
        HistoryFact(367, 8, 6, 1962, "Caribbean", "Jamaica gained independence from the United Kingdom."),
        HistoryFact(368, 8, 31, 1962, "Caribbean", "Trinidad and Tobago gained independence from the United Kingdom."),
        HistoryFact(369, 1, 4, 1948, "Asia", "Myanmar, then known as Burma, gained independence from British colonial rule."),
        HistoryFact(370, 2, 17, 2008, "Europe", "Kosovo unilaterally declared independence from Serbia."),
        HistoryFact(371, 4, 30, 1975, "Asia", "North Vietnamese forces captured Saigon, ending the Vietnam War and leading to the country's reunification."),
        HistoryFact(372, 5, 3, 1947, "Asia", "Japan's postwar constitution took effect, renouncing war and establishing a parliamentary system."),
        HistoryFact(373, 5, 22, 1990, "Middle East", "North Yemen and South Yemen unified to form the Republic of Yemen."),
        HistoryFact(374, 6, 2, 1946, "Europe", "Italians voted in a referendum to abolish the monarchy and establish a republic."),
        HistoryFact(375, 7, 7, 1937, "Asia", "A clash at the Marco Polo Bridge near Beijing escalated into full scale war between China and Japan."),
        HistoryFact(376, 7, 10, 1973, "Caribbean", "The Bahamas gained independence from the United Kingdom."),
        HistoryFact(377, 7, 12, 1975, "Africa", "Sao Tome and Principe gained independence from Portugal."),
        HistoryFact(378, 7, 12, 1979, "Oceania", "Kiribati gained independence from the United Kingdom."),
        HistoryFact(379, 7, 28, 1821, "South America", "Jose de San Martin proclaimed Peru's independence from Spain."),
        HistoryFact(380, 8, 7, 1960, "Africa", "Ivory Coast gained independence from France."),
        HistoryFact(381, 8, 11, 1960, "Africa", "Chad gained independence from France."),
        HistoryFact(382, 8, 25, 1825, "South America", "Uruguay declared independence from the Empire of Brazil."),
        HistoryFact(383, 9, 9, 1948, "Asia", "The Democratic People's Republic of Korea, North Korea, was formally established."),
        HistoryFact(384, 9, 9, 1991, "Asia", "Tajikistan declared independence from the Soviet Union."),
        HistoryFact(385, 10, 27, 1979, "Caribbean", "Saint Vincent and the Grenadines gained independence from the United Kingdom."),
        HistoryFact(386, 10, 27, 1991, "Asia", "Turkmenistan declared independence from the Soviet Union."),
        HistoryFact(387, 11, 1, 1954, "Africa", "Nationalist attacks across French Algeria marked the start of the Algerian War of Independence."),
        HistoryFact(388, 11, 3, 1903, "Central America", "Panama declared independence from Colombia, backed by United States support."),
        HistoryFact(389, 11, 3, 1978, "Caribbean", "Dominica gained independence from the United Kingdom."),
        HistoryFact(390, 9, 30, 1966, "Africa", "Botswana gained independence from the United Kingdom."),
        HistoryFact(391, 10, 24, 1964, "Africa", "Zambia gained independence from the United Kingdom."),
        HistoryFact(392, 10, 4, 1966, "Africa", "Lesotho gained independence from the United Kingdom."),
        HistoryFact(393, 7, 6, 1964, "Africa", "Malawi gained independence from the United Kingdom."),
        HistoryFact(394, 11, 30, 1966, "Caribbean", "Barbados gained independence from the United Kingdom."),
        HistoryFact(395, 5, 26, 1966, "South America", "Guyana gained independence from the United Kingdom."),
        HistoryFact(396, 2, 18, 1965, "Africa", "The Gambia gained independence from the United Kingdom."),
        HistoryFact(397, 4, 27, 1961, "Africa", "Sierra Leone gained independence from the United Kingdom."),
        HistoryFact(398, 6, 1, 1962, "Africa", "Burundi gained independence from Belgium."),
        HistoryFact(399, 8, 5, 1960, "Africa", "Burkina Faso, then known as Upper Volta, gained independence from France."),
        HistoryFact(400, 8, 3, 1960, "Africa", "Niger gained independence from France."),
        HistoryFact(401, 6, 26, 1960, "Africa", "Madagascar gained independence from France."),
        HistoryFact(402, 9, 22, 1960, "Africa", "Mali gained independence from France."),
        HistoryFact(403, 8, 15, 1960, "Africa", "The Republic of the Congo gained independence from France."),
        HistoryFact(404, 8, 17, 1960, "Africa", "Gabon gained independence from France."),
        HistoryFact(405, 8, 20, 1960, "Africa", "Senegal gained independence from France, briefly as part of the Mali Federation."),
        HistoryFact(406, 6, 30, 1960, "Africa", "The Democratic Republic of the Congo gained independence from Belgium."),
        HistoryFact(407, 9, 1, 1991, "Asia", "Uzbekistan declared independence from the Soviet Union."),
        HistoryFact(408, 8, 30, 1991, "Asia", "Kyrgyzstan declared independence from the Soviet Union."),
        HistoryFact(409, 6, 12, 1898, "Asia", "Emilio Aguinaldo proclaimed Philippine independence from Spain."),
        HistoryFact(410, 12, 2, 1975, "Asia", "The Lao People's Democratic Republic was proclaimed, ending centuries of monarchy in Laos."),
        HistoryFact(411, 11, 9, 1953, "Asia", "Cambodia gained full independence from France."),
        HistoryFact(412, 1, 10, 1920, "Global", "The Treaty of Versailles took effect and the League of Nations formally came into being."),
        HistoryFact(413, 7, 25, 1952, "Caribbean", "Puerto Rico's constitution took effect, establishing it as a self governing commonwealth."),
        HistoryFact(414, 9, 10, 1974, "Africa", "Portugal formally recognized the independence of Guinea-Bissau."),
        HistoryFact(415, 12, 20, 1999, "Asia", "Portugal handed sovereignty of Macau to China, ending the last European colony in Asia."),
        HistoryFact(416, 8, 15, 1914, "Central America", "The SS Ancon became the first ship to transit the newly completed Panama Canal."),
        HistoryFact(417, 12, 31, 1999, "Central America", "The United States formally handed control of the Panama Canal over to Panama."),
        HistoryFact(418, 9, 21, 1988, "Central America", "Swimmer Sylvia Poll won Costa Rica's first ever Olympic medal, a silver in the 200 meter freestyle at the Seoul Games."),
        HistoryFact(419, 7, 21, 1996, "Central America", "Swimmer Claudia Poll won Costa Rica's first Olympic gold medal, and the first individual Olympic gold for any Central American nation."),
        HistoryFact(420, 12, 10, 1987, "Central America", "Costa Rican President Oscar Arias Sanchez received the Nobel Peace Prize for his work on Central American peace efforts."),
        HistoryFact(421, 12, 10, 1992, "Central America", "Guatemalan activist Rigoberta Menchu received the Nobel Peace Prize for her work on indigenous rights."),
        HistoryFact(422, 1, 16, 1992, "Central America", "The Chapultepec Peace Accords were signed, ending El Salvador's twelve year civil war."),
        HistoryFact(423, 6, 27, 1954, "Central America", "A coup backed by foreign intelligence services overthrew Guatemalan President Jacobo Arbenz."),
        HistoryFact(424, 9, 21, 1956, "Central America", "Nicaraguan dictator Anastasio Somoza Garcia was fatally shot by a young poet at a public event."),
        HistoryFact(425, 7, 19, 1979, "Central America", "The Sandinista National Liberation Front overthrew the Somoza dictatorship in Nicaragua."),
        HistoryFact(426, 1, 3, 1990, "Central America", "Panamanian leader Manuel Noriega surrendered to United States forces, ending Operation Just Cause."),
        HistoryFact(427, 9, 1, 1999, "Central America", "Mireya Moscoso was inaugurated as Panama's first female president."),
        HistoryFact(428, 4, 25, 1990, "Central America", "Violeta Chamorro was inaugurated as Nicaragua's president, becoming the first woman elected head of state in the Americas."),
        HistoryFact(429, 5, 8, 2010, "Central America", "Laura Chinchilla was inaugurated as Costa Rica's first female president."),
        HistoryFact(430, 1, 12, 1986, "Central America", "Costa Rican born engineer Franklin Chang Diaz flew his first space shuttle mission as one of NASA's astronauts."),
        HistoryFact(431, 8, 16, 2008, "Caribbean", "Jamaican sprinter Usain Bolt set a new world record in the men's 100 meters at the Beijing Olympics."),
        HistoryFact(432, 8, 20, 2009, "Caribbean", "Usain Bolt lowered his own world record in the 200 meters at the World Championships in Berlin."),
        HistoryFact(433, 10, 28, 1962, "Caribbean", "The Cuban Missile Crisis ended as the Soviet Union agreed to withdraw its missiles from Cuba."),
        HistoryFact(434, 8, 31, 1992, "Caribbean", "Trinidad and Tobago officially recognized the steelpan as its national instrument."),
        HistoryFact(435, 5, 30, 1961, "Caribbean", "Dominican dictator Rafael Trujillo was assassinated, ending a three decade regime."),
        HistoryFact(436, 4, 19, 1961, "Caribbean", "Cuban forces defeated the United States backed exile brigade at the Bay of Pigs."),
        HistoryFact(437, 2, 7, 1991, "Caribbean", "Jean Bertrand Aristide was inaugurated as Haiti's first democratically elected president."),
        HistoryFact(438, 11, 30, 2021, "Caribbean", "Barbados became a republic, removing the British monarch as its head of state."),
        HistoryFact(439, 7, 25, 1976, "Caribbean", "Hasely Crawford won the 100 meters at the Montreal Olympics, giving Trinidad and Tobago its first Olympic gold medal."),
        HistoryFact(440, 11, 19, 1969, "South America", "Brazilian footballer Pele scored his one thousandth career goal."),
        HistoryFact(441, 6, 29, 1958, "South America", "Brazil defeated Sweden to win its first FIFA World Cup."),
        HistoryFact(442, 6, 22, 1986, "South America", "Diego Maradona scored both the Hand of God goal and the Goal of the Century in the same World Cup match against England."),
        HistoryFact(443, 11, 4, 1970, "South America", "Salvador Allende was elected President of Chile, becoming Latin America's first democratically elected Marxist head of state."),
        HistoryFact(444, 12, 10, 1982, "South America", "Colombian author Gabriel Garcia Marquez received the Nobel Prize in Literature."),
        HistoryFact(445, 12, 10, 1971, "South America", "Chilean poet Pablo Neruda received the Nobel Prize in Literature."),
        HistoryFact(446, 12, 10, 2010, "South America", "Peruvian author Mario Vargas Llosa received the Nobel Prize in Literature."),
        HistoryFact(447, 8, 6, 1813, "South America", "Simon Bolivar's forces liberated Caracas during the Admirable Campaign."),
        HistoryFact(448, 1, 22, 2006, "South America", "Evo Morales was inaugurated as Bolivia's first president of indigenous descent."),
        HistoryFact(449, 7, 1, 1974, "South America", "Isabel Peron took office as President of Argentina, becoming the first female head of state in the Americas to hold a country's top executive office."),
        HistoryFact(450, 3, 11, 2006, "South America", "Michelle Bachelet was inaugurated as Chile's first female president."),
        HistoryFact(451, 1, 1, 2011, "South America", "Dilma Rousseff was inaugurated as Brazil's first female president."),
        HistoryFact(452, 7, 19, 2020, "Middle East", "The United Arab Emirates launched the Hope Probe toward Mars, the first interplanetary mission by an Arab nation."),
        HistoryFact(453, 12, 10, 1999, "Middle East", "Egyptian chemist Ahmed Zewail received the Nobel Prize in Chemistry, the first Arab scientist to win a Nobel Prize in the sciences."),
        HistoryFact(454, 12, 10, 2003, "Middle East", "Iranian lawyer Shirin Ebadi received the Nobel Peace Prize, becoming the first Iranian and first Muslim woman to win the award."),
        HistoryFact(455, 11, 19, 1977, "Middle East", "Egyptian President Anwar Sadat became the first Arab leader to visit Israel."),
        HistoryFact(456, 10, 26, 1994, "Middle East", "Israel and Jordan signed a peace treaty formally ending decades of war between the two nations."),
        HistoryFact(457, 11, 20, 2022, "Middle East", "Qatar hosted the opening match of the first FIFA World Cup held in the Arab world."),
        HistoryFact(458, 6, 24, 2018, "Middle East", "Saudi Arabia lifted its ban on women driving."),
        HistoryFact(459, 5, 16, 2005, "Middle East", "Kuwaiti women were granted the right to vote and run for political office."),
        HistoryFact(460, 9, 25, 2019, "Middle East", "Hazza Al Mansouri became the first Emirati and first Gulf Arab to travel to the International Space Station."),
        HistoryFact(461, 8, 11, 2016, "Oceania", "Fiji won its first ever Olympic medal, a gold in men's rugby sevens at the Rio Games."),
        HistoryFact(462, 9, 25, 2000, "Oceania", "Cathy Freeman won the 400 meters at the Sydney Olympics, becoming the first Aboriginal Australian to win an individual Olympic gold in athletics."),
        HistoryFact(463, 8, 5, 2016, "Oceania", "Tongan flag bearer Pita Taufatofua drew global attention at the Rio Olympics opening ceremony."),
        HistoryFact(464, 10, 26, 2017, "Oceania", "Jacinda Ardern was sworn in as Prime Minister of New Zealand, then the youngest female head of government in the world."),
        HistoryFact(465, 8, 30, 2001, "Oceania", "The Bougainville Peace Agreement was signed, ending a long running conflict in Papua New Guinea."),
        HistoryFact(466, 10, 20, 1973, "Oceania", "The Sydney Opera House officially opened."),
        HistoryFact(467, 6, 20, 1987, "Oceania", "New Zealand's All Blacks won the first ever Rugby World Cup."),
        HistoryFact(468, 12, 10, 1945, "Oceania", "Australian scientist Howard Florey received the Nobel Prize for turning penicillin into a usable medicine, the first Australian Nobel laureate."),
        HistoryFact(469, 12, 10, 1908, "Oceania", "New Zealand born physicist Ernest Rutherford received the Nobel Prize in Chemistry for his work on radioactive decay."),
        HistoryFact(470, 12, 10, 2000, "Oceania", "New Zealand born chemist Alan MacDiarmid received the Nobel Prize for the discovery of conductive polymers."),
        HistoryFact(471, 12, 10, 1962, "Oceania", "New Zealand born scientist Maurice Wilkins received the Nobel Prize for his contribution to discovering the structure of DNA."),
        HistoryFact(472, 3, 29, 2015, "Oceania", "Australia defeated New Zealand to win the Cricket World Cup final in Melbourne."),
        HistoryFact(473, 7, 9, 1986, "Oceania", "New Zealand's parliament passed the Homosexual Law Reform Act, decriminalizing same sex relationships between men."),
        HistoryFact(474, 4, 17, 2013, "Oceania", "New Zealand legalized same sex marriage, becoming the first country in Oceania to do so."),
        HistoryFact(475, 12, 7, 2017, "Oceania", "Australia legalized same sex marriage following a national postal survey."),
        HistoryFact(476, 6, 26, 1972, "Central America", "Panamanian boxer Roberto Duran defeated Ken Buchanan to win the world lightweight title."),
        HistoryFact(477, 3, 24, 1980, "Central America", "Salvadoran Archbishop Oscar Romero, an outspoken advocate for the poor, was assassinated while celebrating Mass."),
        HistoryFact(478, 8, 1, 1914, "Caribbean", "Jamaican activist Marcus Garvey founded the Universal Negro Improvement Association, a major Pan-Africanist organization."),
        HistoryFact(479, 2, 27, 1844, "Caribbean", "Juan Pablo Duarte and fellow revolutionaries declared the independence of the Dominican Republic from Haiti."),
        HistoryFact(480, 12, 10, 1984, "South America", "Argentine biochemist Cesar Milstein received the Nobel Prize for developing a technique to produce monoclonal antibodies."),
        HistoryFact(481, 12, 10, 1980, "South America", "Argentine human rights activist Adolfo Perez Esquivel received the Nobel Peace Prize for his nonviolent opposition to military rule."),
        HistoryFact(482, 12, 10, 1936, "South America", "Argentine diplomat Carlos Saavedra Lamas received the Nobel Peace Prize, becoming the first Latin American Nobel laureate."),
        HistoryFact(483, 12, 10, 2016, "South America", "Colombian President Juan Manuel Santos received the Nobel Peace Prize for his efforts to end his country's decades long civil conflict."),
        HistoryFact(484, 12, 10, 2002, "Middle East", "Israeli psychologist Daniel Kahneman received the Nobel Prize in Economics for pioneering the study of behavioral economics."),
        HistoryFact(485, 12, 10, 1994, "Middle East", "Yitzhak Rabin, Shimon Peres, and Yasser Arafat jointly received the Nobel Peace Prize for the Oslo Accords."),
        HistoryFact(486, 12, 10, 2006, "Middle East", "Turkish novelist Orhan Pamuk received the Nobel Prize in Literature."),
        HistoryFact(487, 12, 10, 1988, "Middle East", "Egyptian author Naguib Mahfouz received the Nobel Prize in Literature, the first Arabic language writer to do so."),
        HistoryFact(488, 12, 10, 1978, "Middle East", "Menachem Begin and Anwar Sadat jointly received the Nobel Peace Prize for the Camp David Accords."),
        HistoryFact(489, 12, 10, 1967, "Central America", "Guatemalan writer Miguel Angel Asturias received the Nobel Prize in Literature."),
        HistoryFact(490, 11, 2, 1945, "Central America", "Costa Rica joined the United Nations as one of its earliest member states."),
        HistoryFact(491, 9, 25, 1981, "Central America", "Belize joined the United Nations shortly after gaining independence."),
        HistoryFact(492, 11, 17, 2017, "Caribbean", "Evelyn Wever-Croes was sworn in as the first female Prime Minister of Aruba."),
        HistoryFact(493, 12, 15, 1994, "Oceania", "Palau joined the United Nations as its 185th member state."),
        HistoryFact(494, 10, 26, 1981, "Oceania", "Australia's Great Barrier Reef was inscribed as a UNESCO World Heritage Site."),
        HistoryFact(495, 12, 1, 1948, "Central America", "Costa Rican leader Jose Figueres announced the abolition of the country's military, redirecting the budget toward healthcare and education."),
        HistoryFact(496, 10, 10, 1922, "Caribbean", "Cuba's PWX station made the first radio broadcast in Latin America."),
        HistoryFact(497, 10, 25, 1950, "Caribbean", "Commercial television began in Cuba, the first television broadcasting in the Caribbean."),
        HistoryFact(498, 11, 29, 2018, "Caribbean", "Reggae music, born in Jamaica, was added to UNESCO's list of Intangible Cultural Heritage."),
        HistoryFact(499, 8, 27, 1920, "South America", "A group of Argentine medical students made the first radio broadcast in Latin America, transmitting an opera performance from a Buenos Aires rooftop."),
        HistoryFact(500, 8, 21, 1959, "South America", "Chile's Canal 13 launched, becoming one of Latin America's earliest television networks."),
        HistoryFact(501, 2, 19, 1972, "South America", "Brazil aired its first regular color television broadcast."),
        HistoryFact(502, 2, 4, 1976, "Central America", "A major earthquake struck Guatemala, one of the deadliest natural disasters in the country's history."),
        HistoryFact(503, 12, 23, 1972, "Central America", "A powerful earthquake devastated Managua, the capital of Nicaragua."),
        HistoryFact(504, 10, 24, 1902, "Central America", "The Santa Maria volcano in Guatemala erupted violently, one of the largest volcanic eruptions of the twentieth century."),
        HistoryFact(505, 7, 29, 1968, "Central America", "Costa Rica's Arenal volcano erupted suddenly after centuries of dormancy."),
        HistoryFact(506, 1, 13, 2001, "Central America", "A major earthquake struck El Salvador, triggering landslides across the country."),
        HistoryFact(507, 10, 29, 1998, "Central America", "Hurricane Mitch made landfall in Central America, becoming one of the deadliest Atlantic hurricanes in recorded history."),
        HistoryFact(508, 1, 12, 2010, "Caribbean", "A devastating earthquake struck Haiti near the capital Port au Prince."),
        HistoryFact(509, 10, 10, 1780, "Caribbean", "The Great Hurricane of 1780, the deadliest Atlantic hurricane on record, swept through the Caribbean."),
        HistoryFact(510, 9, 13, 1928, "Caribbean", "The San Felipe Segundo hurricane struck Puerto Rico, one of the strongest storms to hit the island."),
        HistoryFact(511, 5, 22, 1960, "South America", "A magnitude 9.5 earthquake struck southern Chile, the most powerful earthquake ever recorded."),
        HistoryFact(512, 11, 13, 1985, "South America", "The eruption of Colombia's Nevado del Ruiz volcano triggered mudflows that buried the town of Armero."),
        HistoryFact(513, 5, 31, 1970, "South America", "A major earthquake struck Ancash, Peru, triggering a massive landslide on Mount Huascaran."),
        HistoryFact(514, 2, 27, 2010, "South America", "A magnitude 8.8 earthquake struck central Chile, one of the strongest ever recorded."),
        HistoryFact(515, 9, 15, 1835, "South America", "Charles Darwin arrived in the Galapagos Islands, observations that would later shape his theory of evolution."),
        HistoryFact(516, 1, 15, 2022, "Oceania", "The Hunga Tonga volcano erupted in one of the most powerful explosions recorded in over a century, triggering tsunamis across the Pacific."),
        HistoryFact(517, 2, 22, 2011, "Oceania", "A major earthquake struck Christchurch, New Zealand, causing widespread destruction."),
        HistoryFact(518, 2, 3, 1931, "Oceania", "The Hawke's Bay earthquake struck New Zealand, the deadliest natural disaster in the country's history."),
        HistoryFact(519, 12, 25, 1974, "Oceania", "Cyclone Tracy devastated the Australian city of Darwin on Christmas Day."),
        HistoryFact(520, 12, 26, 2003, "Middle East", "A major earthquake struck the city of Bam in Iran, destroying much of its ancient citadel."),
        HistoryFact(521, 8, 17, 1999, "Middle East", "A major earthquake struck northwestern Turkey near Izmit, killing thousands."),
        HistoryFact(522, 2, 6, 2023, "Middle East", "A pair of major earthquakes struck southern Turkey and northern Syria hours apart, killing tens of thousands."),
        HistoryFact(523, 6, 21, 1990, "Middle East", "A major earthquake struck the Manjil and Rudbar region of northern Iran."),
        HistoryFact(524, 9, 29, 2009, "Oceania", "A powerful earthquake near Samoa triggered a tsunami that struck Samoa, American Samoa, and Tonga."),
        HistoryFact(525, 3, 13, 2015, "Oceania", "Cyclone Pam struck Vanuatu, one of the most powerful storms ever recorded in the South Pacific."),
        HistoryFact(526, 1, 14, 1907, "Caribbean", "A major earthquake struck Kingston, Jamaica, destroying much of the city."),
        HistoryFact(527, 6, 25, 1997, "Caribbean", "The Soufriere Hills volcano erupted on Montserrat, burying the capital city of Plymouth."),
        HistoryFact(528, 9, 20, 2017, "Caribbean", "Hurricane Maria struck Puerto Rico and Dominica, causing catastrophic damage across the eastern Caribbean."),
        HistoryFact(529, 1, 31, 1906, "South America", "A massive earthquake off the coast of Ecuador and Colombia generated a Pacific wide tsunami."),
        HistoryFact(530, 1, 25, 1999, "South America", "A major earthquake struck the coffee growing region around Armenia, Colombia."),
        HistoryFact(531, 12, 10, 1947, "South America", "Argentine physiologist Bernardo Houssay received the Nobel Prize for his discoveries about the pituitary gland's role in regulating blood sugar."),
        HistoryFact(532, 12, 10, 1970, "South America", "Argentine biochemist Luis Federico Leloir received the Nobel Prize for discovering how the body stores and converts carbohydrates."),
        HistoryFact(533, 9, 28, 2008, "South America", "Ecuadorians approved a new constitution that became the first in the world to grant legal rights to nature."),
        HistoryFact(534, 12, 10, 1996, "Oceania", "Australian immunologist Peter Doherty received the Nobel Prize for discoveries about how the immune system recognizes virus infected cells."),
        HistoryFact(535, 12, 10, 2009, "Oceania", "Australian born scientist Elizabeth Blackburn received the Nobel Prize for discovering how chromosomes are protected by telomeres."),
        HistoryFact(536, 12, 10, 2005, "Oceania", "Australian scientists Barry Marshall and Robin Warren received the Nobel Prize for discovering the bacterium that causes stomach ulcers."),
        HistoryFact(537, 12, 10, 1960, "Oceania", "Australian virologist Frank Macfarlane Burnet received the Nobel Prize for his theory of acquired immune tolerance."),
        HistoryFact(538, 10, 28, 2015, "Oceania", "The Pacific island nation of Palau created one of the world's largest marine sanctuaries, protecting nearly all of its waters."),
        HistoryFact(539, 12, 10, 1960, "Middle East", "Lebanese heritage scientist Peter Medawar received the Nobel Prize for his discoveries about immune tolerance, work that made organ transplants possible."),
        HistoryFact(540, 12, 10, 2015, "Middle East", "Turkish American biochemist Aziz Sancar received the Nobel Prize for mapping how cells repair damaged DNA."),
        HistoryFact(541, 12, 10, 2009, "Middle East", "Israeli scientist Ada Yonath received the Nobel Prize for mapping the structure of the ribosome, work that led to new antibiotics."),
        HistoryFact(542, 12, 10, 2011, "Middle East", "Israeli scientist Dan Shechtman received the Nobel Prize for discovering quasicrystals, a finding once dismissed by the scientific establishment."),
        HistoryFact(543, 12, 10, 2005, "Middle East", "Egyptian diplomat Mohamed ElBaradei and the International Atomic Energy Agency jointly received the Nobel Peace Prize for efforts to prevent the military use of nuclear energy."),
        HistoryFact(544, 12, 10, 2011, "Middle East", "Yemeni activist Tawakkol Karman received the Nobel Peace Prize, becoming the first Arab woman to win the award."),
        HistoryFact(545, 6, 3, 2018, "Central America", "Guatemala's Volcan de Fuego erupted violently, its most devastating eruption in over four decades."),
        HistoryFact(546, 5, 2, 1621, "Central America", "A major earthquake struck Panama la Vieja, the first significant quake recorded by colonial authorities on the Isthmus of Panama."),
        HistoryFact(547, 1, 20, 1904, "Central America", "The largest earthquake recorded in or near Panama in over a century struck the isthmus."),
        HistoryFact(548, 6, 7, 1917, "Central America", "A major earthquake struck San Salvador, followed by a volcanic eruption that compounded the destruction."),
        HistoryFact(549, 4, 22, 1991, "Central America", "A major earthquake centered near the Costa Rica and Panama border caused widespread destruction on both sides."),
        HistoryFact(550, 12, 2, 2018, "Central America", "Explorers Richard Branson and Fabien Cousteau piloted the first submersible dive to the bottom of Belize's Great Blue Hole, broadcast live."),
        HistoryFact(551, 7, 2, 2019, "South America", "A total solar eclipse swept across Chile and Argentina, drawing crowds of sky watchers."),
        HistoryFact(552, 12, 14, 2020, "South America", "A total solar eclipse crossed Chile and Argentina for the second time in under two years, tracing a path south of the 2019 eclipse."),
        HistoryFact(553, 12, 26, 2019, "Middle East", "An annular solar eclipse traced a ring of fire across Saudi Arabia and the Arabian Peninsula."),
        HistoryFact(554, 11, 14, 2012, "Oceania", "A total solar eclipse crossed northern Australia, one of the few populated places along its path."),
        HistoryFact(555, 2, 26, 1998, "Caribbean", "A total solar eclipse swept across the Caribbean Sea, its path of totality crossing several islands."),
        HistoryFact(556, 10, 12, 1931, "South America", "The Christ the Redeemer statue was inaugurated atop Corcovado mountain overlooking Rio de Janeiro."),
        HistoryFact(557, 11, 12, 2012, "South America", "Yale University completed the return of the last Machu Picchu artifacts to Peru, ending a century long dispute over the Inca treasures."),
        HistoryFact(558, 10, 26, 1985, "Oceania", "After decades of advocacy, the Australian government returned formal title of Uluru to the Anangu, its traditional owners."),
        HistoryFact(559, 10, 26, 2019, "Oceania", "Climbing Uluru was permanently closed to visitors, honoring the long standing wishes of the Anangu traditional owners."),
        HistoryFact(560, 11, 5, 1996, "Middle East", "Construction began on the Sheikh Zayed Grand Mosque in Abu Dhabi, envisioned by the UAE's founding president as a symbol of Islamic unity and tolerance."),
        HistoryFact(561, 10, 16, 2002, "Middle East", "Egypt opened the Bibliotheca Alexandrina, a modern library and cultural center reviving the legacy of the ancient Library of Alexandria."),
        HistoryFact(562, 10, 21, 1897, "Central America", "Costa Rica opened its National Theater, funded by a tax its coffee growers approved on themselves to bring the arts to San Jose."),
        HistoryFact(563, 10, 1, 1908, "Central America", "Panama opened its National Theater in the historic core of Panama City."),
        HistoryFact(564, 11, 10, 1943, "Central America", "Guatemala inaugurated its National Palace, which remains the country's architectural symbol."),
        HistoryFact(565, 10, 2, 2014, "Central America", "Panama opened the Biomuseo, a museum dedicated to the country's own natural history and its role as a bridge between two continents."),
        HistoryFact(566, 4, 28, 2023, "Middle East", "Emirati astronaut Sultan Al Neyadi performed the first spacewalk by an Arab astronaut."),
        HistoryFact(567, 5, 21, 2023, "Middle East", "Saudi biomedical researcher Rayyanah Barnawi launched to the International Space Station, becoming the first Arab woman in space."),
        HistoryFact(568, 3, 29, 2006, "South America", "Marcos Pontes launched to the International Space Station, becoming Brazil's first astronaut."),
        HistoryFact(569, 2, 9, 1993, "South America", "Brazil launched its first entirely domestically built satellite, the Data Collecting Satellite SCD-1."),
        HistoryFact(570, 7, 20, 1987, "Oceania", "New Zealand's Maori Language Act made te reo Maori an official language, the result of decades of Maori led advocacy."),
        HistoryFact(571, 8, 5, 1948, "Caribbean", "Jamaican sprinter Arthur Wint won the men's 400 meters at the London Olympics, his country's first Olympic gold medal, with teammate Herb McKenley taking silver."),
        HistoryFact(572, 7, 24, 1783, "South America", "Simon Bolivar, who would go on to lead independence movements across much of South America, was born in Caracas."),
        HistoryFact(573, 2, 2, 1990, "Africa", "South African President F.W. de Klerk announced the unbanning of the African National Congress and the impending release of Nelson Mandela."),
        HistoryFact(574, 10, 13, 1961, "Africa", "Prince Louis Rwagasore, Burundi's first elected prime minister and independence leader, was assassinated shortly after leading his country to self rule."),
        HistoryFact(575, 2, 8, 1944, "North America", "Harry McAlpin became the first Black journalist accredited to attend a White House press conference."),
        HistoryFact(576, 11, 24, 2001, "Middle East", "Turkey's Grand National Assembly ratified a new civil code granting women equal legal status with men."),
        HistoryFact(577, 11, 27, 1895, "Global", "Alfred Nobel signed his final will, establishing the Nobel Prizes to be awarded in his name."),
        HistoryFact(578, 2, 13, 2008, "Oceania", "Australian Prime Minister Kevin Rudd delivered the National Apology to the Stolen Generations, formally acknowledging the harm done to Aboriginal and Torres Strait Islander peoples."),
        HistoryFact(579, 4, 16, 2018, "North America", "Kendrick Lamar's album DAMN. won the Pulitzer Prize for Music, making him the first artist outside classical and jazz to receive the honor."),
        HistoryFact(580, 4, 20, 2016, "North America", "The U.S. Treasury announced plans to feature Harriet Tubman on the twenty dollar bill, honoring the abolitionist and Underground Railroad leader."),
        HistoryFact(581, 8, 22, 1791, "Caribbean", "Enslaved people in Saint Domingue rose up in a mass uprising that began the Haitian Revolution, the only slave revolt in history to lead to the founding of a nation."),
        HistoryFact(582, 6, 9, 1963, "North America", "Civil rights activist Fannie Lou Hamer was arrested and brutally beaten in Winona, Mississippi, an ordeal she later testified about, galvanizing the voting rights movement."),
    )
}
