package com.tyshi00.trinkets

// Original morning motivational prompts, written for Trinkets, spanning
// gentle through energizing so people can pick what matches their morning.
object TrinketsMorningPrompts {
    val ALL: List<MorningPrompt> = listOf(
        // Gentle
        MorningPrompt(1, "You don't have to have today figured out before you get out of bed. Just take the first small step.", MotivationIntensity.GENTLE),
        MorningPrompt(2, "It's okay to move slowly this morning. Slow is still moving.", MotivationIntensity.GENTLE),
        MorningPrompt(3, "Whatever yesterday was, it's finished now. This morning is a quiet, clean page.", MotivationIntensity.GENTLE),
        MorningPrompt(4, "You are allowed to take today one hour at a time.", MotivationIntensity.GENTLE),
        MorningPrompt(5, "Be as patient with yourself this morning as you would be with someone you love.", MotivationIntensity.GENTLE),
        MorningPrompt(6, "Nothing has to be perfect today. It just has to be honest.", MotivationIntensity.GENTLE),
        MorningPrompt(7, "You've survived every hard day so far. That's worth acknowledging quietly before this one begins.", MotivationIntensity.GENTLE),
        MorningPrompt(8, "Let today be simple. Simple is enough.", MotivationIntensity.GENTLE),
        MorningPrompt(9, "You don't need to earn rest today. You're allowed to take it as needed.", MotivationIntensity.GENTLE),
        MorningPrompt(10, "One kind thing for yourself this morning, that's a good enough place to start.", MotivationIntensity.GENTLE),
        MorningPrompt(11, "You're not behind. You're exactly where your today needs you to be.", MotivationIntensity.GENTLE),
        MorningPrompt(12, "Breathe in slowly. There's no rush waiting for you at the bottom of that breath.", MotivationIntensity.GENTLE),
        MorningPrompt(13, "It's fine if today is just about getting through it gently.", MotivationIntensity.GENTLE),
        MorningPrompt(14, "Let your first thought this morning be soft, not a demand.", MotivationIntensity.GENTLE),
        MorningPrompt(15, "You don't have to feel ready. You just have to begin.", MotivationIntensity.GENTLE),
        MorningPrompt(16, "This morning, choose ease wherever you honestly can.", MotivationIntensity.GENTLE),
        MorningPrompt(17, "You are more than your to-do list today.", MotivationIntensity.GENTLE),
        MorningPrompt(18, "A quiet morning is still a good morning.", MotivationIntensity.GENTLE),
        MorningPrompt(19, "Whatever you can manage today is enough.", MotivationIntensity.GENTLE),
        MorningPrompt(20, "Let today unfold instead of forcing it into shape.", MotivationIntensity.GENTLE),
        MorningPrompt(21, "You get to decide what pace today moves at.", MotivationIntensity.GENTLE),
        MorningPrompt(22, "Small steps taken gently still get you somewhere.", MotivationIntensity.GENTLE),
        MorningPrompt(23, "This morning, be the calm you wish someone would offer you.", MotivationIntensity.GENTLE),
        MorningPrompt(24, "You don't owe today your best. You only owe it your honest effort.", MotivationIntensity.GENTLE),
        MorningPrompt(25, "Let this be a morning where you're gentle with your own mistakes.", MotivationIntensity.GENTLE),
        MorningPrompt(26, "Today can be soft around the edges. That's alright.", MotivationIntensity.GENTLE),
        MorningPrompt(27, "You're allowed to start slow and build from there.", MotivationIntensity.GENTLE),
        MorningPrompt(28, "This morning, notice one small thing that's actually going right.", MotivationIntensity.GENTLE),
        MorningPrompt(29, "You don't need permission to take care of yourself today.", MotivationIntensity.GENTLE),
        MorningPrompt(30, "Let today be measured in kindness, not just output.", MotivationIntensity.GENTLE),

        // Steady
        MorningPrompt(31, "Today doesn't need to be extraordinary. It just needs your steady, honest effort.", MotivationIntensity.STEADY),
        MorningPrompt(32, "Pick one thing that matters and give it your full attention this morning.", MotivationIntensity.STEADY),
        MorningPrompt(33, "Consistency beats intensity. Show up today the way you plan to show up tomorrow.", MotivationIntensity.STEADY),
        MorningPrompt(34, "You already know what today's first real step is. Take it before you overthink it.", MotivationIntensity.STEADY),
        MorningPrompt(35, "Progress doesn't have to be dramatic to count. Move the needle, even slightly.", MotivationIntensity.STEADY),
        MorningPrompt(36, "Decide now what 'a good day' looks like, so you'll recognize it when it happens.", MotivationIntensity.STEADY),
        MorningPrompt(37, "Today is a fresh set of hours. Spend them on something you'll be glad you did.", MotivationIntensity.STEADY),
        MorningPrompt(38, "You don't need motivation to start, just the decision to begin anyway.", MotivationIntensity.STEADY),
        MorningPrompt(39, "Whatever's on your list today, start with the thing you're avoiding. It gets lighter once it's moving.", MotivationIntensity.STEADY),
        MorningPrompt(40, "Build today on top of yesterday's effort, not from scratch.", MotivationIntensity.STEADY),
        MorningPrompt(41, "Show up for your own goals today the way you'd show up for someone you care about.", MotivationIntensity.STEADY),
        MorningPrompt(42, "The work you do today doesn't have to be seen to matter.", MotivationIntensity.STEADY),
        MorningPrompt(43, "Today, choose the harder right thing over the easier almost-right thing.", MotivationIntensity.STEADY),
        MorningPrompt(44, "Aim for steady progress today, not a finish line.", MotivationIntensity.STEADY),
        MorningPrompt(45, "You have exactly what you need to handle today's first task. Start there.", MotivationIntensity.STEADY),
        MorningPrompt(46, "Let today be the day you follow through on something small you've been putting off.", MotivationIntensity.STEADY),
        MorningPrompt(47, "Discipline this morning is just a promise you're keeping to your future self.", MotivationIntensity.STEADY),
        MorningPrompt(48, "You don't have to want to do it. You just have to do it anyway.", MotivationIntensity.STEADY),
        MorningPrompt(49, "Today's effort compounds. It's doing more than it looks like it's doing.", MotivationIntensity.STEADY),
        MorningPrompt(50, "Set one honest intention for today and let it guide your first decision.", MotivationIntensity.STEADY),
        MorningPrompt(51, "You've prepared for moments like this. Trust the work you've already put in.", MotivationIntensity.STEADY),
        MorningPrompt(52, "Today, be the reason your own plan actually works.", MotivationIntensity.STEADY),
        MorningPrompt(53, "Focus on what's in front of you. The rest of the day will take care of itself in time.", MotivationIntensity.STEADY),
        MorningPrompt(54, "Every solid habit started as a single decision, repeated. Make today's decision.", MotivationIntensity.STEADY),
        MorningPrompt(55, "You don't need a perfect plan. You need a first move.", MotivationIntensity.STEADY),
        MorningPrompt(56, "Let today's effort be quiet, steady, and impossible to ignore in a month.", MotivationIntensity.STEADY),
        MorningPrompt(57, "Today, do the unglamorous work that no one claps for. It's the work that adds up.", MotivationIntensity.STEADY),
        MorningPrompt(58, "Trust that showing up today, even imperfectly, is what builds momentum.", MotivationIntensity.STEADY),
        MorningPrompt(59, "You're capable of more today than you were giving yourself credit for yesterday.", MotivationIntensity.STEADY),
        MorningPrompt(60, "Start today's hardest task while your energy is freshest.", MotivationIntensity.STEADY),

        // Energizing
        MorningPrompt(61, "Get up. Today has been waiting for you, so go meet it head on.", MotivationIntensity.ENERGIZING),
        MorningPrompt(62, "You didn't come this far to only come this far. Push today.", MotivationIntensity.ENERGIZING),
        MorningPrompt(63, "Today is a blank canvas and you're holding the only brush that matters.", MotivationIntensity.ENERGIZING),
        MorningPrompt(64, "Wake up like you've got something to prove, because you do, to yourself.", MotivationIntensity.ENERGIZING),
        MorningPrompt(65, "Let's go. Today doesn't wait for perfect conditions, and neither should you.", MotivationIntensity.ENERGIZING),
        MorningPrompt(66, "Attack today's first task like it's the only thing standing between you and momentum.", MotivationIntensity.ENERGIZING),
        MorningPrompt(67, "You have one shot at today. Make it loud.", MotivationIntensity.ENERGIZING),
        MorningPrompt(68, "Stop negotiating with the snooze button. Today's already moving without you.", MotivationIntensity.ENERGIZING),
        MorningPrompt(69, "Show today who's in charge. Hint: it's you.", MotivationIntensity.ENERGIZING),
        MorningPrompt(70, "Today isn't going to hand you anything. Go take it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(71, "Your future self is counting on what you do in the next hour. Don't let them down.", MotivationIntensity.ENERGIZING),
        MorningPrompt(72, "Come out swinging today. You've earned the confidence.", MotivationIntensity.ENERGIZING),
        MorningPrompt(73, "Today is your rematch with yesterday. Win it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(74, "No more warming up. Today, you're already ready.", MotivationIntensity.ENERGIZING),
        MorningPrompt(75, "Bring the same energy to today that you'd bring to something you actually love.", MotivationIntensity.ENERGIZING),
        MorningPrompt(76, "Somewhere out there, someone is already working toward the life you want. Beat them out of bed.", MotivationIntensity.ENERGIZING),
        MorningPrompt(77, "Today's excuses were already used up yesterday. Show up anyway.", MotivationIntensity.ENERGIZING),
        MorningPrompt(78, "You're not tired. You're underused. Go use yourself well today.", MotivationIntensity.ENERGIZING),
        MorningPrompt(79, "Today, move like the outcome actually matters to you, because it does.", MotivationIntensity.ENERGIZING),
        MorningPrompt(80, "Get loud with your effort today. Quiet doubt doesn't stand a chance against it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(81, "Today's a fight worth having. Step into it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(82, "Whatever you're building, today is another brick. Set it well.", MotivationIntensity.ENERGIZING),
        MorningPrompt(83, "You want it? Prove it before noon.", MotivationIntensity.ENERGIZING),
        MorningPrompt(84, "Today, be relentless about the one thing that actually matters.", MotivationIntensity.ENERGIZING),
        MorningPrompt(85, "Stop waiting to feel motivated. Move first, and the motivation will catch up.", MotivationIntensity.ENERGIZING),
        MorningPrompt(86, "Today's a great day to become someone your past self would be proud of.", MotivationIntensity.ENERGIZING),
        MorningPrompt(87, "Chase today down. Don't let it just happen to you.", MotivationIntensity.ENERGIZING),
        MorningPrompt(88, "You've got one life and today's your shot at a piece of it. Take it seriously.", MotivationIntensity.ENERGIZING),
        MorningPrompt(89, "Whatever's hard today, do it first, before anything else gets in the way.", MotivationIntensity.ENERGIZING),
        MorningPrompt(90, "Rise like today already belongs to you.", MotivationIntensity.ENERGIZING),

        // Gentle, continued
        MorningPrompt(91, "This morning, you don't have to prove anything to anyone.", MotivationIntensity.GENTLE),
        MorningPrompt(92, "Let today be as light as it wants to be.", MotivationIntensity.GENTLE),
        MorningPrompt(93, "You're allowed to move at the pace that actually feels true today.", MotivationIntensity.GENTLE),
        MorningPrompt(94, "A single small step counts as progress this morning.", MotivationIntensity.GENTLE),
        MorningPrompt(95, "Give yourself the same patience you'd offer a good friend.", MotivationIntensity.GENTLE),
        MorningPrompt(96, "You don't have to feel strong yet. You just have to begin gently.", MotivationIntensity.GENTLE),
        MorningPrompt(97, "It's okay if today looks smaller than yesterday's plans.", MotivationIntensity.GENTLE),
        MorningPrompt(98, "Let your first breath this morning be an easy one.", MotivationIntensity.GENTLE),
        MorningPrompt(99, "Whatever weighs on you, set it down for just this first hour.", MotivationIntensity.GENTLE),
        MorningPrompt(100, "You are not required to have all the answers this morning.", MotivationIntensity.GENTLE),
        MorningPrompt(101, "Today can simply be about getting through it with a little grace.", MotivationIntensity.GENTLE),
        MorningPrompt(102, "You are allowed to start again, as many times as you need to.", MotivationIntensity.GENTLE),
        MorningPrompt(103, "Let today unfold without forcing every piece into place.", MotivationIntensity.GENTLE),
        MorningPrompt(104, "There's no prize for rushing this morning. Take it slow if you need to.", MotivationIntensity.GENTLE),
        MorningPrompt(105, "You can be gentle with yourself and still get where you're going.", MotivationIntensity.GENTLE),
        MorningPrompt(106, "This morning, let good enough actually be enough.", MotivationIntensity.GENTLE),
        MorningPrompt(107, "You're not falling behind. You're simply moving at your own honest pace.", MotivationIntensity.GENTLE),
        MorningPrompt(108, "Let today hold space for rest, even in the middle of everything else.", MotivationIntensity.GENTLE),
        MorningPrompt(109, "You don't need a big plan this morning, just a next small step.", MotivationIntensity.GENTLE),
        MorningPrompt(110, "Be as kind to yourself this morning as the day deserves you to be.", MotivationIntensity.GENTLE),
        MorningPrompt(111, "It's alright to need a little more time to feel ready.", MotivationIntensity.GENTLE),
        MorningPrompt(112, "Let today be soft where it can be, and steady where it must be.", MotivationIntensity.GENTLE),
        MorningPrompt(113, "You're allowed to protect your energy this morning.", MotivationIntensity.GENTLE),
        MorningPrompt(114, "Whatever yesterday held, this morning is a quiet new beginning.", MotivationIntensity.GENTLE),
        MorningPrompt(115, "You don't have to carry everything today. Set some of it down.", MotivationIntensity.GENTLE),
        MorningPrompt(116, "This morning, choose the version of today that feels sustainable.", MotivationIntensity.GENTLE),
        MorningPrompt(117, "You can be tired and still be doing enough.", MotivationIntensity.GENTLE),
        MorningPrompt(118, "Let today be measured in small, honest efforts, not grand ones.", MotivationIntensity.GENTLE),
        MorningPrompt(119, "You're allowed to take today one small task at a time.", MotivationIntensity.GENTLE),
        MorningPrompt(120, "Be gentle with the parts of yourself that are still waking up.", MotivationIntensity.GENTLE),

        // Steady, continued
        MorningPrompt(121, "Today's effort doesn't need to be loud to count.", MotivationIntensity.STEADY),
        MorningPrompt(122, "Pick the one task that actually matters and start there.", MotivationIntensity.STEADY),
        MorningPrompt(123, "You don't need to feel ready. You just need to begin.", MotivationIntensity.STEADY),
        MorningPrompt(124, "Today, keep the promise you made to yourself yesterday.", MotivationIntensity.STEADY),
        MorningPrompt(125, "Small, steady effort today beats a big burst you can't sustain.", MotivationIntensity.STEADY),
        MorningPrompt(126, "Show up for today the same way you'd want to be shown up for.", MotivationIntensity.STEADY),
        MorningPrompt(127, "You already have what you need to take the first step.", MotivationIntensity.STEADY),
        MorningPrompt(128, "Let today's work be honest, even if it isn't flashy.", MotivationIntensity.STEADY),
        MorningPrompt(129, "Start with the task you've been putting off. It gets lighter once you begin.", MotivationIntensity.STEADY),
        MorningPrompt(130, "Today, choose consistency over intensity.", MotivationIntensity.STEADY),
        MorningPrompt(131, "You don't need permission to take today seriously.", MotivationIntensity.STEADY),
        MorningPrompt(132, "Build on what you did yesterday. You don't have to start from zero.", MotivationIntensity.STEADY),
        MorningPrompt(133, "The work you do today may not be seen, but it still matters.", MotivationIntensity.STEADY),
        MorningPrompt(134, "Choose the harder right thing today over the easier almost right thing.", MotivationIntensity.STEADY),
        MorningPrompt(135, "Today calls for steady progress, not a finish line.", MotivationIntensity.STEADY),
        MorningPrompt(136, "You have what you need for today's first task. Start there.", MotivationIntensity.STEADY),
        MorningPrompt(137, "Follow through today on something small you've been putting off.", MotivationIntensity.STEADY),
        MorningPrompt(138, "Discipline this morning is a promise kept to your future self.", MotivationIntensity.STEADY),
        MorningPrompt(139, "You don't have to want to do it. Just do it anyway.", MotivationIntensity.STEADY),
        MorningPrompt(140, "Today's effort compounds, even when it doesn't look like much.", MotivationIntensity.STEADY),
        MorningPrompt(141, "Set one honest intention today and let it guide your first decision.", MotivationIntensity.STEADY),
        MorningPrompt(142, "Trust the preparation you've already put in.", MotivationIntensity.STEADY),
        MorningPrompt(143, "Be the reason your own plan actually works today.", MotivationIntensity.STEADY),
        MorningPrompt(144, "Focus on what's right in front of you. The rest will come into view.", MotivationIntensity.STEADY),
        MorningPrompt(145, "Every solid habit started with a single decision, repeated. Make today's decision.", MotivationIntensity.STEADY),
        MorningPrompt(146, "You don't need a perfect plan, just a first move.", MotivationIntensity.STEADY),
        MorningPrompt(147, "Let today's effort be the kind that only shows its results weeks from now.", MotivationIntensity.STEADY),
        MorningPrompt(148, "Do the unglamorous work today that no one claps for.", MotivationIntensity.STEADY),
        MorningPrompt(149, "Trust that a single ordinary day of effort still moves the whole plan forward.", MotivationIntensity.STEADY),
        MorningPrompt(150, "Tackle today's least appealing task before it has a chance to grow in your mind.", MotivationIntensity.STEADY),

        // Energizing, continued
        MorningPrompt(151, "Wake up ready. Today's already moving, so catch up to it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(152, "You've got one shot at today. Make it count.", MotivationIntensity.ENERGIZING),
        MorningPrompt(153, "Today is your chance to outdo yesterday. Take it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(154, "Push past the resistance. That's where the real progress lives.", MotivationIntensity.ENERGIZING),
        MorningPrompt(155, "Stop waiting for the perfect moment. Today is the moment.", MotivationIntensity.ENERGIZING),
        MorningPrompt(156, "Get after it. Today doesn't reward the hesitant.", MotivationIntensity.ENERGIZING),
        MorningPrompt(157, "You are more capable than the excuses you're making right now.", MotivationIntensity.ENERGIZING),
        MorningPrompt(158, "Move like today already matters, because it does.", MotivationIntensity.ENERGIZING),
        MorningPrompt(159, "The version of you that you want to become starts today, right now.", MotivationIntensity.ENERGIZING),
        MorningPrompt(160, "Stop asking if you're ready and start moving anyway.", MotivationIntensity.ENERGIZING),
        MorningPrompt(161, "Show today exactly what you're made of.", MotivationIntensity.ENERGIZING),
        MorningPrompt(162, "Today's a fresh chance to close the gap between where you are and where you want to be.", MotivationIntensity.ENERGIZING),
        MorningPrompt(163, "Get up and get moving. Momentum is built, not found.", MotivationIntensity.ENERGIZING),
        MorningPrompt(164, "Whatever's holding you back this morning, outwork it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(165, "Today rewards the ones who actually show up.", MotivationIntensity.ENERGIZING),
        MorningPrompt(166, "You didn't wake up to be average today.", MotivationIntensity.ENERGIZING),
        MorningPrompt(167, "Bring your full effort to the very first task. Set the tone.", MotivationIntensity.ENERGIZING),
        MorningPrompt(168, "Today's a great day to prove your doubts wrong.", MotivationIntensity.ENERGIZING),
        MorningPrompt(169, "Move fast, move loud, and let today feel your energy.", MotivationIntensity.ENERGIZING),
        MorningPrompt(170, "Stop overthinking it. Just start.", MotivationIntensity.ENERGIZING),
        MorningPrompt(171, "Chase today like it owes you something, because it does.", MotivationIntensity.ENERGIZING),
        MorningPrompt(172, "You are the only thing standing between today and greatness. Get out of the way.", MotivationIntensity.ENERGIZING),
        MorningPrompt(173, "Today's not for coasting. Bring your best.", MotivationIntensity.ENERGIZING),
        MorningPrompt(174, "You've trained for moments exactly like today. Trust it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(175, "Today is a fight worth showing up for. Show up loud.", MotivationIntensity.ENERGIZING),
        MorningPrompt(176, "Turn today's pressure into fuel.", MotivationIntensity.ENERGIZING),
        MorningPrompt(177, "Stop negotiating with your own excuses.", MotivationIntensity.ENERGIZING),
        MorningPrompt(178, "You have everything you need to make today count. Use it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(179, "Today's the day you stop planning to start and actually start.", MotivationIntensity.ENERGIZING),
        MorningPrompt(180, "Own today from the first minute. Don't let it own you.", MotivationIntensity.ENERGIZING),

        // Gentle, final set
        MorningPrompt(181, "You are enough this morning, exactly as you are.", MotivationIntensity.GENTLE),
        MorningPrompt(182, "Let this morning start with one deep, unhurried breath.", MotivationIntensity.GENTLE),
        MorningPrompt(183, "You don't owe today an explanation for needing to go slow.", MotivationIntensity.GENTLE),
        MorningPrompt(184, "Whatever today holds, you're allowed to meet it softly.", MotivationIntensity.GENTLE),
        MorningPrompt(185, "This morning, let yourself be a beginner again if you need to be.", MotivationIntensity.GENTLE),
        MorningPrompt(186, "You can care for yourself and still care for today's tasks.", MotivationIntensity.GENTLE),
        MorningPrompt(187, "Let today's first hour be free of judgment.", MotivationIntensity.GENTLE),
        MorningPrompt(188, "You are allowed to rest before you've earned it.", MotivationIntensity.GENTLE),
        MorningPrompt(189, "This morning, choose the gentlest version of getting started.", MotivationIntensity.GENTLE),
        MorningPrompt(190, "You don't need to have it all figured out before breakfast.", MotivationIntensity.GENTLE),
        MorningPrompt(191, "Let today be simple, even if simple feels small.", MotivationIntensity.GENTLE),
        MorningPrompt(192, "You are allowed to ask for help this morning.", MotivationIntensity.GENTLE),
        MorningPrompt(193, "This morning, let go of anything that isn't actually yours to carry.", MotivationIntensity.GENTLE),
        MorningPrompt(194, "You can be uncertain and still be okay.", MotivationIntensity.GENTLE),
        MorningPrompt(195, "Let today's pace be dictated by kindness, not urgency.", MotivationIntensity.GENTLE),
        MorningPrompt(196, "You don't have to smile through today if you don't feel like it.", MotivationIntensity.GENTLE),
        MorningPrompt(197, "This morning, let quiet be enough.", MotivationIntensity.GENTLE),
        MorningPrompt(198, "You are allowed to change your plans today if you need to.", MotivationIntensity.GENTLE),
        MorningPrompt(199, "Let today's first task be small enough to actually finish.", MotivationIntensity.GENTLE),
        MorningPrompt(200, "You don't need to earn your morning coffee with productivity.", MotivationIntensity.GENTLE),
        MorningPrompt(201, "This morning, let yourself off the hook for yesterday.", MotivationIntensity.GENTLE),
        MorningPrompt(202, "You are allowed to move through today at your own honest speed.", MotivationIntensity.GENTLE),
        MorningPrompt(203, "Let today hold room for both effort and softness.", MotivationIntensity.GENTLE),
        MorningPrompt(204, "You don't have to have energy you don't have. Work with what's here.", MotivationIntensity.GENTLE),
        MorningPrompt(205, "This morning, let one small comfort be enough to start the day right.", MotivationIntensity.GENTLE),
        MorningPrompt(206, "You are allowed to take today slower than everyone around you.", MotivationIntensity.GENTLE),
        MorningPrompt(207, "Let today's to-do list be shorter than yesterday's, if that's what you need.", MotivationIntensity.GENTLE),
        MorningPrompt(208, "You don't need to prove your worth this morning. It isn't up for debate.", MotivationIntensity.GENTLE),
        MorningPrompt(209, "This morning, let stillness count as something too.", MotivationIntensity.GENTLE),
        MorningPrompt(210, "You are allowed to begin again, gently, as many times as it takes.", MotivationIntensity.GENTLE),

        // Steady, final set
        MorningPrompt(211, "Today's task list doesn't need to be long, just honest.", MotivationIntensity.STEADY),
        MorningPrompt(212, "Show up today the way you'd want to be remembered showing up.", MotivationIntensity.STEADY),
        MorningPrompt(213, "You've handled hard mornings before. You can handle this one.", MotivationIntensity.STEADY),
        MorningPrompt(214, "Let today's first win be small, deliberate, and yours.", MotivationIntensity.STEADY),
        MorningPrompt(215, "Today calls for follow through, not just good intentions.", MotivationIntensity.STEADY),
        MorningPrompt(216, "Trust the plan you made yesterday and simply execute it today.", MotivationIntensity.STEADY),
        MorningPrompt(217, "You don't need a burst of inspiration, just a decision to begin.", MotivationIntensity.STEADY),
        MorningPrompt(218, "Let today's effort match your actual values, not just your habits.", MotivationIntensity.STEADY),
        MorningPrompt(219, "Today is a good day to keep a promise, especially one made to yourself.", MotivationIntensity.STEADY),
        MorningPrompt(220, "Show up for the boring parts of today. That's where progress lives.", MotivationIntensity.STEADY),
        MorningPrompt(221, "You have enough today to take the next honest step.", MotivationIntensity.STEADY),
        MorningPrompt(222, "Let today's work be steady rather than dramatic.", MotivationIntensity.STEADY),
        MorningPrompt(223, "Today's a good day to close the gap between what you say and what you do.", MotivationIntensity.STEADY),
        MorningPrompt(224, "Choose the task that actually moves things forward, not just the easy one.", MotivationIntensity.STEADY),
        MorningPrompt(225, "Today, let discipline do the talking instead of motivation.", MotivationIntensity.STEADY),
        MorningPrompt(226, "You built momentum before. Today, add to it.", MotivationIntensity.STEADY),
        MorningPrompt(227, "Let today's decisions reflect who you're actually trying to become.", MotivationIntensity.STEADY),
        MorningPrompt(228, "Today's effort doesn't need applause to matter.", MotivationIntensity.STEADY),
        MorningPrompt(229, "Trust that consistency, more than intensity, is what gets you there.", MotivationIntensity.STEADY),
        MorningPrompt(230, "Today, start with the task you'd regret not doing.", MotivationIntensity.STEADY),
        MorningPrompt(231, "Let today's plan be simple enough to actually follow through on.", MotivationIntensity.STEADY),
        MorningPrompt(232, "Today calls for steady hands and a clear head. Bring both.", MotivationIntensity.STEADY),
        MorningPrompt(233, "You don't need to feel motivated to be disciplined today.", MotivationIntensity.STEADY),
        MorningPrompt(234, "Let today's small wins add up to something real by tonight.", MotivationIntensity.STEADY),
        MorningPrompt(235, "Today's a good day to finish what you started yesterday.", MotivationIntensity.STEADY),
        MorningPrompt(236, "Show up today, even if it's imperfect. Imperfect beats absent.", MotivationIntensity.STEADY),
        MorningPrompt(237, "Let today's effort be steady enough to trust tomorrow.", MotivationIntensity.STEADY),
        MorningPrompt(238, "Today is built one deliberate choice at a time. Start making them.", MotivationIntensity.STEADY),
        MorningPrompt(239, "You don't need certainty to take today's next step, just willingness.", MotivationIntensity.STEADY),
        MorningPrompt(240, "Let today be the day steady effort quietly outpaces doubt.", MotivationIntensity.STEADY),

        // Energizing, final set
        MorningPrompt(241, "Today's not asking for perfect. It's asking for all in.", MotivationIntensity.ENERGIZING),
        MorningPrompt(242, "Get up and make today answer to you.", MotivationIntensity.ENERGIZING),
        MorningPrompt(243, "You've got fire in you this morning. Use it before it cools.", MotivationIntensity.ENERGIZING),
        MorningPrompt(244, "Today's a battlefield of small decisions. Win the first one.", MotivationIntensity.ENERGIZING),
        MorningPrompt(245, "Stop waiting for permission to go hard today.", MotivationIntensity.ENERGIZING),
        MorningPrompt(246, "Today's yours to seize, so seize it before it slips by.", MotivationIntensity.ENERGIZING),
        MorningPrompt(247, "Bring the energy today that you wish you had yesterday.", MotivationIntensity.ENERGIZING),
        MorningPrompt(248, "You weren't built to sit on the sidelines of your own life. Get moving.", MotivationIntensity.ENERGIZING),
        MorningPrompt(249, "Today's a great day to make your effort impossible to ignore.", MotivationIntensity.ENERGIZING),
        MorningPrompt(250, "Get after today like it's the only shot you're getting.", MotivationIntensity.ENERGIZING),
        MorningPrompt(251, "You have more fight in you than today's excuses can handle.", MotivationIntensity.ENERGIZING),
        MorningPrompt(252, "Today's a day to move first and think later. Get going.", MotivationIntensity.ENERGIZING),
        MorningPrompt(253, "Show today you're not the same person who let yesterday slip.", MotivationIntensity.ENERGIZING),
        MorningPrompt(254, "Today rewards the ones who refuse to wait for the perfect moment.", MotivationIntensity.ENERGIZING),
        MorningPrompt(255, "Bring your loudest effort to the quietest task today.", MotivationIntensity.ENERGIZING),
        MorningPrompt(256, "Today's a day to prove something to yourself, not to anyone else.", MotivationIntensity.ENERGIZING),
        MorningPrompt(257, "Get up like today has been waiting for exactly you.", MotivationIntensity.ENERGIZING),
        MorningPrompt(258, "You don't need the whole plan today, just the first bold move.", MotivationIntensity.ENERGIZING),
        MorningPrompt(259, "Today's a good day to be relentless about the one thing that matters most.", MotivationIntensity.ENERGIZING),
        MorningPrompt(260, "Stop asking if you can. Start proving that you will.", MotivationIntensity.ENERGIZING),
        MorningPrompt(261, "Today's momentum starts the second you get out of bed. Don't waste it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(262, "You've got one life and today's another shot at it. Take it seriously.", MotivationIntensity.ENERGIZING),
        MorningPrompt(263, "Today's a day to outwork the doubt in your own head.", MotivationIntensity.ENERGIZING),
        MorningPrompt(264, "Get moving before your excuses catch up to you.", MotivationIntensity.ENERGIZING),
        MorningPrompt(265, "Today's a day to make the hard choice look easy through sheer effort.", MotivationIntensity.ENERGIZING),
        MorningPrompt(266, "You don't rise to the occasion. You fall to the level of your preparation, so prepare hard today.", MotivationIntensity.ENERGIZING),
        MorningPrompt(267, "Today's a great day to become someone your future self respects.", MotivationIntensity.ENERGIZING),
        MorningPrompt(268, "Stop coasting. Today's asking for your full attention.", MotivationIntensity.ENERGIZING),
        MorningPrompt(269, "You've got the tools. Today's about using every one of them.", MotivationIntensity.ENERGIZING),
        MorningPrompt(270, "Rise today like the outcome actually depends on you, because it does.", MotivationIntensity.ENERGIZING),

        // Gentle, closing set
        MorningPrompt(271, "This morning, let your only job be showing up as you are.", MotivationIntensity.GENTLE),
        MorningPrompt(272, "You don't need to chase today. You're allowed to just walk alongside it.", MotivationIntensity.GENTLE),
        MorningPrompt(273, "Let today's first success simply be getting out of bed.", MotivationIntensity.GENTLE),
        MorningPrompt(274, "You are allowed to feel behind and still be exactly on time for your own life.", MotivationIntensity.GENTLE),
        MorningPrompt(275, "This morning, choose whichever task feels lightest to carry first.", MotivationIntensity.GENTLE),
        MorningPrompt(276, "You don't need to fix everything today. Just tend to one small thing.", MotivationIntensity.GENTLE),
        MorningPrompt(277, "Let today be gentle on the parts of you still healing.", MotivationIntensity.GENTLE),
        MorningPrompt(278, "You are allowed to want less from today than you wanted yesterday.", MotivationIntensity.GENTLE),
        MorningPrompt(279, "This morning, let comfort be a valid choice, not a consolation prize.", MotivationIntensity.GENTLE),
        MorningPrompt(280, "You don't need a reason to rest today. Rest is reason enough.", MotivationIntensity.GENTLE),
        MorningPrompt(281, "Let today hold whatever pace keeps you kind to yourself.", MotivationIntensity.GENTLE),
        MorningPrompt(282, "You are allowed to let today be ordinary.", MotivationIntensity.GENTLE),
        MorningPrompt(283, "This morning, let your effort be measured in care, not output.", MotivationIntensity.GENTLE),
        MorningPrompt(284, "You don't have to carry today's weight all at once. Set some down for later.", MotivationIntensity.GENTLE),
        MorningPrompt(285, "Let today start with one small thing that makes you feel human again.", MotivationIntensity.GENTLE),
        MorningPrompt(286, "You are allowed to be proud of simply making it to this morning.", MotivationIntensity.GENTLE),
        MorningPrompt(287, "This morning, let softness be its own kind of strength.", MotivationIntensity.GENTLE),
        MorningPrompt(288, "You don't need today to be productive to be worthwhile.", MotivationIntensity.GENTLE),
        MorningPrompt(289, "Let today's list be short enough to actually breathe through.", MotivationIntensity.GENTLE),
        MorningPrompt(290, "You are allowed to need today to be easier than usual.", MotivationIntensity.GENTLE),
        MorningPrompt(291, "This morning, let yourself off the hook for feeling behind.", MotivationIntensity.GENTLE),
        MorningPrompt(292, "You don't have to earn rest by suffering first.", MotivationIntensity.GENTLE),
        MorningPrompt(293, "Let today's kindness start with the person in the mirror.", MotivationIntensity.GENTLE),
        MorningPrompt(294, "You are allowed to take up only the space you actually have today.", MotivationIntensity.GENTLE),
        MorningPrompt(295, "This morning, let good intentions count for something, even unfinished.", MotivationIntensity.GENTLE),
        MorningPrompt(296, "You don't need to have your feelings sorted out before starting the day.", MotivationIntensity.GENTLE),
        MorningPrompt(297, "Let today be a day you simply get through with a little tenderness.", MotivationIntensity.GENTLE),
        MorningPrompt(298, "You are allowed to move through today softly, without apology.", MotivationIntensity.GENTLE),
        MorningPrompt(299, "This morning, let one honest breath be the whole plan for now.", MotivationIntensity.GENTLE),
        MorningPrompt(300, "You don't need permission to be gentle with yourself today. Consider this it.", MotivationIntensity.GENTLE),

        // Steady, closing set
        MorningPrompt(301, "Today's success is built from a series of unremarkable good choices.", MotivationIntensity.STEADY),
        MorningPrompt(302, "Let today's plan be simple enough to actually finish.", MotivationIntensity.STEADY),
        MorningPrompt(303, "You've done hard mornings before. Bring that same steadiness today.", MotivationIntensity.STEADY),
        MorningPrompt(304, "Today, let your actions match the person you say you want to be.", MotivationIntensity.STEADY),
        MorningPrompt(305, "Start today's biggest task before doubt gets a say in it.", MotivationIntensity.STEADY),
        MorningPrompt(306, "Let today's effort be steady enough that tomorrow trusts it too.", MotivationIntensity.STEADY),
        MorningPrompt(307, "Today calls for showing up, not showing off.", MotivationIntensity.STEADY),
        MorningPrompt(308, "You have enough today to take one honest, deliberate step forward.", MotivationIntensity.STEADY),
        MorningPrompt(309, "Let today's first hour set the tone for the rest of the day.", MotivationIntensity.STEADY),
        MorningPrompt(310, "Today's a good day to do the thing you keep meaning to start.", MotivationIntensity.STEADY),
        MorningPrompt(311, "Trust the process today, even the slow, unglamorous parts of it.", MotivationIntensity.STEADY),
        MorningPrompt(312, "Let today's discipline speak louder than today's mood.", MotivationIntensity.STEADY),
        MorningPrompt(313, "Today's a good day to make one small promise and actually keep it.", MotivationIntensity.STEADY),
        MorningPrompt(314, "Show up today for the version of yourself who's counting on this effort.", MotivationIntensity.STEADY),
        MorningPrompt(315, "Let today's work be honest, steady, and entirely yours.", MotivationIntensity.STEADY),
        MorningPrompt(316, "Today calls for follow through more than it calls for a fresh start.", MotivationIntensity.STEADY),
        MorningPrompt(317, "You know exactly what today's first step is. Take it now.", MotivationIntensity.STEADY),
        MorningPrompt(318, "Let today's momentum come from doing, not from waiting to feel ready.", MotivationIntensity.STEADY),
        MorningPrompt(319, "Today's a good day to prove reliability matters more than talent alone.", MotivationIntensity.STEADY),
        MorningPrompt(320, "Show today the same steady effort you'd want to see from someone else.", MotivationIntensity.STEADY),
        MorningPrompt(321, "Let today's small task be the thing that unlocks tomorrow's bigger one.", MotivationIntensity.STEADY),
        MorningPrompt(322, "Today's a good day to trust your own preparation.", MotivationIntensity.STEADY),
        MorningPrompt(323, "Let today's effort be quiet proof that you follow through.", MotivationIntensity.STEADY),
        MorningPrompt(324, "Today's a good day to choose the steady path over the flashy shortcut.", MotivationIntensity.STEADY),
        MorningPrompt(325, "Show up for today's small responsibilities. They add up to something bigger.", MotivationIntensity.STEADY),
        MorningPrompt(326, "Let today's decisions be guided by what actually matters to you.", MotivationIntensity.STEADY),
        MorningPrompt(327, "Today's a good day to trade a little comfort for a little progress.", MotivationIntensity.STEADY),
        MorningPrompt(328, "Let today's work be steady enough to build on tomorrow.", MotivationIntensity.STEADY),
        MorningPrompt(329, "Today calls for the kind of effort that doesn't need to be seen to matter.", MotivationIntensity.STEADY),
        MorningPrompt(330, "Trust today's small, deliberate steps. They're doing more than they look like.", MotivationIntensity.STEADY),

        // Energizing, closing set
        MorningPrompt(331, "Get up and give today everything you've been holding back.", MotivationIntensity.ENERGIZING),
        MorningPrompt(332, "Today's not the day for half measures. Go all in.", MotivationIntensity.ENERGIZING),
        MorningPrompt(333, "You have something to prove today, and it's only to yourself.", MotivationIntensity.ENERGIZING),
        MorningPrompt(334, "Stop waiting for a sign. This is the sign.", MotivationIntensity.ENERGIZING),
        MorningPrompt(335, "Today's a day to move with purpose, not just motion.", MotivationIntensity.ENERGIZING),
        MorningPrompt(336, "Get loud with your effort today. Let it be undeniable.", MotivationIntensity.ENERGIZING),
        MorningPrompt(337, "You've got a fire in you this morning. Feed it, don't waste it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(338, "Today's a great day to leave your comfort zone in the dust.", MotivationIntensity.ENERGIZING),
        MorningPrompt(339, "Stop asking permission to want more. Go get it today.", MotivationIntensity.ENERGIZING),
        MorningPrompt(340, "Today rewards the ones who refuse to hit snooze on their own potential.", MotivationIntensity.ENERGIZING),
        MorningPrompt(341, "Bring today the energy you'd bring to something you actually love.", MotivationIntensity.ENERGIZING),
        MorningPrompt(342, "You didn't come this far to slow down now. Push today.", MotivationIntensity.ENERGIZING),
        MorningPrompt(343, "Today's a day to chase the version of yourself you keep talking about.", MotivationIntensity.ENERGIZING),
        MorningPrompt(344, "Get moving. Today isn't going to wait around for perfect timing.", MotivationIntensity.ENERGIZING),
        MorningPrompt(345, "You're stronger today than the version of you who almost gave up last week.", MotivationIntensity.ENERGIZING),
        MorningPrompt(346, "Today's a day to turn hesitation into momentum.", MotivationIntensity.ENERGIZING),
        MorningPrompt(347, "Show today what showing up fully actually looks like.", MotivationIntensity.ENERGIZING),
        MorningPrompt(348, "You've got one shot at today. Don't spend it half awake.", MotivationIntensity.ENERGIZING),
        MorningPrompt(349, "Today's a great day to bet on yourself and actually follow through.", MotivationIntensity.ENERGIZING),
        MorningPrompt(350, "Get after the hard thing first. Everything else gets easier after that.", MotivationIntensity.ENERGIZING),
        MorningPrompt(351, "Today's not asking if you're capable. It's asking if you'll show up.", MotivationIntensity.ENERGIZING),
        MorningPrompt(352, "Bring the intensity today that matches how much this actually matters to you.", MotivationIntensity.ENERGIZING),
        MorningPrompt(353, "Stop waiting to feel unstoppable. Move like you already are.", MotivationIntensity.ENERGIZING),
        MorningPrompt(354, "Today's a great day to make your effort the loudest thing about you.", MotivationIntensity.ENERGIZING),
        MorningPrompt(355, "Get up and chase today down before it chases you.", MotivationIntensity.ENERGIZING),
        MorningPrompt(356, "You've got exactly what today needs. Use every bit of it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(357, "Today's a day to stop planning your comeback and just start it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(358, "Show today the version of you that refuses to settle.", MotivationIntensity.ENERGIZING),
        MorningPrompt(359, "Get moving now. Momentum only exists once you start creating it.", MotivationIntensity.ENERGIZING),
        MorningPrompt(360, "Rise today and make it impossible for anyone to say you didn't try.", MotivationIntensity.ENERGIZING),
    )
}
