package com.tyshi00.trinkets

// Wholesome, dad-style jokes for Trinkets.
//
// PROVENANCE: every entry here was supplied by the project owner. Traditional
// dad jokes are folk humor with no identifiable author and circulate freely.
// Nothing is bulk-copied from a publisher's curated collection or scraped from
// a commercial joke site: individual traditional jokes are fair game, someone
// else's edited compilation is not. See docs/CONTENT.md for sourcing rules.
//
// FORMAT: most entries are setup/punchline. One-liners with no natural question
// borrow one of a handful of rotating openers ("Wanna hear a joke?", "Up for a
// laugh?", and so on) so the tap-to-reveal screen still has something to
// withhold. Keep that set small so the openers stay familiar.
object TrinketsJokes {

    /**
     * Pinned to August 22 by [ContentRepository.PINNED_JOKES] so it comes round
     * every year on that date, instead of drifting with the normal rotation.
     */
    const val SCUBA_JOKE_ID = 1

    val ALL: List<Joke> = listOf(
        Joke(
            SCUBA_JOKE_ID,
            "Why do scuba divers fall backwards out of the boat?",
            "Because if they fell forwards, they would still be in the boat.",
        ),
        Joke(2, "Did you hear about the circus fire?", "It was in tents!"),
        Joke(3, "Did you hear about the guy who invented Lifesavers?", "They say he made a mint!"),
        Joke(4, "Wanna hear a joke?", "I told my wife she should embrace her mistakes. She gave me a hug."),
        Joke(5, "Ready for today's joke?", "I went to buy some camouflage pants, but I couldn't find any."),
        Joke(6, "Up for a laugh?", "I used to have a job at a calendar factory, but I got fired because I took a couple of days off."),
        Joke(7, "Got time for a quick one?", "I was going to tell you a joke about time travel, but you didn't like it."),
        Joke(8, "In the mood for a groaner?", "I used to be a baker, but I couldn't make enough dough."),
        Joke(9, "Did you hear about the guy who got hit in the head with a can of soda?", "He was lucky it was a soft drink."),
        Joke(10, "Want to hear something silly?", "I'm writing a book about glue, but I'm stuck on the first chapter."),
        Joke(11, "What did one plate whisper to the other plate?", "Dinner is on me."),
        Joke(12, "Wanna hear a joke?", "Stop looking for the perfect match; use a lighter."),
        Joke(13, "Ready for today's joke?", "Try the seafood diet, you see food, then you eat it."),
        Joke(14, "Did you hear the rumor about butter?", "Well, I'm not going to go spreading it!"),
        Joke(15, "What's Forrest Gump's password?", "1forrest1"),
        Joke(16, "What state is known for its small drinks?", "Minnesota."),
        Joke(17, "What does a nosey pepper do?", "It gets jalapeno business."),
        Joke(18, "Up for a laugh?", "If two vegetarians get in an argument, is it still called beef?"),
        Joke(19, "Got time for a quick one?", "I have a clean conscience. It's never been used."),
        Joke(20, "In the mood for a groaner?", "I love telling Dad jokes. Sometimes, he even laughs."),
        Joke(21, "How do you stop a bull from charging?", "Cancel its credit card."),
        Joke(22, "What's the difference between a man's wallet before and after kids?", "There are pictures where the money used to be."),
        Joke(23, "How do you follow Will Smith in the mud?", "Follow the fresh prints."),
        Joke(24, "Want to hear something silly?", "My kid gave me a World's Best Dad mug. At least she inherited my sense of humor."),
        Joke(25, "What's 90 degrees but covered with ice?", "The North and South Poles."),
        Joke(26, "What happened when the blue ship and the red ship collided at sea?", "Their crews were marooned."),
        Joke(27, "What's the difference between the bird flu and the swine flu?", "One requires tweetment and the other an oinkment."),
        Joke(28, "What do you call a line of men waiting to get haircuts?", "A barberqueue."),
        Joke(29, "Why do seagulls fly over the sea?", "If they flew over the bay, they would be bagels."),
        Joke(30, "Wanna hear a joke?", "I'm thinking I should do lunges to stay in shape. That would be a big step forward."),
        Joke(31, "What did the baby corn say to the mama corn?", "Where's popcorn?"),
        Joke(32, "What vegetable is cool, but not that cool?", "Radish."),
        Joke(33, "What do you call two monkeys who share an Amazon Prime account?", "Prime mates."),
        Joke(34, "What do you call a beehive without an exit?", "Un-bee-lievable."),
        Joke(35, "Why can't a leopard hide?", "He's always spotted."),
        Joke(36, "Did you hear about the claustrophobic astronaut?", "He just wanted a bit more space."),
        Joke(37, "How do you fix a broken pumpkin?", "With a pumpkin patch."),
        Joke(38, "Why are fish so smart?", "They live in schools!"),
        Joke(39, "Why did the man fall down the well?", "Because he couldn't see that well!"),
        Joke(40, "Why do peppers make such good archers?", "Because they habanero."),
        Joke(41, "What did the sink tell the toilet?", "You look flushed!"),
        Joke(42, "Where do boats go when they're sick?", "To the dock."),
        Joke(43, "What has ears but cannot hear?", "A cornfield!"),
        Joke(44, "Can February March?", "No, but April May!"),
        Joke(45, "Why was 6 afraid of 7?", "Because 7 ate nine!"),
        Joke(46, "Ready for today's joke?", "I'm so good at sleeping that I do it with my eyes closed."),
        Joke(47, "What do you call a pencil with two erasers?", "Pointless."),
        Joke(48, "Did you hear the one about the roof?", "Never mind, it's over your head."),
        Joke(49, "Up for a laugh?", "It really takes guts to be an organ donor."),
        Joke(50, "What did the plumber say to the singer?", "Nice pipes."),
        Joke(51, "Why did the fisherman order the halibut?", "Just for the halibut!"),
        Joke(52, "Why is Peter Pan always flying?", "Because he Neverlands."),
        Joke(53, "What do you call a sleeping bull?", "A bulldozer."),
        Joke(54, "How do you make an octopus laugh?", "With ten-tickles!"),
        Joke(55, "What do you say to a rabbit on its birthday?", "Hoppy Birthday!"),
        Joke(56, "What type of tree fits in your hand?", "A palm tree."),
        Joke(57, "Wanna hear a joke about construction?", "I'm still workin' on it!"),
        Joke(58, "How does a lawyer say goodbye?", "I'll be suing ya!"),
        Joke(59, "What made the tomato blush?", "It saw the salad dressing."),
        Joke(60, "Can I dive in this pool?", "It deep-ends."),
        Joke(61, "Why do vampires always seem sick?", "They're coffin."),
        Joke(62, "What musical instrument do you find in the bathroom?", "A tuba toothpaste!"),
        Joke(63, "Which state has the most streets?", "Rhode Island."),
        Joke(64, "How do astronomers organize a party?", "They planet."),
        Joke(65, "What did the police officer say to her belly button?", "You're under a vest!"),
        Joke(66, "What do you call a fibbing cat?", "A lion."),
        Joke(67, "Got time for a quick one?", "If a child refuses to nap, are they guilty of resisting a rest?"),
        Joke(68, "In the mood for a groaner?", "The coach went to the bank to get his quarterback."),
        Joke(69, "Want to hear something silly?", "I asked my dog what's two minus two. He said nothing."),
        Joke(70, "Wanna hear a joke?", "The first thing Santa's elves learn in school is their elf-abet."),
        Joke(71, "Ready for today's joke?", "Ghosts are bad liars because you can see right through them."),
        Joke(72, "Up for a laugh?", "Shouldn't the roof of your mouth actually be called the ceiling?"),
        Joke(73, "Got time for a quick one?", "All vampires keep their money in a special place, the blood bank."),
        Joke(74, "In the mood for a groaner?", "The pony couldn't sing because it was a little horse."),
        Joke(75, "Want to hear something silly?", "RIP boiling water, you will be mist."),
        Joke(76, "Wanna hear a joke?", "I told my doctor I heard buzzing, but she said it's just a bug that's going around."),
        Joke(77, "Ready for today's joke?", "I ate a clock the other day. It was very time consuming."),
        Joke(78, "Up for a laugh?", "I once wrote a song about a tortilla, but it's more of a wrap."),
        Joke(79, "Got time for a quick one?", "You can tell it's a dogwood tree from its bark."),
        Joke(80, "When does a joke turn into a dad joke?", "When it becomes apparent."),
        Joke(81, "In the mood for a groaner?", "They say that three out of two people are bad at fractions."),
        Joke(82, "Why were the utensils stuck together?", "They were spooning."),
        Joke(83, "How do celebrities stay cool?", "They have many fans."),
        Joke(84, "How does a hurricane see?", "With one eye."),
        Joke(85, "Where do polar bears keep their money?", "The snow bank."),
        Joke(86, "What's a tornado's favorite game?", "Twister!"),
        Joke(87, "How does the moon cut his hair?", "Eclipse it."),
        Joke(88, "What do you call a funny mountain?", "Hill-arious."),
        Joke(89, "What gets wetter the more it dries?", "A towel."),
        Joke(90, "What did the banana say to the boy?", "Nothing, bananas can't talk!"),
        Joke(91, "What rock group has four men who don't sing?", "Mount Rushmore."),
        Joke(92, "Want to hear something silly?", "My boss told me to have a good day, so I went home!"),
        Joke(93, "Wanna hear a joke?", "I was wondering why the frisbee kept getting bigger and bigger. Then it hit me."),
        Joke(94, "Wanna hear a joke about paper?", "Never mind. It's tearable."),
        Joke(95, "How many apples grow on a tree?", "All of them!"),
        Joke(96, "Ready for today's joke?", "I talk to myself because sometimes I just need expert advice."),
        Joke(97, "Up for a laugh?", "I used to be addicted to the hokey-pokey until I turned myself around."),
        Joke(98, "What do you call someone who tells dad jokes but isn't a dad?", "A faux pa."),
        Joke(99, "Got time for a quick one?", "I could tell a joke about pizza, but it's a little cheesy."),
        Joke(100, "In the mood for a groaner?", "If you see a crime at an Apple store, are you an iWitness?"),
        Joke(101, "Why are spiders so smart?", "They can find everything on the web."),
        Joke(102, "What do you give a sick lemon?", "Lemon-aid."),
        Joke(103, "What did the nose tell the finger?", "Stop picking on me!"),
        Joke(104, "What kind of car does a sheep like to drive?", "A lamborghini."),
        Joke(105, "What key is used to open bananas?", "A mon-key."),
        Joke(106, "What has four wheels and flies?", "A garbage truck."),
        Joke(107, "How do you talk to a giant?", "You use big words!"),
        Joke(108, "How do you make a tissue dance?", "Put a little boogie in it!"),
        Joke(109, "What kind of milk comes from a pampered cow?", "Spoiled milk."),
        Joke(110, "What's a sea monster's favorite lunch?", "Fish and ships."),
        Joke(111, "Why are pigs so bad at sports?", "They always hog the ball."),
        Joke(112, "Why couldn't the dad help his son put his shoes on?", "They weren't the dad's size!"),
        Joke(113, "Want to hear something silly?", "Some graduate with honors, I am just honored my kids graduated."),
        Joke(114, "Wanna hear a joke?", "I told my son I was going to buy him a book on procrastination, but I keep putting it off."),
        Joke(115, "Ready for today's joke?", "I told my kids they can be anything they want when they grow up, as long as it's not taller than me."),
        Joke(116, "Up for a laugh?", "My kid told me a joke about boxing. I guess I missed the punch line."),
        Joke(117, "What do you call a cow that just gave birth?", "De-calf-inated."),
        Joke(118, "Got time for a quick one?", "I told my kids to stop playing with their food. So they started playing with their plate instead."),
        Joke(119, "In the mood for a groaner?", "I decided to sell my vacuum cleaner, it was just gathering dust!"),
        Joke(120, "Want to hear something silly?", "I was going to make a joke about the old bed, but then it fell apart."),
        Joke(121, "Why are dads bad detectives?", "Because they only find the evidence after the crime has been committed."),
        Joke(122, "Wanna hear a joke?", "Note to all dads of teens, keep a dog. That way someone is excited to see you!"),
        Joke(123, "What's it like to have the best son in the world?", "You'll have to ask grandpa!"),
        Joke(124, "Ready for today's joke?", "Our wedding was so beautiful, even the cake was in tiers!"),
        Joke(125, "Up for a laugh?", "We have the perfect dad-son relationship. You're my son, and I'm perfect!"),
        Joke(126, "Got time for a quick one?", "I've been thinking about taking up meditation. I figure it's better than sitting around doing nothing!"),
        Joke(127, "In the mood for a groaner?", "I always have a take on everything. My wife calls my explanations dadsplaining."),
        Joke(128, "How many dads does it take to get you to clean your room?", "One, but it takes 18 years!"),
        Joke(129, "Want to hear something silly?", "I smile because I'm your dad, but I laugh because there's nothing you can do about it!"),
        Joke(130, "How do you weigh a millennial?", "In Instagrams."),
        Joke(131, "Why do some couples go to the gym together?", "Because they want their relationship to work out."),
        Joke(132, "What do you call a factory that makes okay products?", "A satisfactory."),
        Joke(133, "Why can't you hear a pterodactyl using the bathroom?", "Silent P."),
        Joke(134, "What did one wall say to the other?", "I'll meet you at the corner."),
        Joke(135, "Did you hear about the kidnapping at school?", "It's fine, he woke up."),
        Joke(136, "Why did the scarecrow win an award?", "Outstanding in his field."),
        Joke(137, "Why did the joke go to therapy?", "It couldn't deliver itself."),
        Joke(138, "I asked my microwave for a loan. What did it say?", "It said it had too many bills."),
        Joke(139, "I told my doctor I broke my arm in two places. What did he say?", "He told me to stop going to those places."),
        Joke(140, "I asked the pharmacist for something to stop my hiccups. What did he do?", "He slapped me."),
        Joke(141, "Why did the baseball keep getting bigger?", "Then it hit me."),
        Joke(142, "Why did the bicycle fall over?", "It was two-tired."),
        Joke(143, "What did the broke teacher say?", "I'm not underpaid, I'm overworked for free."),
        Joke(144, "What else did the broke teacher say?", "I teach with humor, it's cheaper than therapy."),
        Joke(145, "What did the broke college student say?", "My wallet is like an onion, it makes me cry."),
        Joke(146, "What else did the broke college student say?", "I paid for Wi-Fi with exposure."),
        Joke(147, "What did the broke college student say about class?", "I can't afford to pay attention."),
        Joke(148, "What did the broke college student say about grades?", "My GPA and bank balance are in a relationship."),
        Joke(149, "What did the broke college student say about assets?", "My only asset is sarcasm."),
        Joke(150, "Wanna hear a joke?", "I downloaded a joke app, now my phone groans at me."),
        Joke(151, "Ready for today's joke?", "This joke costs nothing and is worth every penny."),
        Joke(152, "Up for a laugh?", "I'm selling a sense of humor. Free samples available."),
        Joke(153, "Got time for a quick one?", "The best things in life are punny, and free."),
        Joke(154, "In the mood for a groaner?", "My jokes are free. Refunds not available."),
        Joke(155, "Want to hear something silly?", "I told my wallet a joke. It remained empty."),
        Joke(156, "Wanna hear a joke?", "I only know 25 letters of the alphabet. I don't know y."),
        Joke(157, "Ready for today's joke?", "I told my wife she was drawing her eyebrows too high. She looked surprised."),
        Joke(158, "Up for a laugh?", "I used to play piano by ear. Now I use my hands."),
        Joke(159, "Got time for a quick one?", "Parallel lines have so much in common. It's a shame they'll never meet."),
        Joke(160, "In the mood for a groaner?", "I tried to catch fog. I mist."),
        Joke(161, "Want to hear something silly?", "Velcro, what a rip-off."),
        Joke(162, "Wanna hear a joke?", "I gave up my seat to a blind person on the bus. That's how I lost my job as a bus driver."),
        Joke(163, "Ready for today's joke?", "I have a joke about construction, but I'm still working on it."),
        Joke(164, "Up for a laugh?", "I told my dog a joke, he pawsed."),
        Joke(165, "Got time for a quick one?", "I have a split personality, and so do I."),
        Joke(166, "In the mood for a groaner?", "My jokes are self-employed. They don't work for everyone."),
        Joke(167, "Want to hear something silly?", "I downloaded a joke virus. Now I laugh randomly."),
        Joke(168, "Wanna hear a joke?", "I post jokes online. The internet doesn't laugh back."),
        Joke(169, "Ready for today's joke?", "I teach math, my jokes don't add up."),
        Joke(170, "Up for a laugh?", "I'm reading a book on anti-gravity. It's impossible to put down."),
        Joke(171, "Got time for a quick one?", "I didn't trust stairs. They're always up to something."),
        Joke(172, "In the mood for a groaner?", "My baker friend quit, he kneaded a break."),
        Joke(173, "Want to hear something silly?", "Time flies like an arrow. Fruit flies like a banana."),
        Joke(174, "Wanna hear a joke?", "The shovel was a groundbreaking invention."),
        Joke(175, "Ready for today's joke?", "I once fell for a pun. It was a slippery slope."),
        Joke(176, "Up for a laugh?", "I told a pun about butter. It spread quickly."),
        Joke(177, "Got time for a quick one?", "Meetings: where minutes are kept and hours are lost."),
        Joke(178, "In the mood for a groaner?", "My computer froze. I offered it a sweater."),
        Joke(179, "Want to hear something silly?", "Don't trust atoms, even in medicine. They make up everything."),
        Joke(180, "Wanna hear a joke?", "I named my dog Five Miles so I can say I walk five miles every day."),
        Joke(181, "Ready for today's joke?", "I used to be a banker, but I lost interest."),
        Joke(182, "Up for a laugh?", "Writing with a broken pencil is pointless."),
        Joke(183, "Got time for a quick one?", "I told a chemistry joke, there was no reaction."),
        Joke(184, "In the mood for a groaner?", "I'm going nowhere fast, and it's cheaper."),
        Joke(185, "What do you call a busy waiter?", "A server."),
        Joke(186, "What do you call an idle server?", "A waiter."),
        Joke(187, "Why was the developer unhappy at their job?", "They wanted arrays."),
        Joke(188, "What's the second movie about a database engineer called?", "The SQL."),
        Joke(189, "Why was the computer freezing?", "It left its Windows open!"),
        Joke(190, "Why don't bachelors like Git?", "Because they are afraid to commit."),
        Joke(191, "What did the server say to his client who was having a bad day?", "Everything's going to be 200."),
        Joke(192, "Why couldn't the user update a file on a shared server?", "They didn't have the write permissions."),
        Joke(193, "How many developers does it take to change a light bulb?", "None. It's a hardware issue."),
        Joke(194, "Why do Java developers wear glasses?", "Because they don't C#!"),
        Joke(195, "What did the psychic say to the developers?", "I see dev people."),
        Joke(196, "Why are keyboards always working so hard?", "Cause they have two shifts!"),
        Joke(197, "What are clouds made of?", "Mostly Linux servers."),
        Joke(198, "Hey officer, how did the hackers escape?", "No idea. They just ransomware."),
        Joke(199, "What did the Network Administrator say when they caught a nasty virus?", "It hurts when IP."),
        Joke(200, "Why do Front-End Developers eat lunch alone?", "Because they don't know how to join tables."),
        Joke(201, "Why do programmers prefer dark mode?", "Because light attracts bugs!"),
        Joke(202, "Why do astronauts use Linux?", "They can't open Windows in space!"),
        Joke(203, "How do front end devs like their brownies?", "GUI."),
        Joke(204, "What did Wonder Woman and Spider-Man name their business?", "Amazon Web Services."),
        Joke(205, "What did the .NET developer name their boat?", "Sea Sharp."),
        Joke(206, "Want to hear something silly?", "Some languages can be read by humans, not by machines. Others can be read by machines but not by humans. XML solves this problem by being readable to neither."),
        Joke(207, "Wanna hear a joke?", "I've been hearing news about this big boolean. Huge if true."),
    )
}
