package com.tyshi00.trinkets

// Short Q&A trivia, featuring unusual, verifiable facts, written originally for
// Trinkets. See docs/CONTENT.md for how to keep growing this bucket.
object TrinketsTrivia {
    val ALL: List<TriviaItem> = listOf(
        TriviaItem(1, "Which planet has a day longer than its year?", "Venus, since it takes about 243 Earth days to rotate once, but only about 225 to orbit the sun."),
        TriviaItem(2, "What color is a polar bear's skin?", "Black. It helps absorb heat from the sun through the bear's translucent fur."),
        TriviaItem(3, "How many hearts does an octopus have?", "Three. Two pump blood to the gills, and one pumps it to the rest of the body."),
        TriviaItem(4, "What's the only mammal capable of true flight?", "The bat. Flying squirrels and similar animals only glide."),
        TriviaItem(5, "Which country has the most time zones?", "France, with 12, thanks to its many overseas territories."),
        TriviaItem(6, "What was the first fruit ever grown in space?", "The tomato, aboard the Salyut 7 space station in 1982 (though astronauts didn't eat it, since it was for research)."),
        TriviaItem(7, "How long can a snail sleep?", "Up to three years at a stretch during periods of extreme heat or cold."),
        TriviaItem(8, "What's unusual about a shrimp's heart?", "It's located in its head."),
        TriviaItem(9, "What food, found sealed in ancient Egyptian tombs, was still edible after 3,000 years?", "Honey. Its low moisture and natural acidity keep it from spoiling almost indefinitely."),
        TriviaItem(10, "What do you call a group of flamingos?", "A flamboyance."),
        TriviaItem(11, "Which country invented the umbrella?", "Ancient China, over 3,000 years ago. Early versions used oiled paper and bamboo."),
        TriviaItem(12, "How many taste buds does a catfish have?", "Around 27,000, spread across its entire body, not just its mouth."),
        TriviaItem(13, "What is the tallest grass in the world?", "Bamboo. Some species can grow nearly a meter in a single day."),
        TriviaItem(14, "Which animal has a memory that can last decades?", "The elephant, which can recognize other elephants and humans after many years apart."),
        TriviaItem(15, "What was Bubblegum originally colored?", "It was intended to be pink simply because that was the only dye the inventor had on hand in 1928, and the color stuck as the standard ever since."),
        TriviaItem(16, "Which US state was once an independent country for nine years?", "Texas, from 1836 to 1845."),
        TriviaItem(17, "How fast can a sneeze travel?", "Up to about 100 miles per hour."),
        TriviaItem(18, "What's the only letter that doesn't appear in any US state name?", "Q."),
        TriviaItem(19, "Which animal's fingerprints are nearly identical to a human's?", "The koala's, close enough that they've occasionally confused crime scene investigators."),
        TriviaItem(20, "What do you call a baby hedgehog?", "A hoglet."),
        TriviaItem(21, "How many bones does a giraffe have in its neck?", "Seven, the same number as a human, just much larger."),
        TriviaItem(22, "Which ocean is technically the saltiest?", "The Atlantic, although the Red Sea has an even higher salinity for a marginal sea."),
        TriviaItem(23, "What is a group of crows called?", "A murder."),
        TriviaItem(24, "Which country gifted the Statue of Liberty to the United States?", "France, in 1886, to mark the centennial of American independence."),
        TriviaItem(25, "How many hours a day does a koala typically sleep?", "Around 18 to 22 hours, largely due to the low energy content of its eucalyptus diet."),
        TriviaItem(26, "What is the world's largest living structure?", "The Great Barrier Reef in Australia, visible even from space."),
        TriviaItem(27, "Which fruit is technically a berry, but a strawberry is not?", "The banana, botanically speaking."),
        TriviaItem(28, "What was the first item ever scanned with a barcode?", "A pack of Wrigley's chewing gum, in an Ohio supermarket in 1974."),
        TriviaItem(29, "How many hearts does an earthworm have?", "Five pairs of aortic arches that function like hearts."),
        TriviaItem(30, "Which country consumes the most tea per capita?", "Turkey."),
        TriviaItem(31, "What is the loudest animal on Earth relative to its size?", "The pistol shrimp, which snaps its claw to create a sound-producing bubble louder than a gunshot."),
        TriviaItem(32, "Which continent has no native ant species until fairly recently?", "Antarctica has none at all, even now."),
        TriviaItem(33, "What is the national instrument of Trinidad and Tobago?", "The steelpan (steel drum), invented there in the mid-20th century."),
        TriviaItem(34, "How long is a day on Mercury compared to its year?", "One day on Mercury (sunrise to sunrise) lasts about 176 Earth days, longer than its 88-day year."),
        TriviaItem(35, "What's unusual about a cat's collarbone?", "It isn't attached to any other bone, letting cats squeeze through very narrow spaces."),
        TriviaItem(36, "Which African country was never colonized by a European power?", "Ethiopia, aside from a brief Italian occupation from 1936 to 1941."),
        TriviaItem(37, "What is the only food that never spoils?", "Honey, when stored properly and sealed."),
        TriviaItem(38, "How many species of penguin are there?", "Eighteen recognized species, and only two, the Emperor and Adélie, live exclusively on the Antarctic continent."),
        TriviaItem(39, "What ancient civilization invented the concept of zero as a number?", "Mathematicians in ancient India, with the concept later refined and transmitted through the Islamic world."),
        TriviaItem(40, "Which everyday spice was once worth more than gold by weight?", "Saffron."),
        TriviaItem(41, "What is the fastest-growing plant in the world?", "Certain species of bamboo."),
        TriviaItem(42, "How many muscles does it take a cat to purr?", "None directly. Purring is produced by rapid, repeated signals to the muscles of the voice box and diaphragm."),
        TriviaItem(43, "Which country has more pyramids than Egypt?", "Sudan, home to over 200 ancient Nubian pyramids."),
        TriviaItem(44, "What is the smallest bone in the human body?", "The stapes, located in the middle ear."),
        TriviaItem(45, "Which bird can fly backwards?", "The hummingbird, thanks to its unique flexible wing joints."),
        TriviaItem(46, "What was the first computer 'bug' actually caused by?", "A real moth that got trapped in the Harvard Mark II computer's relay in 1947."),
        TriviaItem(47, "Which country is home to the world's largest desert, the Sahara, spans how many nations?", "Parts of the Sahara stretch across eleven countries in North Africa."),
        TriviaItem(48, "How many hearts does a hagfish have?", "Four."),
        TriviaItem(49, "What is the world's oldest known living tree species?", "Ginkgo biloba, which has existed largely unchanged for over 200 million years."),
        TriviaItem(50, "Which Southeast Asian country's flag is the only non-rectangular national flag?", "Nepal."),
        TriviaItem(51, "What is a baby rabbit called?", "A kit or kitten."),
        TriviaItem(52, "How much of a jellyfish is water?", "About 95 percent."),
        TriviaItem(53, "Which South American country is named after an Italian city?", "Venezuela is often translated as 'Little Venice,' after explorers noted stilt houses resembling the Italian city."),
        TriviaItem(54, "What was the original purpose of bubble wrap?", "It was invented in 1957 as a textured wallpaper before being repurposed for packaging."),
        TriviaItem(55, "Which animal can rotate its ears 180 degrees?", "The rabbit."),
        TriviaItem(56, "What percentage of the ocean has been explored by humans?", "Less than about 20 percent, by most scientific estimates."),
        TriviaItem(57, "Which two countries have square, rather than rectangular, national flags?", "Switzerland and Vatican City."),
        TriviaItem(58, "How many eyes does a bee have?", "Five. Two large compound eyes and three small simple eyes."),
        TriviaItem(59, "Which country produces the most vanilla in the world?", "Madagascar."),
        TriviaItem(60, "What is unusual about a flamingo's knee?", "What looks like a backward-bending knee is actually its ankle; the true knee is hidden higher up, close to the body."),
        TriviaItem(61, "How far can a chameleon's tongue extend relative to its body?", "Up to twice its own body length."),
        TriviaItem(62, "Which country introduced the numeral system now used worldwide?", "India, through mathematicians who developed the base-10 positional system later called 'Arabic numerals' as it spread through the Islamic world into Europe."),
        TriviaItem(63, "What is a group of jellyfish called?", "A smack."),
        TriviaItem(64, "Which island nation is made up of over 17,000 islands?", "Indonesia."),
        TriviaItem(65, "How long can a cockroach survive without its head?", "About a week, until it eventually dies of thirst."),
        TriviaItem(66, "What was the first animal to be cloned from an adult cell?", "Dolly the sheep, in 1996."),
        TriviaItem(67, "Which country has the most active volcanoes?", "Indonesia, with well over 100."),
        TriviaItem(68, "What is the only mammal that can't jump?", "The elephant."),
        TriviaItem(69, "Which South American mountain range is the longest in the world?", "The Andes, stretching about 7,000 kilometers."),
        TriviaItem(70, "How many times does an average person's heart beat in a lifetime?", "Roughly 2.5 to 3 billion times."),
        TriviaItem(71, "Which nut is not actually a nut, botanically speaking?", "The peanut. It's a legume."),
        TriviaItem(72, "What color was Coca-Cola's original formula?", "Its syrup was actually greenish, and it remains a similar amber-brown from caramel coloring today."),
        TriviaItem(73, "Which country has three capital cities?", "South Africa: Pretoria (executive), Cape Town (legislative), and Bloemfontein (judicial)."),
        TriviaItem(74, "What is a group of owls called?", "A parliament."),
        TriviaItem(75, "How many wings does a dragonfly have?", "Four, and each pair moves independently."),
        TriviaItem(76, "Which country has a floating market that has operated for over a century?", "Thailand's Damnoen Saduak floating market, near Bangkok."),
        TriviaItem(77, "What is unique about a rhinoceros's horn?", "It's made of keratin, the same protein found in human hair and fingernails."),
        TriviaItem(78, "Which African kingdom's ancient capital, Great Zimbabwe, gives the modern country its name?", "Zimbabwe."),
        TriviaItem(79, "How many legs does a lobster have?", "Ten, including its two front claws."),
        TriviaItem(80, "What was the world's first postage stamp called?", "The Penny Black, issued in Britain in 1840."),
        TriviaItem(81, "Which planet in our solar system spins in the opposite direction from most others?", "Venus, which rotates in the opposite direction to most planets, a trait called retrograde rotation."),
        TriviaItem(82, "What is the tallest mountain in Africa?", "Mount Kilimanjaro in Tanzania, at just over 5,895 meters."),
        TriviaItem(83, "How many chambers does a human heart have?", "Four: two atria and two ventricles."),
        TriviaItem(84, "Which country has the longest coastline in the world?", "Canada, with a coastline stretching well over 200,000 kilometers."),
        TriviaItem(85, "What do you call baby kangaroos?", "Joeys."),
        TriviaItem(86, "Which metal is liquid at room temperature?", "Mercury."),
        TriviaItem(87, "How many bones are in the adult human body?", "206."),
        TriviaItem(88, "What is the largest species of big cat?", "The tiger, with the Siberian subspecies being the largest of all."),
        TriviaItem(89, "Which country invented paper?", "China, during the Han dynasty, around two thousand years ago."),
        TriviaItem(90, "What is the smallest country in the world by land area?", "Vatican City."),
        TriviaItem(91, "How many legs does a spider have?", "Eight."),
        TriviaItem(92, "What is the driest place on Earth?", "The Atacama Desert in Chile, parts of which have gone decades without measurable rainfall."),
        TriviaItem(93, "Which bird lays the largest egg relative to its body size?", "The kiwi, native to New Zealand."),
        TriviaItem(94, "What do you call a group of lions?", "A pride."),
        TriviaItem(95, "How many hearts does a squid have?", "Three."),
        TriviaItem(96, "Which African country was formerly known as Abyssinia?", "Ethiopia."),
        TriviaItem(97, "What is the fastest land animal?", "The cheetah, capable of reaching speeds of around 70 miles per hour."),
        TriviaItem(98, "How many teeth does an adult human typically have?", "Thirty two, including wisdom teeth."),
        TriviaItem(99, "Which South American country shares a border with the most other countries?", "Brazil, which borders all South American countries except Chile and Ecuador."),
        TriviaItem(100, "What is the tallest waterfall in the world?", "Angel Falls in Venezuela, at over 979 meters."),
        TriviaItem(101, "How many strings does a standard violin have?", "Four."),
        TriviaItem(102, "Which gas makes up the majority of Earth's atmosphere?", "Nitrogen, at roughly 78 percent."),
        TriviaItem(103, "What is a group of fish called?", "A school, or sometimes a shoal."),
        TriviaItem(104, "Which country has the most natural lakes?", "Canada, home to hundreds of thousands of lakes."),
        TriviaItem(105, "How long is the human small intestine on average?", "Around 6 meters, or about 20 feet."),
        TriviaItem(106, "What is the largest island in the world?", "Greenland."),
        TriviaItem(107, "Which insect can lift many times its own body weight?", "The ant, which can carry loads many times heavier than itself."),
        TriviaItem(108, "What do you call a young eagle?", "An eaglet."),
        TriviaItem(109, "Which African country has the largest population?", "Nigeria."),
        TriviaItem(110, "What is the hardest natural substance on Earth?", "Diamond."),
        TriviaItem(111, "How many hours does it take Earth to complete one rotation?", "About 24 hours, or more precisely, 23 hours and 56 minutes."),
        TriviaItem(112, "Which country produces the most coffee in the world?", "Brazil."),
        TriviaItem(113, "What do you call a group of geese on the ground?", "A gaggle."),
        TriviaItem(114, "Which desert is the largest hot desert in the world?", "The Sahara, in North Africa."),
        TriviaItem(115, "How many bones make up the human skull?", "Twenty two."),
        TriviaItem(116, "Which country has the highest number of official languages?", "South Africa, with eleven official languages."),
        TriviaItem(117, "What is a baby goat called?", "A kid."),
        TriviaItem(118, "Which mammal is known for sleeping the longest each day?", "The koala, though the little brown bat also sleeps extremely long hours."),
        TriviaItem(119, "What is the longest river in the world?", "The Nile, though some measurements favor the Amazon as slightly longer."),
        TriviaItem(120, "Which country has the most volcanoes still considered active?", "Indonesia, with well over 100 active volcanoes."),
        TriviaItem(121, "How many muscles are in the human body?", "Around 600, though estimates vary depending on how they're counted."),
        TriviaItem(122, "What do you call a group of frogs?", "An army."),
        TriviaItem(123, "Which country has the most time zones due to its geography alone?", "Russia, spanning eleven time zones."),
        TriviaItem(124, "What is the tallest tree species in the world?", "The coast redwood, found in California."),
        TriviaItem(125, "Which animal has the longest lifespan among mammals?", "The bowhead whale, which can live well over 200 years."),
        TriviaItem(126, "What is the smallest bird in the world?", "The bee hummingbird, native to Cuba."),
        TriviaItem(127, "Which country is home to the Amazon Rainforest's largest share?", "Brazil, home to about 60 percent of the Amazon."),
        TriviaItem(128, "What do you call a group of rhinos?", "A crash."),
        TriviaItem(129, "How many time zones does China officially use?", "Just one, despite spanning a geographic area wide enough for five."),
        TriviaItem(130, "Which gemstone is the birthstone for April?", "The diamond."),
        TriviaItem(131, "What is the largest desert in the world by total area?", "Antarctica, technically classified as a cold desert due to its low precipitation."),
        TriviaItem(132, "Which country has the most pyramids in the world?", "Sudan."),
        TriviaItem(133, "What is a group of crows sitting together typically called?", "A murder, when discussing crows as a whole group."),
        TriviaItem(134, "How many hearts does a cockroach have?", "One, though it has multiple segments that help pump blood."),
        TriviaItem(135, "Which country has the largest population in the world?", "India, which recently surpassed China."),
        TriviaItem(136, "What do you call a baby owl?", "An owlet."),
        TriviaItem(137, "Which country has more official languages recognized than any other in Asia?", "India, with 22 scheduled languages."),
        TriviaItem(138, "What is the deepest point in the ocean?", "The Challenger Deep in the Mariana Trench."),
        TriviaItem(139, "Which continent is home to the most countries?", "Africa, with 54 recognized countries."),
        TriviaItem(140, "What do you call a group of butterflies?", "A kaleidoscope."),
        TriviaItem(141, "Which planet has the most moons currently known?", "Saturn, with well over 100 confirmed moons."),
        TriviaItem(142, "What is the coldest inhabited place on Earth?", "Oymyakon, a village in Siberia, Russia."),
        TriviaItem(143, "Which African country is completely surrounded by another country?", "Lesotho, entirely encircled by South Africa."),
        TriviaItem(144, "What do you call a group of dolphins?", "A pod."),
        TriviaItem(145, "Which country has the most UNESCO World Heritage Sites?", "Italy."),
        TriviaItem(146, "What is the largest organ in the human body?", "The skin."),
        TriviaItem(147, "Which country grows the most rice in the world?", "China."),
        TriviaItem(148, "What is a group of hippos called?", "A bloat."),
        TriviaItem(149, "Which South American country is the only one with both Atlantic and Caribbean coastlines?", "Colombia."),
        TriviaItem(150, "What is the world's largest amphibian?", "The Chinese giant salamander."),
        TriviaItem(151, "Which country has the most active airports in the world?", "The United States, by a wide margin."),
        TriviaItem(152, "What do you call a group of zebras?", "A dazzle."),
        TriviaItem(153, "Which country is the largest by land area?", "Russia."),
        TriviaItem(154, "What is the loudest animal in the ocean?", "The sperm whale, whose clicks can reach extremely high decibel levels."),
        TriviaItem(155, "Which country has the world's oldest continuously running parliament?", "Iceland, whose Althing dates back to the year 930."),
        TriviaItem(156, "What do you call a young whale?", "A calf."),
        TriviaItem(157, "Which planet has the strongest winds in the solar system?", "Neptune, where winds can exceed 1,200 miles per hour."),
        TriviaItem(158, "What is the most spoken native language in the world?", "Mandarin Chinese."),
        TriviaItem(159, "Which African country was the first to gain independence from colonial rule in the twentieth century's wave of decolonization?", "Libya, in 1951, ahead of most of the continent."),
        TriviaItem(160, "What do you call a group of turtles?", "A bale."),
        TriviaItem(161, "Which country has the highest number of active volcanoes relative to its size?", "Iceland, given how small the country is compared to its volcanic activity."),
        TriviaItem(162, "What is the largest species of penguin?", "The emperor penguin."),
        TriviaItem(163, "Which South American country is the only one without a coastline?", "Bolivia, along with Paraguay."),
        TriviaItem(164, "What do you call a group of otters on land?", "A romp."),
        TriviaItem(165, "Which country has the most islands in the world?", "Sweden, with over 250,000 islands, most of them uninhabited."),
        TriviaItem(166, "What is the fastest fish in the ocean?", "The sailfish, which can reach speeds of over 60 miles per hour."),
        TriviaItem(167, "Which Asian country consists entirely of islands?", "Indonesia, and also the Philippines."),
        TriviaItem(168, "What do you call a group of pandas?", "An embarrassment."),
        TriviaItem(169, "Which country has the largest number of pyramids constructed by an ancient civilization outside Egypt?", "Sudan, home to the ancient Nubian pyramids."),
        TriviaItem(170, "What is the tallest animal in the world?", "The giraffe."),
        TriviaItem(171, "Which country has the world's largest population of elephants?", "Botswana."),
        TriviaItem(172, "What do you call a group of foxes?", "A skulk."),
        TriviaItem(173, "Which country invented tea as a widely cultivated beverage?", "China, thousands of years ago."),
        TriviaItem(174, "What is the largest species of shark?", "The whale shark, though it is a gentle filter feeder."),
        TriviaItem(175, "Which country has the highest literacy rate in Africa?", "Equatorial Guinea and Seychelles both rank among the highest."),
        TriviaItem(176, "What do you call a group of wolves?", "A pack."),
        TriviaItem(177, "Which planet has a giant storm known as the Great Red Spot?", "Jupiter."),
        TriviaItem(178, "What is the world's smallest ocean?", "The Arctic Ocean."),
        TriviaItem(179, "Which Central American country has no standing army?", "Costa Rica, which abolished its military in 1949."),
        TriviaItem(180, "What do you call a group of eagles?", "A convocation."),
        TriviaItem(181, "Which country is home to the largest number of tigers in the wild?", "India."),
        TriviaItem(182, "What is the tallest active volcano in the world?", "Ojos del Salado, on the border of Chile and Argentina."),
        TriviaItem(183, "Which country has the most extensive rail network in Africa?", "South Africa."),
        TriviaItem(184, "What do you call a group of monkeys?", "A troop."),
        TriviaItem(185, "Which country produces the most cocoa in the world?", "Ivory Coast, also known as Cote d'Ivoire."),
        TriviaItem(186, "What is the largest freshwater lake in the world by surface area?", "Lake Superior, in North America."),
        TriviaItem(187, "Which country has the highest point in South America?", "Argentina, home to Aconcagua."),
        TriviaItem(188, "What do you call a group of jellyfish?", "A smack, or sometimes a bloom."),
        TriviaItem(189, "Which country has the largest Muslim population in the world?", "Indonesia."),
        TriviaItem(190, "What is the smallest planet in our solar system?", "Mercury."),
        TriviaItem(191, "Which country produces the most gold in Africa?", "Ghana, historically one of the continent's leading gold producers."),
        TriviaItem(192, "What do you call a group of camels?", "A caravan."),
        TriviaItem(193, "Which country has the world's largest reserve of fresh water by volume?", "Brazil, largely due to the Amazon basin."),
        TriviaItem(194, "What is the fastest bird in level flight?", "The peregrine falcon, though its diving speed is even faster."),
        TriviaItem(195, "Which country hosts the ancient city of Petra?", "Jordan."),
        TriviaItem(196, "What do you call a group of bats?", "A colony, or sometimes a cloud."),
        TriviaItem(197, "Which country is home to the Serengeti?", "Tanzania."),
        TriviaItem(198, "What is the largest cat species native to the Americas?", "The jaguar."),
        TriviaItem(199, "Which country has the most active tea plantations in Asia?", "China, followed closely by India."),
        TriviaItem(200, "What do you call a group of kangaroos?", "A mob."),
        TriviaItem(201, "Which country is the world's largest producer of silk?", "China."),
        TriviaItem(202, "What is the longest mountain range in the world?", "The Andes, spanning much of the west coast of South America."),
        TriviaItem(203, "Which country has the oldest known university still in operation?", "Morocco, home to the University of al-Qarawiyyin, founded in 859."),
        TriviaItem(204, "What do you call a group of parrots?", "A pandemonium."),
        TriviaItem(205, "Which country has the highest average elevation in the world?", "Bhutan."),
        TriviaItem(206, "What is the world's largest coral reef system?", "The Great Barrier Reef, off the coast of Australia."),
        TriviaItem(207, "Which country produces the most bananas in the world?", "India."),
        TriviaItem(208, "What do you call a group of squirrels?", "A scurry."),
        TriviaItem(209, "Which country has the largest desert entirely within its own borders?", "Australia, home to the Great Victoria Desert."),
        TriviaItem(210, "What is the smallest continent by land area?", "Australia."),
        TriviaItem(211, "Which country is home to the ancient ruins of Great Zimbabwe?", "Zimbabwe."),
        TriviaItem(212, "What do you call a group of flamingos standing together?", "A flamboyance, or sometimes a stand."),
        TriviaItem(213, "Which country has the world's busiest airport by passenger traffic?", "The United States, home to Hartsfield-Jackson Atlanta International."),
        TriviaItem(214, "What is the tallest building in the world?", "The Burj Khalifa, in Dubai, United Arab Emirates."),
        TriviaItem(215, "Which country has the largest number of official time zones internationally?", "France, due to its many overseas territories."),
        TriviaItem(216, "What do you call a group of giraffes?", "A tower."),
        TriviaItem(217, "Which country is the birthplace of chess as it's known today?", "India, where an early version of the game originated before spreading through Persia."),
        TriviaItem(218, "What is the largest species of turtle?", "The leatherback sea turtle."),
        TriviaItem(219, "Which country has the highest number of natural UNESCO World Heritage Sites in Africa?", "The Democratic Republic of the Congo."),
        TriviaItem(220, "What do you call a group of peacocks?", "A muster, or sometimes an ostentation."),
        TriviaItem(221, "Which country has the most extensive network of canals in Europe?", "The Netherlands."),
        TriviaItem(222, "What is the largest rodent in the world?", "The capybara, native to South America."),
        TriviaItem(223, "Which country was home to the ancient Inca Empire?", "Peru, primarily, though the empire extended into neighboring countries."),
        TriviaItem(224, "What do you call a group of sharks?", "A shiver."),
        TriviaItem(225, "Which country has the largest number of active mosques in Africa?", "Nigeria, home to a very large Muslim population."),
        TriviaItem(226, "What is the world's tallest freestanding structure that isn't a building?", "The Tokyo Skytree, in Japan."),
        TriviaItem(227, "Which country produces the most olive oil in the world?", "Spain."),
        TriviaItem(228, "What do you call a group of cheetahs?", "A coalition."),
        TriviaItem(229, "Which country has the world's largest salt flat?", "Bolivia, home to the Salar de Uyuni."),
        TriviaItem(230, "What is the deepest lake in the world?", "Lake Baikal, in Russia."),
        TriviaItem(231, "Which country produces the most tea in Africa?", "Kenya, one of the world's leading tea exporters."),
        TriviaItem(232, "What do you call a group of hedgehogs?", "An array."),
        TriviaItem(233, "Which country has the most extensive subway system by station count?", "The United States, largely due to the New York City subway."),
        TriviaItem(234, "What is the largest known flower in the world?", "The corpse flower, native to Sumatra, Indonesia."),
        TriviaItem(235, "Which country hosts the ancient city of Timbuktu?", "Mali."),
        TriviaItem(236, "What do you call a group of storks?", "A muster."),
        TriviaItem(237, "Which country has the world's highest capital city?", "Bolivia, home to La Paz."),
        TriviaItem(238, "What is the fastest land bird?", "The ostrich, capable of running at speeds over 40 miles per hour."),
        TriviaItem(239, "Which country is the origin of the tulip before it became associated with the Netherlands?", "Turkey, and the broader Central Asian region."),
        TriviaItem(240, "What do you call a group of ravens?", "An unkindness."),
        TriviaItem(241, "Which country has the world's largest mangrove forest?", "Bangladesh and India share the Sundarbans, the largest mangrove forest on Earth."),
        TriviaItem(242, "What is the largest species of owl?", "The Blakiston's fish owl, native to parts of Asia."),
        TriviaItem(243, "Which country is home to the Atacama Desert?", "Chile."),
        TriviaItem(244, "What do you call a group of gorillas?", "A band."),
        TriviaItem(245, "Which country has the highest number of ancient rock art sites in Africa?", "Namibia, along with South Africa."),
        TriviaItem(246, "What is the largest known type of squid?", "The colossal squid, found in the deep waters of the Southern Ocean."),
        TriviaItem(247, "Which country produces the most wine in the world?", "Italy, closely followed by France and Spain."),
        TriviaItem(248, "What do you call a group of bees?", "A swarm."),
        TriviaItem(249, "Which country has the tallest waterfall entirely within Africa?", "The Democratic Republic of the Congo, home to some of the continent's most powerful falls."),
        TriviaItem(250, "What is the largest bird by wingspan?", "The wandering albatross, whose wingspan can exceed 11 feet."),
        TriviaItem(251, "Which country is the origin of the game of polo?", "Persia, in what is now Iran, though it later spread widely through Central and South Asia."),
        TriviaItem(252, "What do you call a group of moose?", "A herd."),
        TriviaItem(253, "Which country produces the most cinnamon in the world?", "Indonesia, followed closely by Sri Lanka and China."),
        TriviaItem(254, "What is the smallest species of horse?", "The Falabella, a miniature breed originating in Argentina."),
        TriviaItem(255, "Which country has the world's largest population of wild lions?", "Tanzania."),
        TriviaItem(256, "What do you call a group of walruses?", "A herd, or sometimes a pod."),
        TriviaItem(257, "Which country has the largest network of ancient qanats, or underground water channels?", "Iran."),
        TriviaItem(258, "What is the world's second tallest mountain?", "K2, located on the border of Pakistan and China."),
        TriviaItem(259, "Which country produces the most saffron in the world?", "Iran, by a wide margin."),
        TriviaItem(260, "What do you call a group of swans?", "A bevy, or sometimes a wedge when flying."),
        TriviaItem(261, "Which country has the largest network of ancient underground cities?", "Turkey, in the Cappadocia region."),
        TriviaItem(262, "What is the largest species of crocodile?", "The saltwater crocodile."),
        TriviaItem(263, "Which country is the world's leading producer of cassava?", "Nigeria."),
        TriviaItem(264, "What do you call a group of ants?", "A colony."),
        TriviaItem(265, "Which country has the highest number of active tea houses per capita in the world?", "Turkey, where tea culture runs especially deep."),
        TriviaItem(266, "What is the world's rarest big cat?", "The Amur leopard, native to parts of Russia and China."),
        TriviaItem(267, "Which country produces the most quinoa in the world?", "Peru, closely followed by Bolivia."),
        TriviaItem(268, "What do you call a group of deer?", "A herd."),
        TriviaItem(269, "Which country is home to the ancient Nazca Lines?", "Peru."),
        TriviaItem(270, "What is the largest species of eagle by wingspan?", "The Philippine eagle, among the largest and rarest eagles in the world."),
        TriviaItem(271, "Which country has the world's oldest known calendar system still referenced today?", "Ethiopia, whose calendar differs by roughly seven years from the Gregorian one."),
        TriviaItem(272, "What do you call a group of buffalo?", "A gang, or sometimes an obstinacy."),
        TriviaItem(273, "Which country produces the most cardamom in the world?", "Guatemala, followed closely by India."),
        TriviaItem(274, "What is the tallest species of grass used commonly for building material?", "Bamboo."),
        TriviaItem(275, "Which country is home to the ancient city of Great Zimbabwe's stone ruins?", "Zimbabwe, giving the modern nation its name."),
        TriviaItem(276, "What do you call a group of ducks on water?", "A raft."),
        TriviaItem(277, "Which country has the world's longest continuous mountain chain entirely on one continent?", "Chile and Argentina share the Andes, the longest range in the world."),
        TriviaItem(278, "What is the largest species of manta ray?", "The oceanic manta ray."),
        TriviaItem(279, "Which country produces the most rubber in the world?", "Thailand."),
        TriviaItem(280, "What do you call a group of herons?", "A siege."),
        TriviaItem(281, "Which country is home to the largest network of ancient terraced farmland in South America?", "Peru, especially around the Sacred Valley near Cusco."),
        TriviaItem(282, "What is the largest known species of ape?", "The eastern gorilla."),
        TriviaItem(283, "Which country produces the most palm oil in the world?", "Indonesia, closely followed by Malaysia."),
        TriviaItem(284, "What do you call a group of vultures circling in the air?", "A kettle."),
        TriviaItem(285, "Which country is home to the ancient rock-hewn churches of Lalibela?", "Ethiopia."),
        TriviaItem(286, "What is the largest species of bear?", "The polar bear, closely rivaled by the Kodiak brown bear."),
        TriviaItem(287, "Which country produces the most millet in the world?", "India."),
        TriviaItem(288, "What do you call a group of vultures at rest?", "A committee, or sometimes a venue."),
        TriviaItem(289, "Which country has the highest number of active volcanoes in South America?", "Chile."),
        TriviaItem(290, "What is the largest venomous snake in the world?", "The king cobra."),
        TriviaItem(291, "Which country produces the most tea by weight in the world?", "China."),
        TriviaItem(292, "What do you call a group of larks?", "An exaltation."),
        TriviaItem(293, "Which country is home to the ancient trading city of Djenne?", "Mali, home to the Great Mosque of Djenne, the largest mud brick building in the world."),
        TriviaItem(294, "What is the largest freshwater fish in the world?", "The beluga sturgeon, found mainly in the Caspian and Black Sea basins."),
        TriviaItem(295, "Which country produces the most figs in the world?", "Turkey."),
        TriviaItem(296, "What do you call a group of magpies?", "A tiding, or sometimes a parliament."),
        TriviaItem(297, "Which country has the highest number of active geysers in the world?", "The United States, largely thanks to Yellowstone National Park."),
        TriviaItem(298, "What is the largest species of otter?", "The giant otter, found in South America."),
        TriviaItem(299, "Which country is the origin of the sport of sumo wrestling?", "Japan."),
        TriviaItem(300, "What do you call a group of pelicans?", "A pod, or sometimes a scoop."),
        TriviaItem(301, "Which country has the highest number of active hot air balloon festivals per year?", "Turkey, especially in the Cappadocia region."),
        TriviaItem(302, "What is the largest species of jellyfish?", "The lion's mane jellyfish, whose tentacles can stretch over 100 feet."),
        TriviaItem(303, "Which country produces the most cloves in the world?", "Indonesia."),
        TriviaItem(304, "What do you call a group of woodpeckers?", "A descent."),
        TriviaItem(305, "Which country is home to the ancient walled city of Fez?", "Morocco."),
        TriviaItem(306, "What is the largest species of tortoise?", "The Galapagos tortoise."),
        TriviaItem(307, "Which country produces the most dates in the world?", "Egypt."),
        TriviaItem(308, "What do you call a group of hawks?", "A kettle when flying, or a cast when at rest."),
        TriviaItem(309, "Which country is home to the ancient city of Petra's neighbor, the Wadi Rum desert?", "Jordan."),
        TriviaItem(310, "What is the largest species of scorpion?", "The giant forest scorpion, found in parts of Africa and Asia."),
        TriviaItem(311, "Which country produces the most pistachios in the world?", "Iran, closely followed by the United States."),
        TriviaItem(312, "What do you call a group of toucans?", "A durante."),
        TriviaItem(313, "Which country is home to the terraced rice fields of Banaue?", "The Philippines."),
        TriviaItem(314, "What is the largest species of chameleon?", "The Parson's chameleon, native to Madagascar."),
        TriviaItem(315, "Which country produces the most yams in the world?", "Nigeria, by a wide margin."),
        TriviaItem(316, "What do you call a group of finches?", "A charm."),
        TriviaItem(317, "Which country is home to the ancient temple complex of Angkor Wat?", "Cambodia."),
        TriviaItem(318, "What is the largest species of beetle by weight?", "The Goliath beetle, native to Africa."),
        TriviaItem(319, "Which country produces the most avocados in the world?", "Mexico."),
        TriviaItem(320, "What do you call a group of nightingales?", "A watch."),
        TriviaItem(321, "Which country is home to the ancient city of Carthage?", "Tunisia."),
        TriviaItem(322, "What is the largest species of gecko?", "The New Caledonian giant gecko."),
        TriviaItem(323, "Which country produces the most mangoes in the world?", "India."),
        TriviaItem(324, "What do you call a group of hummingbirds?", "A charm, or sometimes a bouquet."),
        TriviaItem(325, "Which country is home to the salt pans of the Danakil Depression?", "Ethiopia, one of the hottest inhabited places on Earth."),
        TriviaItem(326, "What is the largest species of starfish?", "The sunflower sea star, which can have up to two dozen arms."),
        TriviaItem(327, "Which country produces the most sesame seeds in the world?", "Sudan, closely followed by Myanmar and India."),
        TriviaItem(328, "What do you call a group of quail?", "A covey, or sometimes a bevy."),
        TriviaItem(329, "Which country is home to the ancient city of Persepolis?", "Iran."),
        TriviaItem(330, "What is the largest species of moth by wingspan?", "The Atlas moth, found across Southeast Asia."),
        TriviaItem(331, "Which country produces the most ginger in the world?", "India."),
        TriviaItem(332, "What do you call a group of sparrows?", "A host."),
        TriviaItem(333, "Which country is home to the ancient rock city of Sigiriya?", "Sri Lanka."),
        TriviaItem(334, "What is the largest species of freshwater turtle?", "The Cantor's giant softshell turtle, found across parts of Asia."),
        TriviaItem(335, "Which country produces the most black pepper in the world?", "Vietnam."),
        TriviaItem(336, "What do you call a group of orioles?", "A pitch."),
        TriviaItem(337, "Which country is home to the ancient city of Ayutthaya?", "Thailand."),
        TriviaItem(338, "What is the largest species of lemur?", "The indri, native to Madagascar."),
        TriviaItem(339, "Which country produces the most coconuts in the world?", "Indonesia, closely followed by the Philippines and India."),
        TriviaItem(340, "What do you call a group of crickets?", "An orchestra."),
        TriviaItem(341, "Which country is home to the ancient city of Bagan and its thousands of temples?", "Myanmar."),
        TriviaItem(342, "What is the largest species of anteater?", "The giant anteater, found across Central and South America."),
        TriviaItem(343, "Which country produces the most cashews in the world?", "Ivory Coast."),
        TriviaItem(344, "What do you call a group of penguins on land?", "A waddle."),
        TriviaItem(345, "Which country is home to the terracotta warriors?", "China."),
        TriviaItem(346, "What is the largest species of iguana?", "The Galapagos land iguana."),
        TriviaItem(347, "Which country produces the most tobacco in the world?", "China."),
        TriviaItem(348, "What do you call a group of penguins in the water?", "A raft."),
        TriviaItem(349, "Which country is home to the ancient Silk Road city of Samarkand?", "Uzbekistan."),
        TriviaItem(350, "What is the largest species of salamander?", "The Chinese giant salamander, which can grow to nearly six feet."),
        TriviaItem(351, "Which country produces the most soybeans in the world?", "Brazil, followed closely by the United States."),
        TriviaItem(352, "What do you call a group of antelope?", "A herd."),
        TriviaItem(353, "Which country is home to the floating villages of Lake Titicaca?", "Peru, shared with Bolivia along the lake's shores."),
        TriviaItem(354, "What is the largest species of pangolin?", "The giant pangolin, found across parts of Africa."),
        TriviaItem(355, "Which country produces the most tomatoes in the world?", "China."),
        TriviaItem(356, "What do you call a group of impalas?", "A herd, sometimes described as a leap when startled into motion."),
        TriviaItem(357, "Which country is home to the ancient walled city of Xi'an?", "China."),
        TriviaItem(358, "What is the largest species of frog?", "The goliath frog, found in Cameroon and Equatorial Guinea."),
        TriviaItem(359, "Which country produces the most chili peppers in the world?", "China."),
        TriviaItem(360, "What do you call a group of storks in flight?", "A wedge."),
    )
}
