[tool]
id = "com.tyshi00.trinkets"
label = "Trinkets"
versionCode = 3
versionName = "1.0.3"
permissions = []
# change if you run this on an LP3!
# serverPackage = "com.lightos"
serverPackage = "com.thelightphone.sdk.emulator"
